In [2]:
!export PINECONE_API_KEY="pcsk_32aTpD_BYKjuc5114NyjcLQHZWofdGJLP9daLtmNKgX53rfkmeGiTYD8xsPUeypd18gyfe"
import os
from pinecone import Pinecone
os.environ["PINECONE_API_KEY"] = "pcsk_32aTpD_BYKjuc5114NyjcLQHZWofdGJLP9daLtmNKgX53rfkmeGiTYD8xsPUeypd18gyfe"
os.environ["OPENAI_API_KEY"] = "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"
print("Pinecone API Key:", os.getenv("PINECONE_API_KEY"))
pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY")) 
 

# %load_ext autoreload
# %autoreload 2
# %reload_ext autoreload 
from Search_or_Discuss import classify_and_extract
from data_utils import fetch_papers, verify_results, chunk_papers
from Database import create_index, save_embeddings_to_index, delete_index
from retrieval import answer_query, clear_memory, retrieve_chunks
from pinecone import Pinecone
import io
import contextlib
# Create the index once (assuming it should persist during the conversation)
import pandas as pd
from urllib.error import HTTPError
# 假设这些函数已经定义：create_index, pc.Index, classify_and_extract, fetch_papers,
# verify_results, chunk_papers, save_embeddings_to_index, answer_query, delete_index, clear_memory
import asyncio
# 创建索引
from ragas.dataset_schema import SingleTurnSample
from ragas.metrics import SemanticSimilarity
from ragas.embeddings import LangchainEmbeddingsWrapper
from clearml import Task, Logger

Pinecone API Key: pcsk_32aTpD_BYKjuc5114NyjcLQHZWofdGJLP9daLtmNKgX53rfkmeGiTYD8xsPUeypd18gyfe

'export' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

In [3]:

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

In [4]:
%env CLEARML_WEB_HOST=https://app.5ccsagap.er.kcl.ac.uk/
%env CLEARML_API_HOST=https://api.5ccsagap.er.kcl.ac.uk
%env CLEARML_FILES_HOST=https://files.5ccsagap.er.kcl.ac.uk
# GAP_group3_embedding
%env CLEARML_API_ACCESS_KEY=F3JFSR84AVXM6OTRRRUBQ5QPVHMTWV
%env CLEARML_API_SECRET_KEY=tda_99OfnqWYSguFYS5wH6FtKuVBoryYeREQVh2MPdcXct0hGiNEnfxeIOBpXPH1fcE

from clearml import Task, Logger
task = Task.init(
    project_name="MyProject", 
    task_name="Embedding Comparison - inegrated env"
)

env: CLEARML_WEB_HOST=https://app.5ccsagap.er.kcl.ac.uk/
env: CLEARML_API_HOST=https://api.5ccsagap.er.kcl.ac.uk
env: CLEARML_FILES_HOST=https://files.5ccsagap.er.kcl.ac.uk
env: CLEARML_API_ACCESS_KEY=F3JFSR84AVXM6OTRRRUBQ5QPVHMTWV
env: CLEARML_API_SECRET_KEY=tda_99OfnqWYSguFYS5wH6FtKuVBoryYeREQVh2MPdcXct0hGiNEnfxeIOBpXPH1fcE
ClearML Task: overwriting (reusing) task id=d53955fcc381421d8c5e89263d364ec2
ClearML results page: https://app.5ccsagap.er.kcl.ac.uk/projects/f6c6e15540994198a771be0667091232/experiments/d53955fcc381421d8c5e89263d364ec2/output/log

In [5]:
from pinecone import Pinecone

indexes = pc.list_indexes()

# 逐个删除
for idx in indexes:
    index_name = idx["name"]
    pc.delete_index(index_name)
    print(f"Deleted index: {index_name}")

CLEARML-SERVER new package available: UPGRADE to v2.0.0 is recommended!
Release Notes:
### Breaking Changes

MongoDB major version was upgraded from v5.x to 6.x.
Please note that if your current ClearML Server version is smaller than v1.17 (where MongoDB v5.x was first used), you'll need to first upgrade to ClearML Server v1.17.
#### Upgrading to ClearML Server v1.17 from a previous version
- If using docker-compose,  use the following docker-compose files:
  * [docker-compose file](https://github.com/allegroai/clearml-server/blob/2976ce69cc91550a3614996e8a8d8cd799af2efd/upgrade/1_17_to_2_0/docker-compose.yml)
  * [docker-compose file foe Windows](https://github.com/allegroai/clearml-server/blob/2976ce69cc91550a3614996e8a8d8cd799af2efd/upgrade/1_17_to_2_0/docker-compose-win10.yml)

### New Features

- New look and feel: Full light/dark themes ([clearml #1297](https://github.com/allegroai/clearml/issues/1297))
- New UI task creation options
  - Support bash as well as python scripts
  - Support file upload
- New UI setting for configuring cloud storage credentials with which ClearML can clean up cloud storage artifacts on task deletion.
- Add UI scalar plots presentation of plots in sections grouped by metrics.
- Add UI Batch export plot embed codes for all metric plots in a single click.
- Add UI pipeline presentation of steps grouped into stages

### Bug Fixes
- Fix UI Model Endpoint's Number of Requests plot sometimes displays incorrect data
- Fix UI datasets page does not filter according to project when dataset is running
- Fix UI task scalar legend does not change colors when smoothing is enabled
- Fix queue list in UI Workers and Queues page does not alphabetically sort by queue display name
- Fix queue display name is not searchable in UI Task Creation modal's queue field

ClearML Monitor: GPU monitoring failed getting GPU reading, switching off GPU monitoring
2025-03-29 22:12:35,396 - clearml.Repository Detection - WARNING - Can't get diff information for git repo in c:\Users\guoji\Group-3\gjwenv\Lib\site-packages

Deleted index: woc64a51bt
Deleted index: g1ze6wzztb
Deleted index: wh3pku3qm9
Deleted index: 8xkvyxtznx

In [6]:
index_name = create_index()
index_obj = pc.Index(index_name)

Index '8xkvyxtznx' created successfully!

In [7]:
def retrieve_ans(user_input, index_obj): 
    classification = classify_and_extract(user_input)
    filters = classification['filters']
    print("\nRunning Search with filters:", filters)
    # 第一步：获取papers
    papers = fetch_papers(filters)
    # 第二步：验证与过滤papers
    filtered_papers = verify_results(papers, filters)
    # 第三步：对papers进行分块
    paper_chunks = chunk_papers(filtered_papers)
    # 遍历前3个chunk，打印部分内容，并保存embedding到index 
    for i, chunk in enumerate(paper_chunks[:3]):
        # print(f"\nChunk {i+1}:\n{chunk.page_content[:300]}...")
        save_embeddings_to_index(index_name=index_name, text=[chunk.page_content])

    ans = retrieve_chunks(user_input, index_obj)

    return ans

In [8]:
import pandas as pd
filename = "../evaluation_data/question_answer.csv"
df = pd.read_csv(filename, encoding='gbk')
print(df.head(0))

Empty DataFrame
Columns: [question, answer, paper, reference paragraph 1, reference paragraph 2, reference paragraph 3, similar_question]
Index: []

# Evaluate text-embedding-3-small

In [9]:
from dotenv import load_dotenv
import os 
load_dotenv()
os.environ["EMBEDDING_MODEL"] = "text-embedding-3-small"
os.environ["USE_OPENAI_EMBEDDINGS"] = 'True'

model_name = os.getenv("EMBEDDING_MODEL", "text-embedding-3-small")
print("Using embedding model:", model_name)

model_name = os.getenv("USE_OPENAI_EMBEDDINGS", 'True')
print("whether use openai embedding model:", model_name)
# sometimes you need to restart the kernel in order for this env settings to work

Using embedding model: text-embedding-3-small
whether use openai embedding model: True

In [10]:
import sys
sys.setrecursionlimit(10000)

In [ ]:
import pandas as pd
import numpy as np
import builtins 




# 加载预训练的 SentenceTransformer 模型
model = SentenceTransformer('all-MiniLM-L6-v2')

# 假设 df 已经加载，包含以下列：
# 'question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 例如：df = pd.read_csv("your_dataset.csv")

all_scores = []         # 用于存储每个 question 的 3 个 cosine similarity 分数
comparison_results = [] # 用于存储所有比较结果，稍后转换成 DataFrame

# 遍历 DataFrame 中的每一行（假设有10个问题，即 10 行，共 3*10 比较）
for idx, row in df.iterrows():
    print("=" * 60)
    print(f"Question {idx+1}:")
    print(row['question'])
    print("=" * 60)
    
    # 用户查询即当前行的 question
    user_query = row['question']
    
    # 参考文本列表，顺序与检索结果顺序对应
    ref_paragraphs = [
        row['reference paragraph 1'],
        row['reference paragraph 2'],
        row['reference paragraph 3']
    ]
    
    # 调用检索函数获取结果，返回的 ans 是一个列表，每个元素为 { "text": ..., "source": ... }
    try:
        ans = retrieve_ans(user_query, index_obj)
    except KeyError as e:
        print(f"KeyError encountered for question {idx+1}: {e}. Skipping this question.\n")
        continue

    if ans == 0 or len(ans) < 3:
        print(f"WARNING: No sufficient results for question {idx+1}: {user_query}\n")
        continue
    
    scores = []
    # 针对前三个结果进行比较：第一条检索结果对应第一个参考段落，依此类推
    for i in range(3):
        result_text = ans[i]['text']
        ref_text = ref_paragraphs[i]
        
        print(f"\n--- Comparison {i+1} ---")
        print("Retrieved Result:")
        print(result_text)
        print("\nReference Paragraph:")
        print(ref_text)
        
        # 分别生成两段文本的 embedding
        emb_result = model.encode(result_text, convert_to_tensor=True)
        emb_ref = model.encode(ref_text, convert_to_tensor=True)
        
        # 计算 cosine similarity（util.cos_sim 返回的是 tensor）
        score = util.cos_sim(emb_result, emb_ref)
        similarity = score.item()
        scores.append(similarity)
        
        print(f"\nCosine Similarity for Comparison {i+1}: {similarity:.4f}")
        
        # 记录当前比较结果到 comparison_results 列表中
        comparison_results.append({
            "question": user_query,
            "comparison_index": i+1,
            "retrieved_result": result_text,
            "reference_paragraph": ref_text,
            "cosine_similarity": similarity
        })
    
    print("\nSimilarity scores for Question {}: {}".format(idx+1, scores))
    all_scores.append(scores)

# 将所有分数转换为 numpy 数组，shape 为 (num_questions, 3)
score_matrix = np.array(all_scores)
print("\n" + "=" * 60)
print("Cosine Similarity Matrix:")
print(score_matrix)

# 计算所有相似度的均值
mean_score = score_matrix.mean()
print("\nMean Cosine Similarity: {:.4f}".format(mean_score))

# 将所有比较结果转换为 DataFrame 并打印输出
comparison_df = pd.DataFrame(comparison_results)
print("\nComparison Results DataFrame:")
print(comparison_df)

============================================================
Question 1:
Search for the question: Describe the K-means clustering algorithm.
============================================================

Running Search with filters: {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: K-means clustering algorithm
----------------------------------------------------------------------------------------------------

Title: An implementation of the relational k-means algorithm
- Author(s): Balázs Szalkai
- Category: cs.LG
- Abstract (first 200 chars): A C# implementation of a generalized k-means variant called relational
k-means is described here. Relational k-means is a generalization of the
well-known k-means clustering method which works for non...
- Submitted Date: 2013-04-25 12:59:31+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Popcorn: Accelerating Kernel K-means on GPUs through Sparse Linear Algebra
- Author(s): Julian Bellavita, Thomas Pasquali, Laura Del Rio Martin, Flavio Vella, Giulia Guidi
- Category: cs.DC
- Abstract (first 200 chars): K-means is a popular clustering algorithm with significant applications in
numerous scientific and engineering areas. One drawback of K-means is its
inability to identify non-linearly separable cluste...
- Submitted Date: 2025-01-09 21:43:16+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Performance Evaluation of Incremental K-means Clustering Algorithm
- Author(s): Sanjay Chakraborty, N. K. Nagwani
- Category: cs.IR
- Abstract (first 200 chars): The incremental K-means clustering algorithm has already been proposed and
analysed in paper [Chakraborty and Nagwani, 2011]. It is a very innovative
approach which is applicable in periodically incre...
- Submitted Date: 2014-06-18 14:34:18+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Elkan's k-Means for Graphs
- Author(s): Brijnesh J. Jain, Klaus Obermayer
- Category: cs.AI
- Abstract (first 200 chars): This paper extends k-means algorithms from the Euclidean domain to the domain
of graphs. To recompute the centroids, we apply subgradient methods for solving
the optimization-based formulation of the ...
- Submitted Date: 2009-12-23 10:30:11+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Extraction of Protein Sequence Motif Information using PSO K-Means
- Author(s): R. Gowri, R. Rathipriya
- Category: cs.CV
- Abstract (first 200 chars): The main objective of the paper is to find the motif information.The
functionalities of the proteins are ideally found from their motif information
which is extracted using various techniques like clu...
- Submitted Date: 2015-04-09 09:53:44+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Wide Gaps and Clustering Axioms
- Author(s): Mieczysław A. Kłopotek
- Category: cs.LG
- Abstract (first 200 chars): The widely applied k-means algorithm produces clusterings that violate our
expectations with respect to high/low similarity/density and is in conflict
with Kleinberg's axiomatic system for distance ba...
- Submitted Date: 2023-08-07 10:43:48+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Breathing K-Means: Superior K-Means Solutions through Dynamic K-Values
- Author(s): Bernd Fritzke
- Category: cs.LG
- Abstract (first 200 chars): We introduce the breathing k-means algorithm, which on average significantly
improves solutions obtained by the widely-known greedy k-means++ algorithm, the
default method for k-means clustering in th...
- Submitted Date: 2020-06-28 17:49:37+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Improving the K-means algorithm using improved downhill simplex search
- Author(s): Ehsan Saboori, Shafigh Parsazad, Anoosheh Sadeghi
- Category: cs.LG
- Abstract (first 200 chars): The k-means algorithm is one of the well-known and most popular clustering
algorithms. K-means seeks an optimal partition of the data by minimizing the
sum of squared error with an iterative optimizat...
- Submitted Date: 2012-09-05 03:02:26+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A new Initial Centroid finding Method based on Dissimilarity Tree for K-means Algorithm
- Author(s): Abhishek Kumar, Suresh Chandra Gupta
- Category: cs.LG
- Abstract (first 200 chars): Cluster analysis is one of the primary data analysis technique in data mining
and K-means is one of the commonly used partitioning clustering algorithm. In
K-means algorithm, resulting set of clusters...
- Submitted Date: 2015-06-19 11:43:14+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Ball k-means
- Author(s): Shuyin Xia, Daowan Peng, Deyu Meng, Changqing Zhang, Guoyin Wang, Zizhong Chen, Wei Wei
- Category: cs.LG
- Abstract (first 200 chars): This paper presents a novel accelerated exact k-means algorithm called the
Ball k-means algorithm, which uses a ball to describe a cluster, focusing on
reducing the point-centroid distance computation...
- Submitted Date: 2020-05-02 10:39:26+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Final Papers Matching All Filters: 10

Extracted 39 chunks from 'An implementation of the relational k-means algorithm'
Extracted 156 chunks from 'Popcorn: Accelerating Kernel K-means on GPUs through Sparse Linear Algebra'
Extracted 42 chunks from 'Performance Evaluation of Incremental K-means Clustering Algorithm'
Extracted 104 chunks from 'Elkan's k-Means for Graphs'
Extracted 48 chunks from 'Extraction of Protein Sequence Motif Information using PSO K-Means'
Extracted 106 chunks from 'Wide Gaps and Clustering Axioms'
Extracted 180 chunks from 'Breathing K-Means: Superior K-Means Solutions through Dynamic K-Values'
Extracted 33 chunks from 'Improving the K-means algorithm using improved downhill simplex search'
Extracted 40 chunks from 'A new Initial Centroid finding Method based on Dissimilarity Tree for K-means Algorithm'
Extracted 28 chunks from 'Ball k-means'

Total Chunks Extracted: 776

Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
results:  {'matches': [], 'namespace': 'default', 'usage': {'read_units': 1}}
! No relevant documents found in Pinecone
WARNING: No sufficient results for question 1: Search for the question: Describe the K-means clustering algorithm.

============================================================
Question 2:
Search for the question: Explain the Typiclust algorithm
============================================================

Running Search with filters: {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: Typiclust algorithm
----------------------------------------------------------------------------------------------------

Title: Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets
- Author(s): Guy Hacohen, Avihu Dekel, Daphna Weinshall
- Category: cs.LG
- Abstract (first 200 chars): Investigating active learning, we focus on the relation between the number of
labeled examples (budget size), and suitable querying strategies. Our
theoretical analysis shows a behavior reminiscent of...
- Submitted Date: 2022-02-06 15:09:05+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Bridging Diversity and Uncertainty in Active learning with Self-Supervised Pre-Training
- Author(s): Paul Doucet, Benjamin Estermann, Till Aczel, Roger Wattenhofer
- Category: cs.LG
- Abstract (first 200 chars): This study addresses the integration of diversity-based and uncertainty-based
sampling strategies in active learning, particularly within the context of
self-supervised pre-trained models. We introduc...
- Submitted Date: 2024-03-06 14:18:24+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A Note on the Performance of Algorithms for Solving Linear Diophantine Equations in the Naturals
- Author(s): Valeriu Motroi, Stefan Ciobaca
- Category: cs.DS
- Abstract (first 200 chars): We implement four algorithms for solving linear Diophantine equations in the
naturals: a lexicographic enumeration algorithm, a completion procedure, a
graph-based algorithm, and the Slopes algorithm....
- Submitted Date: 2021-04-12 04:45:00+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Critic Algorithms using Cooperative Networks
- Author(s): Debangshu Banerjee, Kavita Wagh
- Category: cs.AI
- Abstract (first 200 chars): An algorithm is proposed for policy evaluation in Markov Decision Processes
which gives good empirical results with respect to convergence rates. The
algorithm tracks the Projected Bellman Error and i...
- Submitted Date: 2022-01-19 19:47:18+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Quantum Hidden Subgroup Algorithms: An Algorithmic Toolkit
- Author(s): Samuel J. Lomonaco Jr., Louis H. Kauffman
- Category: quant-ph
- Abstract (first 200 chars): One of the most promising and versatile approaches to creating new quantum
algorithms is based on the quantum hidden subgroup (QHS) paradigm, originally
suggested by Alexei Kitaev. This class of quant...
- Submitted Date: 2006-07-06 18:50:51+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Arc-Search Infeasible Interior-Point Algorithm for Linear Programming
- Author(s): Yaguang Yang
- Category: math.OC
- Abstract (first 200 chars): Mehrotra's algorithm has been the most successful infeasible interior-point
algorithm for linear programming since 1990. Most popular interior-point
software packages for linear programming are based ...
- Submitted Date: 2014-06-17 20:53:29+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: An Algorithm Computing the Local $b$ Function by an Approximate Division Algorithm in $\hat{\mathcal{D}}$
- Author(s): Hiromasa Nakayama
- Category: math.RA
- Abstract (first 200 chars): We give an algorithm to compute the local $b$ function. In this algorithm, we
use the Mora division algorithm in the ring of differential operators and an
approximate division algorithm in the ring of...
- Submitted Date: 2006-06-19 06:39:46+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Critical Analysis: Bat Algorithm based Investigation and Application on Several Domains
- Author(s): Shahla U. Umar, Tarik A. Rashid
- Category: cs.NE
- Abstract (first 200 chars): In recent years several swarm optimization algorithms, such as Bat Algorithm
(BA) have emerged, which was proposed by Xin-She Yang in 2010. The idea of the
algorithm was taken from the echolocation ab...
- Submitted Date: 2021-01-18 19:25:12+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Quantum Algorithms
- Author(s): Michele Mosca
- Category: quant-ph
- Abstract (first 200 chars): This article surveys the state of the art in quantum computer algorithms,
including both black-box and non-black-box results. It is infeasible to detail
all the known quantum algorithms, so a represen...
- Submitted Date: 2008-08-04 02:14:39+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A Novel Genetic Algorithm using Helper Objectives for the 0-1 Knapsack Problem
- Author(s): Jun He, Feidun He, Hongbin Dong
- Category: cs.NE
- Abstract (first 200 chars): The 0-1 knapsack problem is a well-known combinatorial optimisation problem.
Approximation algorithms have been designed for solving it and they return
provably good solutions within polynomial time. ...
- Submitted Date: 2014-04-03 11:46:42+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Final Papers Matching All Filters: 10

Extracted 179 chunks from 'Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets'
Extracted 55 chunks from 'Bridging Diversity and Uncertainty in Active learning with Self-Supervised Pre-Training'
Extracted 51 chunks from 'A Note on the Performance of Algorithms for Solving Linear Diophantine Equations in the Naturals'
Extracted 53 chunks from 'Critic Algorithms using Cooperative Networks'

In [ ]:
comparison_df

,question,comparison_index,retrieved_result,reference_paragraph,cosine_similarity
0,Search for the question: Explain the concept o...,1,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,Defines PCA as a transformation technique.,0.264818
1,Search for the question: Explain the concept o...,2,"arbitrary distance matrix, as opposed to the t...",Explains conversion of original variables to u...,0.171778
2,Search for the question: Explain the concept o...,3,centroids. The standard k-means method [2] att...,Discusses PCA's application in dimensionality ...,0.361076
3,Search for the question: What is the Support V...,1,which can learn a suitable piece-wise linear l...,Defines SVM and its objective to maximize the ...,0.514465
4,Search for the question: What is the Support V...,2,"1995)(Vapnik, 2013)(Gunn, 1998) are still very...",Explains the role of support vectors in formin...,0.374085
5,Search for the question: What is the Support V...,3,Learning a powerful SVM using piece-wise linea...,Mentions use of kernel functions for non-linea...,0.388488
6,Search for the question: Describe the backprop...,1,ZORB: A Derivative-Free Backpropagation\nAlgor...,Introduces backpropagation as a method for err...,0.544076
7,Search for the question: Describe the backprop...,2,training a neural network with gradient descen...,Details the forward and backward passes and gr...,0.452051
8,Search for the question: Describe the backprop...,3,with 11 layers on MNIST and observed that ZORB...,Highlights iterative weight updates using grad...,0.411738
9,Search for the question: What are Convolutiona...,1,convolution) as far as we know.\n1 Introductio...,Describes CNN architecture for image recognition.,0.531200
10,Search for the question: What are Convolutiona...,2,ILP-M C ONV: O PTIMIZE CONVOLUTION ALGORITHM F...,Details convolutional and pooling layers for f...,0.402432
11,Search for the question: What are Convolutiona...,3,network inference algorithm on mobile GPUs is ...,Presents state-of-the-art performance in compu...,0.330296
12,Search for the question: Explain the concept o...,1,ZORB: A Derivative-Free Backpropagation\nAlgor...,"Outlines the RL framework including agents, st...",0.112818
13,Search for the question: Explain the concept o...,2,Learning a powerful SVM using piece-wise linea...,Describes learning through trial and error int...,0.127133
14,Search for the question: Explain the concept o...,3,training a neural network with gradient descen...,Mentions key algorithms like Q-learning and po...,0.409618
15,Search for the question: What is the differenc...,1,"1995)(Vapnik, 2013)(Gunn, 1998) are still very...",Defines Type I and Type II errors in hypothesi...,0.027854
16,Search for the question: What is the differenc...,2,which can learn a suitable piece-wise linear l...,Explains the implications of false positives a...,-0.020845
17,Search for the question: What is the differenc...,3,Learning a powerful SVM using piece-wise linea...,Emphasizes the need for balancing sensitivity ...,0.089222
18,Search for the question: How does the Gradient...,1,ZORB: A Derivative-Free Backpropagation\nAlgor...,Introduces Gradient Descent for optimizing los...,0.586798
19,Search for the question: How does the Gradient...,2,and its update is more accurate. We combine th...,Explains iterative updates and gradient comput...,0.435443
20,Search for the question: How does the Gradient...,3,Scaling transition from momentum stochastic gr...,Highlights the importance of learning rate in ...,0.429036
21,Search for the question: What is Overfitting i...,1,vide recommendations for possible solutions. W...,Defines overfitting as the model capturing noi...,0.508399
22,Search for the question: What is Overfitting i...,2,Machine Learning Students Overﬁt to Overﬁtting...,Discusses regularization methods such as L1 an...,0.545277
23,Search for the question: What is Overfitting i...,3,tation. This has driven the demand of machine ...,Mentions cross-validation and dropout as strat...,0.430333
24,Search for the question: what is concept of Tr...,1,Such an ability to acquire and reuse knowledge...,Introduces Transfer Learning as leveraging pre...,0.564895
25,Search for the question: what is concept of Tr...,2,Transferability in Deep Learning: A Survey\nTr...,Describes the process of fine-tuning and adapt...,0.290523
26,Search for the question: what is concept of Tr...,3,tation. This has driven the demand of machine ...,Highlights benefits in reducing training time ...,0.362457

In [ ]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - text-embedding-3-small",          # 在ClearML中显示的标题
    series="Retrieval Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=comparison_df             # 直接传入 DataFrame
)

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import util
 

# 假设 df 已经加载，并且包含以下列：
# 'question', 'similar_question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 此外，之前生成的 comparison_df 包含原始 question 对应的 retrieval 结果，列包括：
# "question", "comparison_index", "retrieved_result", "reference_paragraph", "cosine_similarity"

# 用于存储新比较结果的列表
new_comparison_results = []

# 遍历 df 的前 10 行（或需要的数量）
for idx, row in df.head(10).iterrows():
    orig_question = row['question']
    sim_question = row['similar_question']
    
    print("=" * 60)
    print(f"Processing row {idx+1}:")
    print("Original Question:")
    print(orig_question)
    print("Similar Question:")
    print(sim_question)
    print("=" * 60)
    
    # 获取原始问题的 retrieval 结果
    # 从之前的 comparison_df 筛选出原始问题对应的 retrieval 结果（保证顺序为 1-3）
    orig_results_df = comparison_df[comparison_df['question'] == orig_question]
    if orig_results_df.empty or len(orig_results_df) < 3:
        print(f"WARNING: No sufficient retrieval results for original question {idx+1}. Skipping row.")
        continue
    
    orig_results = orig_results_df.sort_values("comparison_index")["retrieved_result"].tolist()
    
    # 获取相似问题的 retrieval 结果（调用检索函数）
    ans_sim = retrieve_ans(sim_question, index_obj)
    if ans_sim == 0 or len(ans_sim) < 3:
        print(f"WARNING: No sufficient retrieval results for similar question {idx+1}. Skipping row.")
        continue
    sim_results = [item['text'] for item in ans_sim[:3]]
    
    # 计算原始问题与相似问题本身的 cosine similarity
    emb_orig_question = model.encode(orig_question, convert_to_tensor=True)
    emb_sim_question = model.encode(sim_question, convert_to_tensor=True)
    query_cos_sim = util.cos_sim(emb_orig_question, emb_sim_question).item()
    
    # 对于对应位置的 retrieval 结果进行比较：只比较对应的 1 对 1, 2 对 2, 3 对 3
    for i in range(3):
        orig_text = orig_results[i]
        sim_text = sim_results[i]
        
        emb_orig = model.encode(orig_text, convert_to_tensor=True)
        emb_sim = model.encode(sim_text, convert_to_tensor=True)
        retrieval_cos_sim = util.cos_sim(emb_orig, emb_sim).item()
        
        new_comparison_results.append({
            "original_question": orig_question,
            "similar_question": sim_question,
            "comparison_index": i+1,
            "orig_retrieved_result": orig_text,
            "sim_retrieved_result": sim_text,
            "retrieval_cosine_similarity": retrieval_cos_sim,
            "query_cosine_similarity": query_cos_sim
        })
        
        print(f"\nComparison {i+1}:")
        print("Original Retrieval Result:")
        print(orig_text)
        print("\nSimilar Retrieval Result:")
        print(sim_text)
        print(f"\nRetrieval Cosine Similarity: {retrieval_cos_sim:.4f}")
    
    print(f"\nQuery Cosine Similarity (Original vs. Similar Question): {query_cos_sim:.4f}")

# 将所有新比较结果转换为 DataFrame
similarity_comparison_df = pd.DataFrame(new_comparison_results)
print("\nNew Comparison Results DataFrame:")
print(similarity_comparison_df)

# 如需计算所有 retrieval_cosine_similarity 的平均值
mean_retrieval_cos_sim = similarity_comparison_df["retrieval_cosine_similarity"].mean()
mean_query_cos_sim = similarity_comparison_df["query_cosine_similarity"].mean()

print("\nMean Retrieval Cosine Similarity: {:.4f}".format(mean_retrieval_cos_sim))
print("Mean Query Cosine Similarity: {:.4f}".format(mean_query_cos_sim))

============================================================
Processing row 1:
Original Question:
Search for the question: Describe the K-means clustering algorithm.
Similar Question:
Search for the question: Can you explain how the K-means clustering algorithm works?
============================================================
WARNING: No sufficient retrieval results for original question 1. Skipping row.
============================================================
Processing row 2:
Original Question:
Search for the question: Explain the concept of Principal Component Analysis (PCA).
Similar Question:
Search for the question: What is the fundamental idea behind Principal Component Analysis (PCA)?
============================================================

Running Search with filters: {'query': 'Principal Component Analysis', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: Principal Component Analysis
----------------------------------------------------------------------------------------------------

Title: Principal components of nuclear mass models
- Author(s): X. H. Wu, P. W. Zhao
- Category: nucl-th
- Abstract (first 200 chars): The principal component analysis approach is employed to extract the
principal components contained in nuclear mass models for the first time. The
effects coming from different nuclear mass models are...
- Submitted Date: 2024-05-24 12:08:46+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A note on the prediction error of principal component regression
- Author(s): Martin Wahl
- Category: math.ST
- Abstract (first 200 chars): We analyse the prediction error of principal component regression (PCR) and
prove non-asymptotic upper bounds for the corresponding squared risk. Under
mild assumptions, we show that PCR performs as w...
- Submitted Date: 2018-11-07 16:59:35+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Moment Analysis
- Author(s): Magnus Fontes, Rasmus Henningsson
- Category: math.ST
- Abstract (first 200 chars): Principal Moment Analysis is a method designed for dimension reduction,
analysis and visualization of high dimensional multivariate data. It
generalizes Principal Component Analysis and allows for sig...
- Submitted Date: 2020-03-09 15:48:29+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Symbolic principal plane with Duality Centers Method
- Author(s): Oldemar Rodriguez
- Category: stat.ME
- Abstract (first 200 chars): In \cite{ref11} and \cite{ref3}, the authors proposed the Centers and the
Vertices Methods to extend the well known principal components analysis method
to a particular kind of symbolic objects charac...
- Submitted Date: 2024-01-10 02:21:01+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Sparse Principal Component Analysis with missing observations
- Author(s): Karim Lounici
- Category: math.ST
- Abstract (first 200 chars): In this paper, we study the problem of sparse Principal Component Analysis
(PCA) in the high-dimensional setting with missing observations. Our goal is to
estimate the first principal component when w...
- Submitted Date: 2012-05-31 18:29:32+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Component Analysis for Functional Data on Riemannian Manifolds and Spheres
- Author(s): Xiongtao Dai, Hans-Georg Müller
- Category: math.ST
- Abstract (first 200 chars): Functional data analysis on nonlinear manifolds has drawn recent interest.
Sphere-valued functional data, which are encountered for example as movement
trajectories on the surface of the earth, are an...
- Submitted Date: 2017-05-17 16:02:17+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Derivative Principal Component Analysis for Representing the Time Dynamics of Longitudinal and Functional Data
- Author(s): Xiongtao Dai, Hans-Georg Müller, Wenwen Tao
- Category: stat.ME
- Abstract (first 200 chars): We propose a nonparametric method to explicitly model and represent the
derivatives of smooth underlying trajectories for longitudinal data. This
representation is based on a direct Karhunen--Lo\`eve ...
- Submitted Date: 2017-07-14 00:45:45+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Basis Analysis in Sparse Representation
- Author(s): Hong Sun, Cheng-Wei Sang, Chen-Guang Liu
- Category: cs.CV
- Abstract (first 200 chars): This article introduces a new signal analysis method, which can be
interpreted as a principal component analysis in sparse decomposition of the
signal. The method, called principal basis analysis, is ...
- Submitted Date: 2015-11-25 01:11:24+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Visualisation of financial time series by linear principal component analysis and nonlinear principal component analysis
- Author(s): Hao-Che Chen
- Category: q-fin.MF
- Abstract (first 200 chars): In this dissertation, the main goal is visualisation of financial time
series. We expect that visualisation of financial time series will be a useful
auxiliary for technical analysis. Firstly, we revi...
- Submitted Date: 2014-10-29 12:59:42+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A unified framework of principal component analysis and factor analysis
- Author(s): Shifeng Xiong
- Category: stat.ME
- Abstract (first 200 chars): Principal component analysis and factor analysis are fundamental multivariate
analysis methods. In this paper a unified framework to connect them is
introduced. Under a general latent variable model, ...
- Submitted Date: 2024-05-30 15:13:40+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Final Papers Matching All Filters: 10

Extracted 89 chunks from 'Principal components of nuclear mass models'
Extracted 82 chunks from 'A note on the prediction error of principal component regression'
Extracted 38 chunks from 'Principal Moment Analysis'
Extracted 54 chunks from 'Symbolic principal plane with Duality Centers Method'
Extracted 116 chunks from 'Sparse Principal Component Analysis with missing observations'
Extracted 155 chunks from 'Principal Component Analysis for Functional Data on Riemannian Manifolds and Spheres'
Extracted 121 chunks from 'Derivative Principal Component Analysis for Representing the Time Dynamics of Longitudinal and Functional Data'
Extracted 45 chunks from 'Principal Basis Analysis in Sparse Representation'
Extracted 170 chunks from 'Visualisation of financial time series by linear principal component analysis and nonlinear principal component analysis'
Extracted 85 chunks from 'A unified framework of principal component analysis and factor analysis'

Total Chunks Extracted: 955

Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
results:  {'matches': [{'id': '9e03465a-a873-44b3-93a4-9c2e3464d1eb',
              'metadata': {'text': 'arXiv:2405.15487v1  [nucl-th]  24 May '
                                   '2024\n'
                                   'Principal components of nuclear mass '
                                   'models\n'
                                   'X. H. Wu ( 吴鑫辉)1, 2,∗ and P. W. Zhao ( '
                                   '赵鹏巍)2, †\n'
                                   '1Department of Physics, Fuzhou University, '
                                   'Fuzhou 350108, Fujian, China\n'
                                   '2State Key Laboratory of Nuclear Physics '
                                   'and Technology,\n'
                                   'School of Physics, Peking University, '
                                   'Beijing 100871, China\n'
                                   'The principal component analysis approach '
                                   'is employed to ex tract the principal '
                                   'components'},
              'score': 0.362353265,
              'values': []},
             {'id': 'e3a5d8b4-5359-4e71-9c62-73e8ff2410f7',
              'metadata': {'text': 'arXiv:2405.15487v1  [nucl-th]  24 May '
                                   '2024\n'
                                   'Principal components of nuclear mass '
                                   'models\n'
                                   'X. H. Wu ( 吴鑫辉)1, 2,∗ and P. W. Zhao ( '
                                   '赵鹏巍)2, †\n'
                                   '1Department of Physics, Fuzhou University, '
                                   'Fuzhou 350108, Fujian, China\n'
                                   '2State Key Laboratory of Nuclear Physics '
                                   'and Technology,\n'
                                   'School of Physics, Peking University, '
                                   'Beijing 100871, China\n'
                                   'The principal component analysis approach '
                                   'is employed to ex tract the principal '
                                   'components'},
              'score': 0.362335861,
              'values': []},
             {'id': '8c3d8450-46ee-43e9-b2fa-4f88f0182cb5',
              'metadata': {'text': 'centroids. The standard k-means method [2] '
                                   'attempts to produce such a c lustering of '
                                   'the\n'
                                   'data points that the sum of squared '
                                   'centroid distances ∑ n\n'
                                   'i=1 ||pi − zi||2 is minimized.\n'
                                   'The main diﬃculty of this method is that '
                                   'it requires the data p oints to be the '
                                   'elements\n'
                                   'of a Euclidean space, since we need to '
                                   'average the data points somehow. A '
                                   'generalization\n'
                                   'of k-means called relational k-means has '
                                   'been proposed [3] to address this issue. '
                                   'This'},
              'score': 0.269638211,
              'values': []}],
 'namespace': 'default',
 'usage': {'read_units': 6}}

Comparison 1:
Original Retrieval Result:
arXiv:2405.15487v1  [nucl-th]  24 May 2024
Principal components of nuclear mass models
X. H. Wu ( 吴鑫辉)1, 2,∗ and P. W. Zhao ( 赵鹏巍)2, †
1Department of Physics, Fuzhou University, Fuzhou 350108, Fujian, China
2State Key Laboratory of Nuclear Physics and Technology,
School of Physics, Peking University, Beijing 100871, China
The principal component analysis approach is employed to ex tract the principal components

Similar Retrieval Result:
arXiv:2405.15487v1  [nucl-th]  24 May 2024
Principal components of nuclear mass models
X. H. Wu ( 吴鑫辉)1, 2,∗ and P. W. Zhao ( 赵鹏巍)2, †
1Department of Physics, Fuzhou University, Fuzhou 350108, Fujian, China
2State Key Laboratory of Nuclear Physics and Technology,
School of Physics, Peking University, Beijing 100871, China
The principal component analysis approach is employed to ex tract the principal components

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
arbitrary distance matrix, as opposed to the traditional k- means method, where the
clustered objects need to be identiﬁed with vectors.
1 Introduction
Suppose that we are given a set of data pointsp1, ...pn ∈ Rd and a number of clusters
N. W e would like assort these data points “optimally” into N clusters. For each point pi
let zi denote the center of gravity of the cluster pi is assigned to. W e call the zi vectors

Similar Retrieval Result:
arXiv:2405.15487v1  [nucl-th]  24 May 2024
Principal components of nuclear mass models
X. H. Wu ( 吴鑫辉)1, 2,∗ and P. W. Zhao ( 赵鹏巍)2, †
1Department of Physics, Fuzhou University, Fuzhou 350108, Fujian, China
2State Key Laboratory of Nuclear Physics and Technology,
School of Physics, Peking University, Beijing 100871, China
The principal component analysis approach is employed to ex tract the principal components

Retrieval Cosine Similarity: 0.1746

Comparison 3:
Original Retrieval Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Similar Retrieval Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Retrieval Cosine Similarity: 1.0000

Query Cosine Similarity (Original vs. Similar Question): 0.9398
============================================================
Processing row 3:
Original Question:
Search for the question: What is the Support Vector Machine (SVM) and how does it work?
Similar Question:
Search for the question: How does a Support Vector Machine (SVM) operate?
============================================================

Running Search with filters: {'query': 'Support Vector Machine operation', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: Support Vector Machine operation
----------------------------------------------------------------------------------------------------

Title: Linear Classification of data with Support Vector Machines and Generalized Support Vector Machines
- Author(s): Xiaomin Qi, Sergei Silvestrov, Talat Nazir
- Category: cs.LG
- Abstract (first 200 chars): In this paper, we study the support vector machine and introduced the notion
of generalized support vector machine for classification of data. We show that
the problem of generalized support vector ma...
- Submitted Date: 2016-05-31 09:54:46+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Vector Quantization for Machine Vision
- Author(s): Vincenzo Liguori
- Category: cs.CV
- Abstract (first 200 chars): This paper shows how to reduce the computational cost for a variety of common
machine vision tasks by operating directly in the compressed domain,
particularly in the context of hardware acceleration....
- Submitted Date: 2016-03-30 04:40:31+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Comprehensive Review On Twin Support Vector Machines
- Author(s): M. Tanveer, T. Rajani, R. Rastogi, Y. H. Shao, M. A. Ganaie
- Category: cs.LG
- Abstract (first 200 chars): Twin support vector machine (TWSVM) and twin support vector regression (TSVR)
are newly emerging efficient machine learning techniques which offer promising
solutions for classification and regression...
- Submitted Date: 2021-05-01 19:48:45+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Entanglement Classification via Witness Operators generated by Support Vector Machine
- Author(s): Claudio Sanavio, Edoardo Tignone, Elisa Ercolessi
- Category: quant-ph
- Abstract (first 200 chars): Although entanglement is a basic resource for reaching quantum advantange in
many computation and information protocols, we lack a universal recipe for
detecting it, with analytical results obtained f...
- Submitted Date: 2023-01-17 08:49:13+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A complexity analysis of statistical learning algorithms
- Author(s): Mark A. Kon
- Category: stat.ML
- Abstract (first 200 chars): We apply information-based complexity analysis to support vector machine
(SVM) algorithms, with the goal of a comprehensive continuous algorithmic
analysis of such algorithms. This involves complexity...
- Submitted Date: 2012-12-19 03:06:13+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Support Vector Based Anomaly Detection in Federated Learning
- Author(s): Massimo Frasson, Dario Malchiodi
- Category: cs.LG
- Abstract (first 200 chars): Anomaly detection plays a crucial role in various domains, from cybersecurity
to industrial systems. However, traditional centralized approaches often
encounter challenges related to data privacy. In ...
- Submitted Date: 2024-07-04 13:32:17+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅

In [ ]:
similarity_comparison_df

,original_question,similar_question,comparison_index,orig_retrieved_result,sim_retrieved_result,retrieval_cosine_similarity,query_cosine_similarity
0,Search for the question: Explain the concept o...,Search for the question: What is the fundament...,1,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,1.000000,0.939805
1,Search for the question: Explain the concept o...,Search for the question: What is the fundament...,2,"arbitrary distance matrix, as opposed to the t...",arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,0.174556,0.939805
2,Search for the question: Explain the concept o...,Search for the question: What is the fundament...,3,centroids. The standard k-means method [2] att...,centroids. The standard k-means method [2] att...,1.000000,0.939805
3,Search for the question: What is the Support V...,Search for the question: How does a Support Ve...,1,which can learn a suitable piece-wise linear l...,2010 Mathematics Subject Classiﬁcation:62H30.\...,0.486710,0.945307
4,Search for the question: What is the Support V...,Search for the question: How does a Support Ve...,2,"1995)(Vapnik, 2013)(Gunn, 1998) are still very...",which can learn a suitable piece-wise linear l...,0.551234,0.945307
5,Search for the question: What is the Support V...,Search for the question: How does a Support Ve...,3,Learning a powerful SVM using piece-wise linea...,"1995)(Vapnik, 2013)(Gunn, 1998) are still very...",0.635804,0.945307
6,Search for the question: Describe the backprop...,Search for the question: How does the backprop...,1,ZORB: A Derivative-Free Backpropagation\nAlgor...,ZORB: A Derivative-Free Backpropagation\nAlgor...,1.000000,0.876163
7,Search for the question: Describe the backprop...,Search for the question: How does the backprop...,2,training a neural network with gradient descen...,ZORB: A Derivative-Free Backpropagation\nAlgor...,0.706921,0.876163
8,Search for the question: Describe the backprop...,Search for the question: How does the backprop...,3,with 11 layers on MNIST and observed that ZORB...,training a neural network with gradient descen...,0.662124,0.876163
9,Search for the question: What are Convolutiona...,Search for the question: Can you describe what...,1,convolution) as far as we know.\n1 Introductio...,convolution) as far as we know.\n1 Introductio...,1.000000,0.890054
10,Search for the question: What are Convolutiona...,Search for the question: Can you describe what...,2,ILP-M C ONV: O PTIMIZE CONVOLUTION ALGORITHM F...,convolution) as far as we know.\n1 Introductio...,0.531007,0.890054
11,Search for the question: What are Convolutiona...,Search for the question: Can you describe what...,3,network inference algorithm on mobile GPUs is ...,ILP-M C ONV: O PTIMIZE CONVOLUTION ALGORITHM F...,0.767981,0.890054
12,Search for the question: Explain the concept o...,Search for the question: What is Reinforcement...,1,ZORB: A Derivative-Free Backpropagation\nAlgor...,Tracking as Online Decision-Making:\nLearning ...,0.224207,0.856715
13,Search for the question: Explain the concept o...,Search for the question: What is Reinforcement...,2,Learning a powerful SVM using piece-wise linea...,"long reinforcement learning are provided, alon...",0.146029,0.856715
14,Search for the question: Explain the concept o...,Search for the question: What is Reinforcement...,3,training a neural network with gradient descen...,Some Insights into Lifelong Reinforcement Lear...,0.273573,0.856715
15,Search for the question: What is the differenc...,Search for the question: How do Type I and Typ...,1,"1995)(Vapnik, 2013)(Gunn, 1998) are still very...",3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,0.042517,0.971657
16,Search for the question: What is the differenc...,Search for the question: How do Type I and Typ...,2,which can learn a suitable piece-wise linear l...,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,-0.049772,0.971657
17,Search for the question: What is the differenc...,Search for the question: How do Type I and Typ...,3,Learning a powerful SVM using piece-wise linea...,"IDEAOPERATIONAL,WESHOWHOWTOOBTAINAGNOSTICHyPOT...",0.052304,0.971657
18,Search for the question: How does the Gradient...,Search for the question: Can you detail the pr...,1,ZORB: A Derivative-Free Backpropagation\nAlgor...,GRADIENT DESCENT IN SOME SIMPLE SETTINGS\nY. C...,0.501942,0.863471
19,Search for the question: How does the Gradient...,Search for the question: Can you detail the pr...,2,and its update is more accurate. We combine th...,ZORB: A Derivative-Free Backpropagation\nAlgor...,0.528222,0.863471
20,Search for the question: How does the Gradient...,Search for the question: Can you detail the pr...,3,Scaling transition from momentum stochastic gr...,ZORB: A Derivative-Free Backpropagation\nAlgor...,0.440478,0.863471
21,Search for the question: What is Overfitting i...,Search for the question: How can overfitting b...,1,vide recommendations for possible solutions. W...,vide recommendations for possible solutions. W...,1.000000,0.935217
22,Search for the question: What is Overfitting i...,Search for the question: How can overfitting b...,2,Machine Learning Students Overﬁt to Overﬁtting...,Machine Learning Students Overﬁt to Overﬁtting...,1.000000,0.935217
23,Search for the question: What is Overfitting i...,Search for the question: How can overfitting b...,3,tation. This has driven the demand of machine ...,RL agents and find that they could overfit in ...,0.499927,0.935217
24,Search for the question: what is concept of Tr...,Search for the question: Can you explain the c...,1,Such an ability to acquire and reuse knowledge...,Such an ability to acquire and reuse knowledge...,1.000000,0.902878
25,Search for the question: what is concept of Tr...,Search for the question: Can you explain the c...,2,Transferability in Deep Learning: A Survey\nTr...,Transferability in Deep Learning: A Survey\nTr...,1.000000,0.902878
26,Search for the question: what is concept of Tr...,Search for the question: Can you explain the c...,3,tation. This has driven the demand of machine ...,Mingsheng Long † mingsheng@tsinghua.edu.cn\nSc...,0.538633,0.902878

In [ ]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - text-embedding-3-small",          # 在ClearML中显示的标题
    series="Embedding Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=similarity_comparison_df             # 直接传入 DataFrame
)

# Evaluate text-embedding-3-large

In [ ]:
from dotenv import load_dotenv
import os 
load_dotenv()
os.environ["EMBEDDING_MODEL"] = 'text-embedding-3-large'
os.environ["USE_OPENAI_EMBEDDINGS"] = 'True'

model_name = os.getenv("EMBEDDING_MODEL", 'text-embedding-3-large')
print("Using embedding model:", model_name) 

model_name = os.getenv("USE_OPENAI_EMBEDDINGS", 'True')
print("whether use openai embedding model:", model_name)
# sometimes you need to restart the kernel in order for this env settings to work

Using embedding model: text-embedding-3-large
whether use openai embedding model: True

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer, util

# 加载预训练的 SentenceTransformer 模型
model = SentenceTransformer('all-MiniLM-L6-v2')

# 假设 df 已经加载，包含以下列：
# 'question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 例如：df = pd.read_csv("your_dataset.csv")

all_scores = []         # 用于存储每个 question 的 3 个 cosine similarity 分数
comparison_results = [] # 用于存储所有比较结果，稍后转换成 DataFrame

# 遍历 DataFrame 中的每一行（假设有10个问题，即 10 行，共 3*10 比较）
for idx, row in df.iterrows():
    print("=" * 60)
    print(f"Question {idx+1}:")
    print(row['question'])
    print("=" * 60)
    
    # 用户查询即当前行的 question
    user_query = row['question']
    
    # 参考文本列表，顺序与检索结果顺序对应
    ref_paragraphs = [
        row['reference paragraph 1'],
        row['reference paragraph 2'],
        row['reference paragraph 3']
    ]
    
    # 调用检索函数获取结果，返回的 ans 是一个列表，每个元素为 { "text": ..., "source": ... }
    try:
        ans = retrieve_ans(user_query, index_obj)
    except KeyError as e:
        print(f"KeyError encountered for question {idx+1}: {e}. Skipping this question.\n")
        continue

    if ans == 0 or len(ans) < 3:
        print(f"WARNING: No sufficient results for question {idx+1}: {user_query}\n")
        continue
    
    scores = []
    # 针对前三个结果进行比较：第一条检索结果对应第一个参考段落，依此类推
    for i in range(3):
        result_text = ans[i]['text']
        ref_text = ref_paragraphs[i]
        
        print(f"\n--- Comparison {i+1} ---")
        print("Retrieved Result:")
        print(result_text)
        print("\nReference Paragraph:")
        print(ref_text)
        
        # 分别生成两段文本的 embedding
        emb_result = model.encode(result_text, convert_to_tensor=True)
        emb_ref = model.encode(ref_text, convert_to_tensor=True)
        
        # 计算 cosine similarity（util.cos_sim 返回的是 tensor）
        score = util.cos_sim(emb_result, emb_ref)
        similarity = score.item()
        scores.append(similarity)
        
        print(f"\nCosine Similarity for Comparison {i+1}: {similarity:.4f}")
        
        # 记录当前比较结果到 comparison_results 列表中
        comparison_results.append({
            "question": user_query,
            "comparison_index": i+1,
            "retrieved_result": result_text,
            "reference_paragraph": ref_text,
            "cosine_similarity": similarity
        })
    
    print("\nSimilarity scores for Question {}: {}".format(idx+1, scores))
    all_scores.append(scores)

# 将所有分数转换为 numpy 数组，shape 为 (num_questions, 3)
score_matrix = np.array(all_scores)
print("\n" + "=" * 60)
print("Cosine Similarity Matrix:")
print(score_matrix)

# 计算所有相似度的均值
mean_score = score_matrix.mean()
print("\nMean Cosine Similarity: {:.4f}".format(mean_score))

# 将所有比较结果转换为 DataFrame 并打印输出
comparison_df = pd.DataFrame(comparison_results)
print("\nComparison Results DataFrame:")
print(comparison_df)

============================================================
Question 1:
Search for the question: Describe the K-means clustering algorithm.
============================================================

Running Search with filters: {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: K-means clustering algorithm
----------------------------------------------------------------------------------------------------

Title: An implementation of the relational k-means algorithm
- Author(s): Balázs Szalkai
- Category: cs.LG
- Abstract (first 200 chars): A C# implementation of a generalized k-means variant called relational
k-means is described here. Relational k-means is a generalization of the
well-known k-means clustering method which works for non...
- Submitted Date: 2013-04-25 12:59:31+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Popcorn: Accelerating Kernel K-means on GPUs through Sparse Linear Algebra
- Author(s): Julian Bellavita, Thomas Pasquali, Laura Del Rio Martin, Flavio Vella, Giulia Guidi
- Category: cs.DC
- Abstract (first 200 chars): K-means is a popular clustering algorithm with significant applications in
numerous scientific and engineering areas. One drawback of K-means is its
inability to identify non-linearly separable cluste...
- Submitted Date: 2025-01-09 21:43:16+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Performance Evaluation of Incremental K-means Clustering Algorithm
- Author(s): Sanjay Chakraborty, N. K. Nagwani
- Category: cs.IR
- Abstract (first 200 chars): The incremental K-means clustering algorithm has already been proposed and
analysed in paper [Chakraborty and Nagwani, 2011]. It is a very innovative
approach which is applicable in periodically incre...
- Submitted Date: 2014-06-18 14:34:18+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Elkan's k-Means for Graphs
- Author(s): Brijnesh J. Jain, Klaus Obermayer
- Category: cs.AI
- Abstract (first 200 chars): This paper extends k-means algorithms from the Euclidean domain to the domain
of graphs. To recompute the centroids, we apply subgradient methods for solving
the optimization-based formulation of the ...
- Submitted Date: 2009-12-23 10:30:11+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Extraction of Protein Sequence Motif Information using PSO K-Means
- Author(s): R. Gowri, R. Rathipriya
- Category: cs.CV
- Abstract (first 200 chars): The main objective of the paper is to find the motif information.The
functionalities of the proteins are ideally found from their motif information
which is extracted using various techniques like clu...
- Submitted Date: 2015-04-09 09:53:44+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Wide Gaps and Clustering Axioms
- Author(s): Mieczysław A. Kłopotek
- Category: cs.LG
- Abstract (first 200 chars): The widely applied k-means algorithm produces clusterings that violate our
expectations with respect to high/low similarity/density and is in conflict
with Kleinberg's axiomatic system for distance ba...
- Submitted Date: 2023-08-07 10:43:48+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Breathing K-Means: Superior K-Means Solutions through Dynamic K-Values
- Author(s): Bernd Fritzke
- Category: cs.LG
- Abstract (first 200 chars): We introduce the breathing k-means algorithm, which on average significantly
improves solutions obtained by the widely-known greedy k-means++ algorithm, the
default method for k-means clustering in th...
- Submitted Date: 2020-06-28 17:49:37+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Improving the K-means algorithm using improved downhill simplex search
- Author(s): Ehsan Saboori, Shafigh Parsazad, Anoosheh Sadeghi
- Category: cs.LG
- Abstract (first 200 chars): The k-means algorithm is one of the well-known and most popular clustering
algorithms. K-means seeks an optimal partition of the data by minimizing the
sum of squared error with an iterative optimizat...
- Submitted Date: 2012-09-05 03:02:26+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A new Initial Centroid finding Method based on Dissimilarity Tree for K-means Algorithm
- Author(s): Abhishek Kumar, Suresh Chandra Gupta
- Category: cs.LG
- Abstract (first 200 chars): Cluster analysis is one of the primary data analysis technique in data mining
and K-means is one of the commonly used partitioning clustering algorithm. In
K-means algorithm, resulting set of clusters...
- Submitted Date: 2015-06-19 11:43:14+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Ball k-means
- Author(s): Shuyin Xia, Daowan Peng, Deyu Meng, Changqing Zhang, Guoyin Wang, Zizhong Chen, Wei Wei
- Category: cs.LG
- Abstract (first 200 chars): This paper presents a novel accelerated exact k-means algorithm called the
Ball k-means algorithm, which uses a ball to describe a cluster, focusing on
reducing the point-centroid distance computation...
- Submitted Date: 2020-05-02 10:39:26+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Final Papers Matching All Filters: 10

Extracted 39 chunks from 'An implementation of the relational k-means algorithm'
Extracted 156 chunks from 'Popcorn: Accelerating Kernel K-means on GPUs through Sparse Linear Algebra'
Extracted 42 chunks from 'Performance Evaluation of Incremental K-means Clustering Algorithm'
Extracted 104 chunks from 'Elkan's k-Means for Graphs'
Extracted 48 chunks from 'Extraction of Protein Sequence Motif Information using PSO K-Means'
Extracted 106 chunks from 'Wide Gaps and Clustering Axioms'
Extracted 180 chunks from 'Breathing K-Means: Superior K-Means Solutions through Dynamic K-Values'
Extracted 33 chunks from 'Improving the K-means algorithm using improved downhill simplex search'
Extracted 40 chunks from 'A new Initial Centroid finding Method based on Dissimilarity Tree for K-means Algorithm'
Extracted 28 chunks from 'Ball k-means'

Total Chunks Extracted: 776

Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
results:  {'matches': [{'id': '8c3d8450-46ee-43e9-b2fa-4f88f0182cb5',
              'metadata': {'text': 'centroids. The standard k-means method [2] '
                                   'attempts to produce such a c lustering of '
                                   'the\n'
                                   'data points that the sum of squared '
                                   'centroid distances ∑ n\n'
                                   'i=1 ||pi − zi||2 is minimized.\n'
                                   'The main diﬃculty of this method is that '
                                   'it requires the data p oints to be the '
                                   'elements\n'
                                   'of a Euclidean space, since we need to '
                                   'average the data points somehow. A '
                                   'generalization\n'
                                   'of k-means called relational k-means has '
                                   'been proposed [3] to address this issue. '
                                   'This'},
              'score': 0.535030663,
              'values': []},
             {'id': '5b6f940b-29ef-41fd-968a-2d27ab108f49',
              'metadata': {'text': 'centroids. The standard k-means method [2] '
                                   'attempts to produce such a c lustering of '
                                   'the\n'
                                   'data points that the sum of squared '
                                   'centroid distances ∑ n\n'
                                   'i=1 ||pi − zi||2 is minimized.\n'
                                   'The main diﬃculty of this method is that '
                                   'it requires the data p oints to be the '
                                   'elements\n'
                                   'of a Euclidean space, since we need to '
                                   'average the data points somehow. A '
                                   'generalization\n'
                                   'of k-means called relational k-means has '
                                   'been proposed [3] to address this issue. '
                                   'This'},
              'score': 0.535025477,
              'values': []},
             {'id': '155525d8-c1ba-4541-86af-9b91c539f12b',
              'metadata': {'text': 'arbitrary distance matrix, as opposed to '
                                   'the traditional k- means method, where '
                                   'the\n'
                                   'clustered objects need to be identiﬁed '
                                   'with vectors.\n'
                                   '1 Introduction\n'
                                   'Suppose that we are given a set of data '
                                   'pointsp1, ...pn ∈ Rd and a number of '
                                   'clusters\n'
                                   'N. W e would like assort these data points '
                                   '“optimally” into N clusters. For each '
                                   'point pi\n'
                                   'let zi denote the center of gravity of the '
                                   'cluster pi is assigned to. W e call the zi '
                                   'vectors'},
              'score': 0.446549505,
              'values': []}],
 'namespace': 'default',
 'usage': {'read_units': 6}}

--- Comparison 1 ---
Retrieved Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Reference Paragraph:
Describes K-means clustering as partitioning data into clusters.

Cosine Similarity for Comparison 1: 0.6068

--- Comparison 2 ---
Retrieved Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Reference Paragraph:
Details on iterative refinement and minimizing within-cluster sum of squares.

Cosine Similarity for Comparison 2: 0.4995

--- Comparison 3 ---
Retrieved Result:
arbitrary distance matrix, as opposed to the traditional k- means method, where the
clustered objects need to be identiﬁed with vectors.
1 Introduction
Suppose that we are given a set of data pointsp1, ...pn ∈ Rd and a number of clusters
N. W e would like assort these data points “optimally” into N clusters. For each point pi
let zi denote the center of gravity of the cluster pi is assigned to. W e call the zi vectors

Reference Paragraph:
Mentions sensitivity to initial centroid placement and convergence to local minima.

Cosine Similarity for Comparison 3: 0.4472

Similarity scores for Question 1: [0.6067860722541809, 0.4994816482067108, 0.4472055435180664]
============================================================
Question 2:
Search for the question: Explain the concept of Principal Component Analysis (PCA).
============================================================

Running Search with filters: {'query': 'Principal Component Analysis', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: Principal Component Analysis
----------------------------------------------------------------------------------------------------

Title: Principal components of nuclear mass models
- Author(s): X. H. Wu, P. W. Zhao
- Category: nucl-th
- Abstract (first 200 chars): The principal component analysis approach is employed to extract the
principal components contained in nuclear mass models for the first time. The
effects coming from different nuclear mass models are...
- Submitted Date: 2024-05-24 12:08:46+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A note on the prediction error of principal component regression
- Author(s): Martin Wahl
- Category: math.ST
- Abstract (first 200 chars): We analyse the prediction error of principal component regression (PCR) and
prove non-asymptotic upper bounds for the corresponding squared risk. Under
mild assumptions, we show that PCR performs as w...
- Submitted Date: 2018-11-07 16:59:35+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Moment Analysis
- Author(s): Magnus Fontes, Rasmus Henningsson
- Category: math.ST
- Abstract (first 200 chars): Principal Moment Analysis is a method designed for dimension reduction,
analysis and visualization of high dimensional multivariate data. It
generalizes Principal Component Analysis and allows for sig...
- Submitted Date: 2020-03-09 15:48:29+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Symbolic principal plane with Duality Centers Method
- Author(s): Oldemar Rodriguez
- Category: stat.ME
- Abstract (first 200 chars): In \cite{ref11} and \cite{ref3}, the authors proposed the Centers and the
Vertices Methods to extend the well known principal components analysis method
to a particular kind of symbolic objects charac...
- Submitted Date: 2024-01-10 02:21:01+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Sparse Principal Component Analysis with missing observations
- Author(s): Karim Lounici
- Category: math.ST
- Abstract (first 200 chars): In this paper, we study the problem of sparse Principal Component Analysis
(PCA) in the high-dimensional setting with missing observations. Our goal is to
estimate the first principal component when w...
- Submitted Date: 2012-05-31 18:29:32+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Component Analysis for Functional Data on Riemannian Manifolds and Spheres
- Author(s): Xiongtao Dai, Hans-Georg Müller
- Category: math.ST
- Abstract (first 200 chars): Functional data analysis on nonlinear manifolds has drawn recent interest.
Sphere-valued functional data, which are encountered for example as movement
trajectories on the surface of the earth, are an...
- Submitted Date: 2017-05-17 16:02:17+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Derivative Principal Component Analysis for Representing the Time Dynamics of Longitudinal and Functional Data
- Author(s): Xiongtao Dai, Hans-Georg Müller, Wenwen Tao
- Category: stat.ME
- Abstract (first 200 chars): We propose a nonparametric method to explicitly model and represent the
derivatives of smooth underlying trajectories for longitudinal data. This
representation is based on a direct Karhunen--Lo\`eve ...
- Submitted Date: 2017-07-14 00:45:45+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Basis Analysis in Sparse Representation
- Author(s): Hong Sun, Cheng-Wei Sang, Chen-Guang Liu
- Category: cs.CV
- Abstract (first 200 chars): This article introduces a new signal analysis method, which can be
interpreted as a principal component analysis in sparse decomposition of the
signal. The method, called principal basis analysis, is ...
- Submitted Date: 2015-11-25 01:11:24+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Visualisation of financial time series by linear principal component analysis and nonlinear principal component analysis
- Author(s): Hao-Che Chen
- Category: q-fin.MF
- Abstract (first 200 chars): In this dissertation, the main goal is visualisation of financial time
series. We expect that visualisation of financial time series will be a useful
auxiliary for technical analysis. Firstly, we revi...
- Submitted Date: 2014-10-29 12:59:42+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅

In [ ]:
comparison_df

,question,comparison_index,retrieved_result,reference_paragraph,cosine_similarity
0,Search for the question: Describe the K-means ...,1,centroids. The standard k-means method [2] att...,Describes K-means clustering as partitioning d...,0.606786
1,Search for the question: Describe the K-means ...,2,centroids. The standard k-means method [2] att...,Details on iterative refinement and minimizing...,0.499482
2,Search for the question: Describe the K-means ...,3,"arbitrary distance matrix, as opposed to the t...",Mentions sensitivity to initial centroid place...,0.447206
3,Search for the question: Explain the concept o...,1,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,Defines PCA as a transformation technique.,0.264818
4,Search for the question: Explain the concept o...,2,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,Explains conversion of original variables to u...,0.373151
5,Search for the question: Explain the concept o...,3,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,Discusses PCA's application in dimensionality ...,0.366465
6,Search for the question: What is the Support V...,1,2010 Mathematics Subject Classiﬁcation:62H30.\...,Defines SVM and its objective to maximize the ...,0.467928
7,Search for the question: What is the Support V...,2,the notion of generalized support vector machi...,Explains the role of support vectors in formin...,0.404305
8,Search for the question: What is the Support V...,3,arXiv:1606.05664v1 [cs.LG] 31 May 2016\nLine...,Mentions use of kernel functions for non-linea...,0.434608
9,Search for the question: Describe the backprop...,1,ZORB: A Derivative-Free Backpropagation\nAlgor...,Introduces backpropagation as a method for err...,0.544076
10,Search for the question: Describe the backprop...,2,ZORB: A Derivative-Free Backpropagation\nAlgor...,Details the forward and backward passes and gr...,0.485703
11,Search for the question: Describe the backprop...,3,ZORB: A Derivative-Free Backpropagation\nAlgor...,Highlights iterative weight updates using grad...,0.400605
12,Search for the question: What are Convolutiona...,1,convolution) as far as we know.\n1 Introductio...,Describes CNN architecture for image recognition.,0.531200
13,Search for the question: What are Convolutiona...,2,convolution) as far as we know.\n1 Introductio...,Details convolutional and pooling layers for f...,0.519286
14,Search for the question: What are Convolutiona...,3,convolution) as far as we know.\n1 Introductio...,Presents state-of-the-art performance in compu...,0.415733
15,Search for the question: Explain the concept o...,1,"long reinforcement learning are provided, alon...","Outlines the RL framework including agents, st...",0.462525
16,Search for the question: Explain the concept o...,2,"long reinforcement learning are provided, alon...",Describes learning through trial and error int...,0.414901
17,Search for the question: Explain the concept o...,3,Some Insights into Lifelong Reinforcement Lear...,Mentions key algorithms like Q-learning and po...,0.446761
18,Search for the question: What is the differenc...,1,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,Defines Type I and Type II errors in hypothesi...,0.395687
19,Search for the question: What is the differenc...,2,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,Explains the implications of false positives a...,0.186265
20,Search for the question: What is the differenc...,3,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,Emphasizes the need for balancing sensitivity ...,0.151616
21,Search for the question: How does the Gradient...,1,GRADIENT DESCENT IN SOME SIMPLE SETTINGS\nY. C...,Introduces Gradient Descent for optimizing los...,0.701202
22,Search for the question: How does the Gradient...,2,"1. Introduction\nIn this note, we are interest...",Explains iterative updates and gradient comput...,0.440938
23,Search for the question: How does the Gradient...,3,ZORB: A Derivative-Free Backpropagation\nAlgor...,Highlights the importance of learning rate in ...,0.389941
24,Search for the question: What is Overfitting i...,1,vide recommendations for possible solutions. W...,Defines overfitting as the model capturing noi...,0.508399
25,Search for the question: What is Overfitting i...,2,vide recommendations for possible solutions. W...,Discusses regularization methods such as L1 an...,0.516669
26,Search for the question: What is Overfitting i...,3,Machine Learning Students Overﬁt to Overﬁtting...,Mentions cross-validation and dropout as strat...,0.500908
27,Search for the question: what is concept of Tr...,1,Such an ability to acquire and reuse knowledge...,Introduces Transfer Learning as leveraging pre...,0.564895
28,Search for the question: what is concept of Tr...,2,Such an ability to acquire and reuse knowledge...,Describes the process of fine-tuning and adapt...,0.267920
29,Search for the question: what is concept of Tr...,3,Transferability in Deep Learning: A Survey\nTr...,Highlights benefits in reducing training time ...,0.221061

In [ ]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - text-embedding-3-large",          # 在ClearML中显示的标题
    series="Retrieval Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=comparison_df             # 直接传入 DataFrame
)

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import util


# 假设 df 已经加载，并且包含以下列：
# 'question', 'similar_question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 此外，之前生成的 comparison_df 包含原始 question 对应的 retrieval 结果，列包括：
# "question", "comparison_index", "retrieved_result", "reference_paragraph", "cosine_similarity"

# 用于存储新比较结果的列表
new_comparison_results = []

# 遍历 df 的前 10 行（或需要的数量）
for idx, row in df.head(10).iterrows():
    orig_question = row['question']
    sim_question = row['similar_question']
    
    print("=" * 60)
    print(f"Processing row {idx+1}:")
    print("Original Question:")
    print(orig_question)
    print("Similar Question:")
    print(sim_question)
    print("=" * 60)
    
    # 获取原始问题的 retrieval 结果
    # 从之前的 comparison_df 筛选出原始问题对应的 retrieval 结果（保证顺序为 1-3）
    orig_results_df = comparison_df[comparison_df['question'] == orig_question]
    if orig_results_df.empty or len(orig_results_df) < 3:
        print(f"WARNING: No sufficient retrieval results for original question {idx+1}. Skipping row.")
        continue
    
    orig_results = orig_results_df.sort_values("comparison_index")["retrieved_result"].tolist()
    
    # 获取相似问题的 retrieval 结果（调用检索函数）
    ans_sim = retrieve_ans(sim_question, index_obj)
    if ans_sim == 0 or len(ans_sim) < 3:
        print(f"WARNING: No sufficient retrieval results for similar question {idx+1}. Skipping row.")
        continue
    sim_results = [item['text'] for item in ans_sim[:3]]
    
    # 计算原始问题与相似问题本身的 cosine similarity
    emb_orig_question = model.encode(orig_question, convert_to_tensor=True)
    emb_sim_question = model.encode(sim_question, convert_to_tensor=True)
    query_cos_sim = util.cos_sim(emb_orig_question, emb_sim_question).item()
    
    # 对于对应位置的 retrieval 结果进行比较：只比较对应的 1 对 1, 2 对 2, 3 对 3
    for i in range(3):
        orig_text = orig_results[i]
        sim_text = sim_results[i]
        
        emb_orig = model.encode(orig_text, convert_to_tensor=True)
        emb_sim = model.encode(sim_text, convert_to_tensor=True)
        retrieval_cos_sim = util.cos_sim(emb_orig, emb_sim).item()
        
        new_comparison_results.append({
            "original_question": orig_question,
            "similar_question": sim_question,
            "comparison_index": i+1,
            "orig_retrieved_result": orig_text,
            "sim_retrieved_result": sim_text,
            "retrieval_cosine_similarity": retrieval_cos_sim,
            "query_cosine_similarity": query_cos_sim
        })
        
        print(f"\nComparison {i+1}:")
        print("Original Retrieval Result:")
        print(orig_text)
        print("\nSimilar Retrieval Result:")
        print(sim_text)
        print(f"\nRetrieval Cosine Similarity: {retrieval_cos_sim:.4f}")
    
    print(f"\nQuery Cosine Similarity (Original vs. Similar Question): {query_cos_sim:.4f}")

# 将所有新比较结果转换为 DataFrame
similarity_comparison_df = pd.DataFrame(new_comparison_results)
print("\nNew Comparison Results DataFrame:")
print(similarity_comparison_df)

# 如需计算所有 retrieval_cosine_similarity 的平均值
mean_retrieval_cos_sim = similarity_comparison_df["retrieval_cosine_similarity"].mean()
mean_query_cos_sim = similarity_comparison_df["query_cosine_similarity"].mean()

print("\nMean Retrieval Cosine Similarity: {:.4f}".format(mean_retrieval_cos_sim))
print("Mean Query Cosine Similarity: {:.4f}".format(mean_query_cos_sim))

============================================================
Processing row 1:
Original Question:
Search for the question: Describe the K-means clustering algorithm.
Similar Question:
Search for the question: Can you explain how the K-means clustering algorithm works?
============================================================

Running Search with filters: {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: K-means clustering algorithm
----------------------------------------------------------------------------------------------------

Title: An implementation of the relational k-means algorithm
- Author(s): Balázs Szalkai
- Category: cs.LG
- Abstract (first 200 chars): A C# implementation of a generalized k-means variant called relational
k-means is described here. Relational k-means is a generalization of the
well-known k-means clustering method which works for non...
- Submitted Date: 2013-04-25 12:59:31+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Popcorn: Accelerating Kernel K-means on GPUs through Sparse Linear Algebra
- Author(s): Julian Bellavita, Thomas Pasquali, Laura Del Rio Martin, Flavio Vella, Giulia Guidi
- Category: cs.DC
- Abstract (first 200 chars): K-means is a popular clustering algorithm with significant applications in
numerous scientific and engineering areas. One drawback of K-means is its
inability to identify non-linearly separable cluste...
- Submitted Date: 2025-01-09 21:43:16+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Performance Evaluation of Incremental K-means Clustering Algorithm
- Author(s): Sanjay Chakraborty, N. K. Nagwani
- Category: cs.IR
- Abstract (first 200 chars): The incremental K-means clustering algorithm has already been proposed and
analysed in paper [Chakraborty and Nagwani, 2011]. It is a very innovative
approach which is applicable in periodically incre...
- Submitted Date: 2014-06-18 14:34:18+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Elkan's k-Means for Graphs
- Author(s): Brijnesh J. Jain, Klaus Obermayer
- Category: cs.AI
- Abstract (first 200 chars): This paper extends k-means algorithms from the Euclidean domain to the domain
of graphs. To recompute the centroids, we apply subgradient methods for solving
the optimization-based formulation of the ...
- Submitted Date: 2009-12-23 10:30:11+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Extraction of Protein Sequence Motif Information using PSO K-Means
- Author(s): R. Gowri, R. Rathipriya
- Category: cs.CV
- Abstract (first 200 chars): The main objective of the paper is to find the motif information.The
functionalities of the proteins are ideally found from their motif information
which is extracted using various techniques like clu...
- Submitted Date: 2015-04-09 09:53:44+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Wide Gaps and Clustering Axioms
- Author(s): Mieczysław A. Kłopotek
- Category: cs.LG
- Abstract (first 200 chars): The widely applied k-means algorithm produces clusterings that violate our
expectations with respect to high/low similarity/density and is in conflict
with Kleinberg's axiomatic system for distance ba...
- Submitted Date: 2023-08-07 10:43:48+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Breathing K-Means: Superior K-Means Solutions through Dynamic K-Values
- Author(s): Bernd Fritzke
- Category: cs.LG
- Abstract (first 200 chars): We introduce the breathing k-means algorithm, which on average significantly
improves solutions obtained by the widely-known greedy k-means++ algorithm, the
default method for k-means clustering in th...
- Submitted Date: 2020-06-28 17:49:37+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Improving the K-means algorithm using improved downhill simplex search
- Author(s): Ehsan Saboori, Shafigh Parsazad, Anoosheh Sadeghi
- Category: cs.LG
- Abstract (first 200 chars): The k-means algorithm is one of the well-known and most popular clustering
algorithms. K-means seeks an optimal partition of the data by minimizing the
sum of squared error with an iterative optimizat...
- Submitted Date: 2012-09-05 03:02:26+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A new Initial Centroid finding Method based on Dissimilarity Tree for K-means Algorithm
- Author(s): Abhishek Kumar, Suresh Chandra Gupta
- Category: cs.LG
- Abstract (first 200 chars): Cluster analysis is one of the primary data analysis technique in data mining
and K-means is one of the commonly used partitioning clustering algorithm. In
K-means algorithm, resulting set of clusters...
- Submitted Date: 2015-06-19 11:43:14+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Ball k-means
- Author(s): Shuyin Xia, Daowan Peng, Deyu Meng, Changqing Zhang, Guoyin Wang, Zizhong Chen, Wei Wei
- Category: cs.LG
- Abstract (first 200 chars): This paper presents a novel accelerated exact k-means algorithm called the
Ball k-means algorithm, which uses a ball to describe a cluster, focusing on
reducing the point-centroid distance computation...
- Submitted Date: 2020-05-02 10:39:26+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Final Papers Matching All Filters: 10

Extracted 39 chunks from 'An implementation of the relational k-means algorithm'
Extracted 156 chunks from 'Popcorn: Accelerating Kernel K-means on GPUs through Sparse Linear Algebra'
Extracted 42 chunks from 'Performance Evaluation of Incremental K-means Clustering Algorithm'
Extracted 104 chunks from 'Elkan's k-Means for Graphs'
Extracted 48 chunks from 'Extraction of Protein Sequence Motif Information using PSO K-Means'
Extracted 106 chunks from 'Wide Gaps and Clustering Axioms'
Extracted 180 chunks from 'Breathing K-Means: Superior K-Means Solutions through Dynamic K-Values'
Extracted 33 chunks from 'Improving the K-means algorithm using improved downhill simplex search'
Extracted 40 chunks from 'A new Initial Centroid finding Method based on Dissimilarity Tree for K-means Algorithm'
Extracted 28 chunks from 'Ball k-means'

Total Chunks Extracted: 776

Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
results:  {'matches': [{'id': '5b6f940b-29ef-41fd-968a-2d27ab108f49',
              'metadata': {'text': 'centroids. The standard k-means method [2] '
                                   'attempts to produce such a c lustering of '
                                   'the\n'
                                   'data points that the sum of squared '
                                   'centroid distances ∑ n\n'
                                   'i=1 ||pi − zi||2 is minimized.\n'
                                   'The main diﬃculty of this method is that '
                                   'it requires the data p oints to be the '
                                   'elements\n'
                                   'of a Euclidean space, since we need to '
                                   'average the data points somehow. A '
                                   'generalization\n'
                                   'of k-means called relational k-means has '
                                   'been proposed [3] to address this issue. '
                                   'This'},
              'score': 0.51703769,
              'values': []},
             {'id': '8c3d8450-46ee-43e9-b2fa-4f88f0182cb5',
              'metadata': {'text': 'centroids. The standard k-means method [2] '
                                   'attempts to produce such a c lustering of '
                                   'the\n'
                                   'data points that the sum of squared '
                                   'centroid distances ∑ n\n'
                                   'i=1 ||pi − zi||2 is minimized.\n'
                                   'The main diﬃculty of this method is that '
                                   'it requires the data p oints to be the '
                                   'elements\n'
                                   'of a Euclidean space, since we need to '
                                   'average the data points somehow. A '
                                   'generalization\n'
                                   'of k-means called relational k-means has '
                                   'been proposed [3] to address this issue. '
                                   'This'},
              'score': 0.516981661,
              'values': []},
             {'id': 'c48f7494-ef21-4328-83cf-288dd3525688',
              'metadata': {'text': 'centroids. The standard k-means method [2] '
                                   'attempts to produce such a c lustering of '
                                   'the\n'
                                   'data points that the sum of squared '
                                   'centroid distances ∑ n\n'
                                   'i=1 ||pi − zi||2 is minimized.\n'
                                   'The main diﬃculty of this method is that '
                                   'it requires the data p oints to be the '
                                   'elements\n'
                                   'of a Euclidean space, since we need to '
                                   'average the data points somehow. A '
                                   'generalization\n'
                                   'of k-means called relational k-means has '
                                   'been proposed [3] to address this issue. '
                                   'This'},
              'score': 0.516970396,
              'values': []}],
 'namespace': 'default',
 'usage': {'read_units': 6}}

Comparison 1:
Original Retrieval Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Similar Retrieval Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Similar Retrieval Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Retrieval Cosine Similarity: 1.0000

Comparison 3:
Original Retrieval Result:
arbitrary distance matrix, as opposed to the traditional k- means method, where the
clustered objects need to be identiﬁed with vectors.
1 Introduction
Suppose that we are given a set of data pointsp1, ...pn ∈ Rd and a number of clusters
N. W e would like assort these data points “optimally” into N clusters. For each point pi
let zi denote the center of gravity of the cluster pi is assigned to. W e call the zi vectors

Similar Retrieval Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Retrieval Cosine Similarity: 0.6742

Query Cosine Similarity (Original vs. Similar Question): 0.8765
============================================================
Processing row 2:
Original Question:
Search for the question: Explain the concept of Principal Component Analysis (PCA).
Similar Question:
Search for the question: What is the fundamental idea behind Principal Component Analysis (PCA)?
============================================================

Running Search with filters: {'query': 'Principal Component Analysis', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: Principal Component Analysis
----------------------------------------------------------------------------------------------------

Title: Principal components of nuclear mass models
- Author(s): X. H. Wu, P. W. Zhao
- Category: nucl-th
- Abstract (first 200 chars): The principal component analysis approach is employed to extract the
principal components contained in nuclear mass models for the first time. The
effects coming from different nuclear mass models are...
- Submitted Date: 2024-05-24 12:08:46+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A note on the prediction error of principal component regression
- Author(s): Martin Wahl
- Category: math.ST
- Abstract (first 200 chars): We analyse the prediction error of principal component regression (PCR) and
prove non-asymptotic upper bounds for the corresponding squared risk. Under
mild assumptions, we show that PCR performs as w...
- Submitted Date: 2018-11-07 16:59:35+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Moment Analysis
- Author(s): Magnus Fontes, Rasmus Henningsson
- Category: math.ST
- Abstract (first 200 chars): Principal Moment Analysis is a method designed for dimension reduction,
analysis and visualization of high dimensional multivariate data. It
generalizes Principal Component Analysis and allows for sig...
- Submitted Date: 2020-03-09 15:48:29+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Symbolic principal plane with Duality Centers Method
- Author(s): Oldemar Rodriguez
- Category: stat.ME
- Abstract (first 200 chars): In \cite{ref11} and \cite{ref3}, the authors proposed the Centers and the
Vertices Methods to extend the well known principal components analysis method
to a particular kind of symbolic objects charac...
- Submitted Date: 2024-01-10 02:21:01+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Sparse Principal Component Analysis with missing observations
- Author(s): Karim Lounici
- Category: math.ST
- Abstract (first 200 chars): In this paper, we study the problem of sparse Principal Component Analysis
(PCA) in the high-dimensional setting with missing observations. Our goal is to
estimate the first principal component when w...
- Submitted Date: 2012-05-31 18:29:32+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Component Analysis for Functional Data on Riemannian Manifolds and Spheres
- Author(s): Xiongtao Dai, Hans-Georg Müller
- Category: math.ST
- Abstract (first 200 chars): Functional data analysis on nonlinear manifolds has drawn recent interest.
Sphere-valued functional data, which are encountered for example as movement
trajectories on the surface of the earth, are an...
- Submitted Date: 2017-05-17 16:02:17+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Derivative Principal Component Analysis for Representing the Time Dynamics of Longitudinal and Functional Data
- Author(s): Xiongtao Dai, Hans-Georg Müller, Wenwen Tao
- Category: stat.ME
- Abstract (first 200 chars): We propose a nonparametric method to explicitly model and represent the
derivatives of smooth underlying trajectories for longitudinal data. This
representation is based on a direct Karhunen--Lo\`eve ...
- Submitted Date: 2017-07-14 00:45:45+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅

In [ ]:
similarity_comparison_df

,original_question,similar_question,comparison_index,orig_retrieved_result,sim_retrieved_result,retrieval_cosine_similarity,query_cosine_similarity
0,Search for the question: Describe the K-means ...,Search for the question: Can you explain how t...,1,centroids. The standard k-means method [2] att...,centroids. The standard k-means method [2] att...,1.000000,0.876549
1,Search for the question: Describe the K-means ...,Search for the question: Can you explain how t...,2,centroids. The standard k-means method [2] att...,centroids. The standard k-means method [2] att...,1.000000,0.876549
2,Search for the question: Describe the K-means ...,Search for the question: Can you explain how t...,3,"arbitrary distance matrix, as opposed to the t...",centroids. The standard k-means method [2] att...,0.674180,0.876549
3,Search for the question: Explain the concept o...,Search for the question: What is the fundament...,1,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,1.000000,0.939805
4,Search for the question: Explain the concept o...,Search for the question: What is the fundament...,2,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,1.000000,0.939805
5,Search for the question: Explain the concept o...,Search for the question: What is the fundament...,3,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,1.000000,0.939805
6,Search for the question: What is the Support V...,Search for the question: How does a Support Ve...,1,2010 Mathematics Subject Classiﬁcation:62H30.\...,2010 Mathematics Subject Classiﬁcation:62H30.\...,1.000000,0.945307
7,Search for the question: What is the Support V...,Search for the question: How does a Support Ve...,2,the notion of generalized support vector machi...,which can learn a suitable piece-wise linear l...,0.393871,0.945307
8,Search for the question: What is the Support V...,Search for the question: How does a Support Ve...,3,arXiv:1606.05664v1 [cs.LG] 31 May 2016\nLine...,which can learn a suitable piece-wise linear l...,0.577839,0.945307
9,Search for the question: Describe the backprop...,Search for the question: How does the backprop...,1,ZORB: A Derivative-Free Backpropagation\nAlgor...,ZORB: A Derivative-Free Backpropagation\nAlgor...,1.000000,0.876163
10,Search for the question: Describe the backprop...,Search for the question: How does the backprop...,2,ZORB: A Derivative-Free Backpropagation\nAlgor...,ZORB: A Derivative-Free Backpropagation\nAlgor...,1.000000,0.876163
11,Search for the question: Describe the backprop...,Search for the question: How does the backprop...,3,ZORB: A Derivative-Free Backpropagation\nAlgor...,ZORB: A Derivative-Free Backpropagation\nAlgor...,1.000000,0.876163
12,Search for the question: What are Convolutiona...,Search for the question: Can you describe what...,1,convolution) as far as we know.\n1 Introductio...,convolution) as far as we know.\n1 Introductio...,1.000000,0.890054
13,Search for the question: What are Convolutiona...,Search for the question: Can you describe what...,2,convolution) as far as we know.\n1 Introductio...,convolution) as far as we know.\n1 Introductio...,1.000000,0.890054
14,Search for the question: What are Convolutiona...,Search for the question: Can you describe what...,3,convolution) as far as we know.\n1 Introductio...,convolution) as far as we know.\n1 Introductio...,1.000000,0.890054
15,Search for the question: Explain the concept o...,Search for the question: What is Reinforcement...,1,"long reinforcement learning are provided, alon...",Tracking as Online Decision-Making:\nLearning ...,0.471733,0.856715
16,Search for the question: Explain the concept o...,Search for the question: What is Reinforcement...,2,"long reinforcement learning are provided, alon...",Tracking as Online Decision-Making:\nLearning ...,0.471733,0.856715
17,Search for the question: Explain the concept o...,Search for the question: What is Reinforcement...,3,Some Insights into Lifelong Reinforcement Lear...,"long reinforcement learning are provided, alon...",0.722845,0.856715
18,Search for the question: What is the differenc...,Search for the question: How do Type I and Typ...,1,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,1.000000,0.971657
19,Search for the question: What is the differenc...,Search for the question: How do Type I and Typ...,2,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,1.000000,0.971657
20,Search for the question: What is the differenc...,Search for the question: How do Type I and Typ...,3,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,1.000000,0.971657
21,Search for the question: How does the Gradient...,Search for the question: Can you detail the pr...,1,GRADIENT DESCENT IN SOME SIMPLE SETTINGS\nY. C...,GRADIENT DESCENT IN SOME SIMPLE SETTINGS\nY. C...,1.000000,0.863471
22,Search for the question: How does the Gradient...,Search for the question: Can you detail the pr...,2,"1. Introduction\nIn this note, we are interest...",GRADIENT DESCENT IN SOME SIMPLE SETTINGS\nY. C...,0.691213,0.863471
23,Search for the question: How does the Gradient...,Search for the question: Can you detail the pr...,3,ZORB: A Derivative-Free Backpropagation\nAlgor...,ZORB: A Derivative-Free Backpropagation\nAlgor...,1.000000,0.863471
24,Search for the question: What is Overfitting i...,Search for the question: How can overfitting b...,1,vide recommendations for possible solutions. W...,vide recommendations for possible solutions. W...,1.000000,0.935217
25,Search for the question: What is Overfitting i...,Search for the question: How can overfitting b...,2,vide recommendations for possible solutions. W...,vide recommendations for possible solutions. W...,1.000000,0.935217
26,Search for the question: What is Overfitting i...,Search for the question: How can overfitting b...,3,Machine Learning Students Overﬁt to Overﬁtting...,Machine Learning Students Overﬁt to Overﬁtting...,1.000000,0.935217
27,Search for the question: what is concept of Tr...,Search for the question: Can you explain the c...,1,Such an ability to acquire and reuse knowledge...,Such an ability to acquire and reuse knowledge...,1.000000,0.902878
28,Search for the question: what is concept of Tr...,Search for the question: Can you explain the c...,2,Such an ability to acquire and reuse knowledge...,Such an ability to acquire and reuse knowledge...,1.000000,0.902878
29,Search for the question: what is concept of Tr...,Search for the question: Can you explain the c...,3,Transferability in Deep Learning: A Survey\nTr...,Transferability in Deep Learning: A Survey\nTr...,1.000000,0.902878

In [ ]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - text-embedding-3-large",          # 在ClearML中显示的标题
    series="Embedding Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=similarity_comparison_df             # 直接传入 DataFrame
)

# Evaluate all-MiniLM-L6-v2

In [ ]:
from dotenv import load_dotenv
import os 
load_dotenv() 
os.environ["USE_OPENAI_EMBEDDINGS"] = 'False'

model_name = os.getenv("USE_OPENAI_EMBEDDINGS", 'False')
print("whether use openai embedding model:", model_name)
# sometimes you need to restart the kernel in order for this env settings to work

whether use openai embedding model: False

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import util
 

# 假设 df 已经加载，包含以下列：
# 'question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 例如：df = pd.read_csv("your_dataset.csv")

all_scores = []         # 用于存储每个 question 的 3 个 cosine similarity 分数
comparison_results = [] # 用于存储所有比较结果，稍后转换成 DataFrame

# 遍历 DataFrame 中的每一行（假设有10个问题，即 10 行，共 3*10 比较）
for idx, row in df.iterrows():
    print("=" * 60)
    print(f"Question {idx+1}:")
    print(row['question'])
    print("=" * 60)
    
    # 用户查询即当前行的 question
    user_query = row['question']
    
    # 参考文本列表，顺序与检索结果顺序对应
    ref_paragraphs = [
        row['reference paragraph 1'],
        row['reference paragraph 2'],
        row['reference paragraph 3']
    ]
    
    # 调用检索函数获取结果，返回的 ans 是一个列表，每个元素为 { "text": ..., "source": ... }
    try:
        ans = retrieve_ans(user_query, index_obj)
    except KeyError as e:
        print(f"KeyError encountered for question {idx+1}: {e}. Skipping this question.\n")
        continue

    if ans == 0 or len(ans) < 3:
        print(f"WARNING: No sufficient results for question {idx+1}: {user_query}\n")
        continue
    
    scores = []
    # 针对前三个结果进行比较：第一条检索结果对应第一个参考段落，依此类推
    for i in range(3):
        result_text = ans[i]['text']
        ref_text = ref_paragraphs[i]
        
        print(f"\n--- Comparison {i+1} ---")
        print("Retrieved Result:")
        print(result_text)
        print("\nReference Paragraph:")
        print(ref_text)
        
        # 分别生成两段文本的 embedding
        emb_result = model.encode(result_text, convert_to_tensor=True)
        emb_ref = model.encode(ref_text, convert_to_tensor=True)
        
        # 计算 cosine similarity（util.cos_sim 返回的是 tensor）
        score = util.cos_sim(emb_result, emb_ref)
        similarity = score.item()
        scores.append(similarity)
        
        print(f"\nCosine Similarity for Comparison {i+1}: {similarity:.4f}")
        
        # 记录当前比较结果到 comparison_results 列表中
        comparison_results.append({
            "question": user_query,
            "comparison_index": i+1,
            "retrieved_result": result_text,
            "reference_paragraph": ref_text,
            "cosine_similarity": similarity
        })
    
    print("\nSimilarity scores for Question {}: {}".format(idx+1, scores))
    all_scores.append(scores)

# 将所有分数转换为 numpy 数组，shape 为 (num_questions, 3)
score_matrix = np.array(all_scores)
print("\n" + "=" * 60)
print("Cosine Similarity Matrix:")
print(score_matrix)

# 计算所有相似度的均值
mean_score = score_matrix.mean()
print("\nMean Cosine Similarity: {:.4f}".format(mean_score))

# 将所有比较结果转换为 DataFrame 并打印输出
comparison_df = pd.DataFrame(comparison_results)
print("\nComparison Results DataFrame:")
print(comparison_df)

============================================================
Question 1:
Search for the question: Describe the K-means clustering algorithm.
============================================================

Running Search with filters: {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: K-means clustering algorithm
----------------------------------------------------------------------------------------------------

Title: An implementation of the relational k-means algorithm
- Author(s): Balázs Szalkai
- Category: cs.LG
- Abstract (first 200 chars): A C# implementation of a generalized k-means variant called relational
k-means is described here. Relational k-means is a generalization of the
well-known k-means clustering method which works for non...
- Submitted Date: 2013-04-25 12:59:31+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Popcorn: Accelerating Kernel K-means on GPUs through Sparse Linear Algebra
- Author(s): Julian Bellavita, Thomas Pasquali, Laura Del Rio Martin, Flavio Vella, Giulia Guidi
- Category: cs.DC
- Abstract (first 200 chars): K-means is a popular clustering algorithm with significant applications in
numerous scientific and engineering areas. One drawback of K-means is its
inability to identify non-linearly separable cluste...
- Submitted Date: 2025-01-09 21:43:16+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Performance Evaluation of Incremental K-means Clustering Algorithm
- Author(s): Sanjay Chakraborty, N. K. Nagwani
- Category: cs.IR
- Abstract (first 200 chars): The incremental K-means clustering algorithm has already been proposed and
analysed in paper [Chakraborty and Nagwani, 2011]. It is a very innovative
approach which is applicable in periodically incre...
- Submitted Date: 2014-06-18 14:34:18+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Elkan's k-Means for Graphs
- Author(s): Brijnesh J. Jain, Klaus Obermayer
- Category: cs.AI
- Abstract (first 200 chars): This paper extends k-means algorithms from the Euclidean domain to the domain
of graphs. To recompute the centroids, we apply subgradient methods for solving
the optimization-based formulation of the ...
- Submitted Date: 2009-12-23 10:30:11+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Extraction of Protein Sequence Motif Information using PSO K-Means
- Author(s): R. Gowri, R. Rathipriya
- Category: cs.CV
- Abstract (first 200 chars): The main objective of the paper is to find the motif information.The
functionalities of the proteins are ideally found from their motif information
which is extracted using various techniques like clu...
- Submitted Date: 2015-04-09 09:53:44+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Wide Gaps and Clustering Axioms
- Author(s): Mieczysław A. Kłopotek
- Category: cs.LG
- Abstract (first 200 chars): The widely applied k-means algorithm produces clusterings that violate our
expectations with respect to high/low similarity/density and is in conflict
with Kleinberg's axiomatic system for distance ba...
- Submitted Date: 2023-08-07 10:43:48+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Breathing K-Means: Superior K-Means Solutions through Dynamic K-Values
- Author(s): Bernd Fritzke
- Category: cs.LG
- Abstract (first 200 chars): We introduce the breathing k-means algorithm, which on average significantly
improves solutions obtained by the widely-known greedy k-means++ algorithm, the
default method for k-means clustering in th...
- Submitted Date: 2020-06-28 17:49:37+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Improving the K-means algorithm using improved downhill simplex search
- Author(s): Ehsan Saboori, Shafigh Parsazad, Anoosheh Sadeghi
- Category: cs.LG
- Abstract (first 200 chars): The k-means algorithm is one of the well-known and most popular clustering
algorithms. K-means seeks an optimal partition of the data by minimizing the
sum of squared error with an iterative optimizat...
- Submitted Date: 2012-09-05 03:02:26+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A new Initial Centroid finding Method based on Dissimilarity Tree for K-means Algorithm
- Author(s): Abhishek Kumar, Suresh Chandra Gupta
- Category: cs.LG
- Abstract (first 200 chars): Cluster analysis is one of the primary data analysis technique in data mining
and K-means is one of the commonly used partitioning clustering algorithm. In
K-means algorithm, resulting set of clusters...
- Submitted Date: 2015-06-19 11:43:14+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Ball k-means
- Author(s): Shuyin Xia, Daowan Peng, Deyu Meng, Changqing Zhang, Guoyin Wang, Zizhong Chen, Wei Wei
- Category: cs.LG
- Abstract (first 200 chars): This paper presents a novel accelerated exact k-means algorithm called the
Ball k-means algorithm, which uses a ball to describe a cluster, focusing on
reducing the point-centroid distance computation...
- Submitted Date: 2020-05-02 10:39:26+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Final Papers Matching All Filters: 10

Extracted 39 chunks from 'An implementation of the relational k-means algorithm'
Extracted 156 chunks from 'Popcorn: Accelerating Kernel K-means on GPUs through Sparse Linear Algebra'
Extracted 42 chunks from 'Performance Evaluation of Incremental K-means Clustering Algorithm'
Extracted 104 chunks from 'Elkan's k-Means for Graphs'
Extracted 48 chunks from 'Extraction of Protein Sequence Motif Information using PSO K-Means'
Extracted 106 chunks from 'Wide Gaps and Clustering Axioms'
Extracted 180 chunks from 'Breathing K-Means: Superior K-Means Solutions through Dynamic K-Values'
Extracted 33 chunks from 'Improving the K-means algorithm using improved downhill simplex search'
Extracted 40 chunks from 'A new Initial Centroid finding Method based on Dissimilarity Tree for K-means Algorithm'
Extracted 28 chunks from 'Ball k-means'

Total Chunks Extracted: 776

Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 1 embeddings into index '8xkvyxtznx', namespace 'default'.
results:  {'matches': [{'id': '5b6f940b-29ef-41fd-968a-2d27ab108f49',
              'metadata': {'text': 'centroids. The standard k-means method [2] '
                                   'attempts to produce such a c lustering of '
                                   'the\n'
                                   'data points that the sum of squared '
                                   'centroid distances ∑ n\n'
                                   'i=1 ||pi − zi||2 is minimized.\n'
                                   'The main diﬃculty of this method is that '
                                   'it requires the data p oints to be the '
                                   'elements\n'
                                   'of a Euclidean space, since we need to '
                                   'average the data points somehow. A '
                                   'generalization\n'
                                   'of k-means called relational k-means has '
                                   'been proposed [3] to address this issue. '
                                   'This'},
              'score': 0.535104811,
              'values': []},
             {'id': 'baa45c80-2aa1-4c36-9e97-86546c2febbf',
              'metadata': {'text': 'centroids. The standard k-means method [2] '
                                   'attempts to produce such a c lustering of '
                                   'the\n'
                                   'data points that the sum of squared '
                                   'centroid distances ∑ n\n'
                                   'i=1 ||pi − zi||2 is minimized.\n'
                                   'The main diﬃculty of this method is that '
                                   'it requires the data p oints to be the '
                                   'elements\n'
                                   'of a Euclidean space, since we need to '
                                   'average the data points somehow. A '
                                   'generalization\n'
                                   'of k-means called relational k-means has '
                                   'been proposed [3] to address this issue. '
                                   'This'},
              'score': 0.535041451,
              'values': []},
             {'id': 'c48f7494-ef21-4328-83cf-288dd3525688',
              'metadata': {'text': 'centroids. The standard k-means method [2] '
                                   'attempts to produce such a c lustering of '
                                   'the\n'
                                   'data points that the sum of squared '
                                   'centroid distances ∑ n\n'
                                   'i=1 ||pi − zi||2 is minimized.\n'
                                   'The main diﬃculty of this method is that '
                                   'it requires the data p oints to be the '
                                   'elements\n'
                                   'of a Euclidean space, since we need to '
                                   'average the data points somehow. A '
                                   'generalization\n'
                                   'of k-means called relational k-means has '
                                   'been proposed [3] to address this issue. '
                                   'This'},
              'score': 0.535030663,
              'values': []}],
 'namespace': 'default',
 'usage': {'read_units': 6}}

--- Comparison 1 ---
Retrieved Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Reference Paragraph:
Describes K-means clustering as partitioning data into clusters.

Cosine Similarity for Comparison 1: 0.6068

--- Comparison 2 ---
Retrieved Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Reference Paragraph:
Details on iterative refinement and minimizing within-cluster sum of squares.

Cosine Similarity for Comparison 2: 0.4995

--- Comparison 3 ---
Retrieved Result:
centroids. The standard k-means method [2] attempts to produce such a c lustering of the
data points that the sum of squared centroid distances ∑ n
i=1 ||pi − zi||2 is minimized.
The main diﬃculty of this method is that it requires the data p oints to be the elements
of a Euclidean space, since we need to average the data points somehow. A generalization
of k-means called relational k-means has been proposed [3] to address this issue. This

Reference Paragraph:
Mentions sensitivity to initial centroid placement and convergence to local minima.

Cosine Similarity for Comparison 3: 0.4279

Similarity scores for Question 1: [0.6067860722541809, 0.4994816482067108, 0.4278792142868042]
============================================================
Question 2:
Search for the question: Explain the concept of Principal Component Analysis (PCA).
============================================================

Running Search with filters: {'query': 'Principal Component Analysis', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '10', 'sort_by': 'relevance'}

Formatted Query: Principal Component Analysis
----------------------------------------------------------------------------------------------------

Title: Principal components of nuclear mass models
- Author(s): X. H. Wu, P. W. Zhao
- Category: nucl-th
- Abstract (first 200 chars): The principal component analysis approach is employed to extract the
principal components contained in nuclear mass models for the first time. The
effects coming from different nuclear mass models are...
- Submitted Date: 2024-05-24 12:08:46+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: A note on the prediction error of principal component regression
- Author(s): Martin Wahl
- Category: math.ST
- Abstract (first 200 chars): We analyse the prediction error of principal component regression (PCR) and
prove non-asymptotic upper bounds for the corresponding squared risk. Under
mild assumptions, we show that PCR performs as w...
- Submitted Date: 2018-11-07 16:59:35+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Moment Analysis
- Author(s): Magnus Fontes, Rasmus Henningsson
- Category: math.ST
- Abstract (first 200 chars): Principal Moment Analysis is a method designed for dimension reduction,
analysis and visualization of high dimensional multivariate data. It
generalizes Principal Component Analysis and allows for sig...
- Submitted Date: 2020-03-09 15:48:29+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Symbolic principal plane with Duality Centers Method
- Author(s): Oldemar Rodriguez
- Category: stat.ME
- Abstract (first 200 chars): In \cite{ref11} and \cite{ref3}, the authors proposed the Centers and the
Vertices Methods to extend the well known principal components analysis method
to a particular kind of symbolic objects charac...
- Submitted Date: 2024-01-10 02:21:01+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Sparse Principal Component Analysis with missing observations
- Author(s): Karim Lounici
- Category: math.ST
- Abstract (first 200 chars): In this paper, we study the problem of sparse Principal Component Analysis
(PCA) in the high-dimensional setting with missing observations. Our goal is to
estimate the first principal component when w...
- Submitted Date: 2012-05-31 18:29:32+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Component Analysis for Functional Data on Riemannian Manifolds and Spheres
- Author(s): Xiongtao Dai, Hans-Georg Müller
- Category: math.ST
- Abstract (first 200 chars): Functional data analysis on nonlinear manifolds has drawn recent interest.
Sphere-valued functional data, which are encountered for example as movement
trajectories on the surface of the earth, are an...
- Submitted Date: 2017-05-17 16:02:17+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Derivative Principal Component Analysis for Representing the Time Dynamics of Longitudinal and Functional Data
- Author(s): Xiongtao Dai, Hans-Georg Müller, Wenwen Tao
- Category: stat.ME
- Abstract (first 200 chars): We propose a nonparametric method to explicitly model and represent the
derivatives of smooth underlying trajectories for longitudinal data. This
representation is based on a direct Karhunen--Lo\`eve ...
- Submitted Date: 2017-07-14 00:45:45+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Principal Basis Analysis in Sparse Representation
- Author(s): Hong Sun, Cheng-Wei Sang, Chen-Guang Liu
- Category: cs.CV
- Abstract (first 200 chars): This article introduces a new signal analysis method, which can be
interpreted as a principal component analysis in sparse decomposition of the
signal. The method, called principal basis analysis, is ...
- Submitted Date: 2015-11-25 01:11:24+00:00

Filter Matches:
- Author Match: ✅
- Title Match: ✅
- Category Match: ✅
- Abstract Match: ✅
- Exclusion (NOT): ✅
- Date Range Match: ✅
----------------------------------------------------------------------------------------------------

Title: Visualisation of financial time series by linear principal component analysis and nonlinear principal component analysis
- Author(s): Hao-Che Chen
- Category: q-fin.MF
- Abstract (first 200 chars): In this dissertation, the main goal is visualisation of financial time
series. We expect that visualisation of financial time series will be a useful
auxiliary for technical analysis. Firstly, we revi...
- Submitted Date: 2014-10-29 12:59:42+00:00

Filter Matches:
- Author Match: ✅

In [ ]:
comparison_df

,question,comparison_index,retrieved_result,reference_paragraph,cosine_similarity
0,Search for the question: Describe the K-means ...,1,centroids. The standard k-means method [2] att...,Describes K-means clustering as partitioning d...,0.606786
1,Search for the question: Describe the K-means ...,2,centroids. The standard k-means method [2] att...,Details on iterative refinement and minimizing...,0.499482
2,Search for the question: Describe the K-means ...,3,centroids. The standard k-means method [2] att...,Mentions sensitivity to initial centroid place...,0.427879
3,Search for the question: Explain the concept o...,1,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,Defines PCA as a transformation technique.,0.264818
4,Search for the question: Explain the concept o...,2,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,Explains conversion of original variables to u...,0.373151
5,Search for the question: Explain the concept o...,3,arXiv:2405.15487v1 [nucl-th] 24 May 2024\nPr...,Discusses PCA's application in dimensionality ...,0.366465
6,Search for the question: What is the Support V...,1,2010 Mathematics Subject Classiﬁcation:62H30.\...,Defines SVM and its objective to maximize the ...,0.467928
7,Search for the question: What is the Support V...,2,the notion of generalized support vector machi...,Explains the role of support vectors in formin...,0.404305
8,Search for the question: What is the Support V...,3,arXiv:1606.05664v1 [cs.LG] 31 May 2016\nLine...,Mentions use of kernel functions for non-linea...,0.434608
9,Search for the question: Describe the backprop...,1,ZORB: A Derivative-Free Backpropagation\nAlgor...,Introduces backpropagation as a method for err...,0.544076
10,Search for the question: Describe the backprop...,2,ZORB: A Derivative-Free Backpropagation\nAlgor...,Details the forward and backward passes and gr...,0.485703
11,Search for the question: Describe the backprop...,3,ZORB: A Derivative-Free Backpropagation\nAlgor...,Highlights iterative weight updates using grad...,0.400605
12,Search for the question: What are Convolutiona...,1,convolution) as far as we know.\n1 Introductio...,Describes CNN architecture for image recognition.,0.531200
13,Search for the question: What are Convolutiona...,2,convolution) as far as we know.\n1 Introductio...,Details convolutional and pooling layers for f...,0.519286
14,Search for the question: What are Convolutiona...,3,convolution) as far as we know.\n1 Introductio...,Presents state-of-the-art performance in compu...,0.415733
15,Search for the question: Explain the concept o...,1,"long reinforcement learning are provided, alon...","Outlines the RL framework including agents, st...",0.462525
16,Search for the question: Explain the concept o...,2,"long reinforcement learning are provided, alon...",Describes learning through trial and error int...,0.414901
17,Search for the question: Explain the concept o...,3,"long reinforcement learning are provided, alon...",Mentions key algorithms like Q-learning and po...,0.464616
18,Search for the question: What is the differenc...,1,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,Defines Type I and Type II errors in hypothesi...,0.395687
19,Search for the question: What is the differenc...,2,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,Explains the implications of false positives a...,0.186265
20,Search for the question: What is the differenc...,3,3ãoPAULo (2017/03363-8)\nDESPITEITSCOMMONPRACT...,Emphasizes the need for balancing sensitivity ...,0.151616
21,Search for the question: How does the Gradient...,1,GRADIENT DESCENT IN SOME SIMPLE SETTINGS\nY. C...,Introduces Gradient Descent for optimizing los...,0.701202
22,Search for the question: How does the Gradient...,2,GRADIENT DESCENT IN SOME SIMPLE SETTINGS\nY. C...,Explains iterative updates and gradient comput...,0.575640
23,Search for the question: How does the Gradient...,3,"1. Introduction\nIn this note, we are interest...",Highlights the importance of learning rate in ...,0.383225
24,Search for the question: What is Overfitting i...,1,vide recommendations for possible solutions. W...,Defines overfitting as the model capturing noi...,0.508399
25,Search for the question: What is Overfitting i...,2,vide recommendations for possible solutions. W...,Discusses regularization methods such as L1 an...,0.516669
26,Search for the question: What is Overfitting i...,3,Machine Learning Students Overﬁt to Overﬁtting...,Mentions cross-validation and dropout as strat...,0.500908
27,Search for the question: what is concept of Tr...,1,Such an ability to acquire and reuse knowledge...,Introduces Transfer Learning as leveraging pre...,0.564895
28,Search for the question: what is concept of Tr...,2,Such an ability to acquire and reuse knowledge...,Describes the process of fine-tuning and adapt...,0.267920
29,Search for the question: what is concept of Tr...,3,Such an ability to acquire and reuse knowledge...,Highlights benefits in reducing training time ...,0.248680

In [ ]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - all-MiniLM-L6-v2",          # 在ClearML中显示的标题
    series="Retrieval Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=comparison_df             # 直接传入 DataFrame
)

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import util
 

# 假设 df 已经加载，并且包含以下列：
# 'question', 'similar_question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 此外，之前生成的 comparison_df 包含原始 question 对应的 retrieval 结果，列包括：
# "question", "comparison_index", "retrieved_result", "reference_paragraph", "cosine_similarity"

# 用于存储新比较结果的列表
new_comparison_results = []

# 遍历 df 的前 10 行（或需要的数量）
for idx, row in df.head(10).iterrows():
    orig_question = row['question']
    sim_question = row['similar_question']
    
    print("=" * 60)
    print(f"Processing row {idx+1}:")
    print("Original Question:")
    print(orig_question)
    print("Similar Question:")
    print(sim_question)
    print("=" * 60)
    
    # 获取原始问题的 retrieval 结果
    # 从之前的 comparison_df 筛选出原始问题对应的 retrieval 结果（保证顺序为 1-3）
    orig_results_df = comparison_df[comparison_df['question'] == orig_question]
    if orig_results_df.empty or len(orig_results_df) < 3:
        print(f"WARNING: No sufficient retrieval results for original question {idx+1}. Skipping row.")
        continue
    
    orig_results = orig_results_df.sort_values("comparison_index")["retrieved_result"].tolist()
    
    # 获取相似问题的 retrieval 结果（调用检索函数）
    ans_sim = retrieve_ans(sim_question, index_obj)
    if ans_sim == 0 or len(ans_sim) < 3:
        print(f"WARNING: No sufficient retrieval results for similar question {idx+1}. Skipping row.")
        continue
    sim_results = [item['text'] for item in ans_sim[:3]]
    
    # 计算原始问题与相似问题本身的 cosine similarity
    emb_orig_question = model.encode(orig_question, convert_to_tensor=True)
    emb_sim_question = model.encode(sim_question, convert_to_tensor=True)
    query_cos_sim = util.cos_sim(emb_orig_question, emb_sim_question).item()
    
    # 对于对应位置的 retrieval 结果进行比较：只比较对应的 1 对 1, 2 对 2, 3 对 3
    for i in range(3):
        orig_text = orig_results[i]
        sim_text = sim_results[i]
        
        emb_orig = model.encode(orig_text, convert_to_tensor=True)
        emb_sim = model.encode(sim_text, convert_to_tensor=True)
        retrieval_cos_sim = util.cos_sim(emb_orig, emb_sim).item()
        
        new_comparison_results.append({
            "original_question": orig_question,
            "similar_question": sim_question,
            "comparison_index": i+1,
            "orig_retrieved_result": orig_text,
            "sim_retrieved_result": sim_text,
            "retrieval_cosine_similarity": retrieval_cos_sim,
            "query_cosine_similarity": query_cos_sim
        })
        
        print(f"\nComparison {i+1}:")
        print("Original Retrieval Result:")
        print(orig_text)
        print("\nSimilar Retrieval Result:")
        print(sim_text)
        print(f"\nRetrieval Cosine Similarity: {retrieval_cos_sim:.4f}")
    
    print(f"\nQuery Cosine Similarity (Original vs. Similar Question): {query_cos_sim:.4f}")

# 将所有新比较结果转换为 DataFrame
similarity_comparison_df = pd.DataFrame(new_comparison_results)
print("\nNew Comparison Results DataFrame:")
print(similarity_comparison_df)

# 如需计算所有 retrieval_cosine_similarity 的平均值
mean_retrieval_cos_sim = similarity_comparison_df["retrieval_cosine_similarity"].mean()
mean_query_cos_sim = similarity_comparison_df["query_cosine_similarity"].mean()

print("\nMean Retrieval Cosine Similarity: {:.4f}".format(mean_retrieval_cos_sim))
print("Mean Query Cosine Similarity: {:.4f}".format(mean_query_cos_sim))

============================================================
Processing row 1:
Original Question:
Search for the question: Describe the K-means clustering algorithm.
Similar Question:
Search for the question: Can you explain how the K-means clustering algorithm works?
============================================================

KeyError: 'filters'

In [ ]:
similarity_comparison_df

In [ ]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - all-MiniLM-L6-v2",          # 在ClearML中显示的标题
    series="Embedding Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=similarity_comparison_df             # 直接传入 DataFrame
)

In [ ]:
# # TODO 
# evaluate humanlly, and use the metric

In [ ]:
path = "../evaluation_data/retrieval_comparison.csv"
comparison_df.to_csv(path)

NameError: name 'similarity_comparison_df' is not defined