In [1]:
!export PINECONE_API_KEY="pcsk_32aTpD_BYKjuc5114NyjcLQHZWofdGJLP9daLtmNKgX53rfkmeGiTYD8xsPUeypd18gyfe"
import os
from pinecone import Pinecone
os.environ["PINECONE_API_KEY"] = "pcsk_32aTpD_BYKjuc5114NyjcLQHZWofdGJLP9daLtmNKgX53rfkmeGiTYD8xsPUeypd18gyfe"
os.environ["OPENAI_API_KEY"] = "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"
print("Pinecone API Key:", os.getenv("PINECONE_API_KEY"))
pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY")) 
 

# %load_ext autoreload
# %autoreload 2
# %reload_ext autoreload 
from extract_filter import classify_and_extract
from data_utils import fetch_papers, verify_results, chunk_papers, format_query
from Database import create_index, save_embeddings_to_index, delete_index
from retrieval import answer_query, clear_memory, retrieve_chunks
from pinecone import Pinecone
import io
import contextlib
# Create the index once (assuming it should persist during the conversation)
import pandas as pd
from urllib.error import HTTPError
# 假设这些函数已经定义：create_index, pc.Index, classify_and_extract, fetch_papers,
# verify_results, chunk_papers, save_embeddings_to_index, answer_query, delete_index, clear_memory
import asyncio
# 创建索引
from ragas.dataset_schema import SingleTurnSample
from ragas.metrics import SemanticSimilarity
from ragas.embeddings import LangchainEmbeddingsWrapper
from clearml import Task, Logger
from time import sleep

'export' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
c:\Users\guoji\Group-3\gjwenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Pinecone API Key: pcsk_32aTpD_BYKjuc5114NyjcLQHZWofdGJLP9daLtmNKgX53rfkmeGiTYD8xsPUeypd18gyfe

In [2]:

from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

In [ ]:
%env CLEARML_WEB_HOST=https://app.5ccsagap.er.kcl.ac.uk/
%env CLEARML_API_HOST=https://api.5ccsagap.er.kcl.ac.uk
%env CLEARML_FILES_HOST=https://files.5ccsagap.er.kcl.ac.uk
# GAP_group3_embedding
%env CLEARML_API_ACCESS_KEY=F3JFSR84AVXM6OTRRRUBQ5QPVHMTWV
%env CLEARML_API_SECRET_KEY=tda_99OfnqWYSguFYS5wH6FtKuVBoryYeREQVh2MPdcXct0hGiNEnfxeIOBpXPH1fcE

from clearml import Task, Logger
task = Task.init(
    project_name="MyProject", 
    task_name="Embedding Comparison - inegrated env"
)

env: CLEARML_WEB_HOST=https://app.5ccsagap.er.kcl.ac.uk/
env: CLEARML_API_HOST=https://api.5ccsagap.er.kcl.ac.uk
env: CLEARML_FILES_HOST=https://files.5ccsagap.er.kcl.ac.uk
env: CLEARML_API_ACCESS_KEY=F3JFSR84AVXM6OTRRRUBQ5QPVHMTWV
env: CLEARML_API_SECRET_KEY=tda_99OfnqWYSguFYS5wH6FtKuVBoryYeREQVh2MPdcXct0hGiNEnfxeIOBpXPH1fcE
ClearML Task: overwriting (reusing) task id=c605651b36fd433e84a820f0651a19a7
ClearML results page: https://app.5ccsagap.er.kcl.ac.uk/projects/f6c6e15540994198a771be0667091232/experiments/c605651b36fd433e84a820f0651a19a7/output/log

In [4]:
from pinecone import Pinecone

indexes = pc.list_indexes()

# 逐个删除
for idx in indexes:
    index_name = idx["name"]
    pc.delete_index(index_name)
    print(f"Deleted index: {index_name}")

2025-04-04 01:49:08,036 - clearml.Repository Detection - WARNING - Can't get diff information for git repo in c:\Users\guoji\Group-3\gjwenv\Lib\site-packages
CLEARML-SERVER new package available: UPGRADE to v2.0.0 is recommended!
Release Notes:
### Breaking Changes

MongoDB major version was upgraded from v5.x to 6.x.
Please note that if your current ClearML Server version is smaller than v1.17 (where MongoDB v5.x was first used), you'll need to first upgrade to ClearML Server v1.17.
#### Upgrading to ClearML Server v1.17 from a previous version
- If using docker-compose,  use the following docker-compose files:
  * [docker-compose file](https://github.com/allegroai/clearml-server/blob/2976ce69cc91550a3614996e8a8d8cd799af2efd/upgrade/1_17_to_2_0/docker-compose.yml)
  * [docker-compose file foe Windows](https://github.com/allegroai/clearml-server/blob/2976ce69cc91550a3614996e8a8d8cd799af2efd/upgrade/1_17_to_2_0/docker-compose-win10.yml)

### New Features

- New look and feel: Full light/dark themes ([clearml #1297](https://github.com/allegroai/clearml/issues/1297))
- New UI task creation options
  - Support bash as well as python scripts
  - Support file upload
- New UI setting for configuring cloud storage credentials with which ClearML can clean up cloud storage artifacts on task deletion.
- Add UI scalar plots presentation of plots in sections grouped by metrics.
- Add UI Batch export plot embed codes for all metric plots in a single click.
- Add UI pipeline presentation of steps grouped into stages

### Bug Fixes
- Fix UI Model Endpoint's Number of Requests plot sometimes displays incorrect data
- Fix UI datasets page does not filter according to project when dataset is running
- Fix UI task scalar legend does not change colors when smoothing is enabled
- Fix queue list in UI Workers and Queues page does not alphabetically sort by queue display name
- Fix queue display name is not searchable in UI Task Creation modal's queue field

ClearML Monitor: GPU monitoring failed getting GPU reading, switching off GPU monitoring
ClearML Monitor: Could not detect iteration reporting, falling back to iterations as seconds-from-start
2025-04-04 07:12:56,153 - clearml.Task - WARNING - ### TASK STOPPED - USER ABORTED - STATUS CHANGED ###

Deleted index: 8xkvyxtznx

In [5]:
index_name = create_index()
index_obj = pc.Index(index_name)

Index '8xkvyxtznx' created successfully!

In [6]:
def retrieve_ans(user_input, index_obj): 
    classification = classify_and_extract(user_input)
    print(classification)
    
 
    filters = classification['filters']
    print("\nRunning Search with filters:", filters)

    # check if academic query is present
    if not format_query(filters):   
        question = classification['question']
        answer = answer_query(question, index_obj, top_k=100)
        print("Generated Answer:")
        print(answer)
        return

    # Step 1: Fetch papers
    papers = fetch_papers(filters)

    # Step 2: Verify & Filter papers
    verified_papers = verify_results(papers, filters)
    print(f"[integration] Found {len(verified_papers)} verified paper(s).")
    
    # Determine number of papers to return; default to 1 if not provided
    try:
        num_papers = int(filters.get("max_results", 1))
    except ValueError:
        num_papers = 1
    num_papers = min(num_papers, len(verified_papers))

    # Step 3: Chunk papers
    chunks = chunk_papers(verified_papers[:num_papers])  # Get full paper content as chunks
    texts = [chunk["text"] for chunk in chunks]  # Extract just the text

    if texts:
        # Save the full paper text chunks to the index
        batch_size = 200
        for i in range(0, len(texts), batch_size):
            text_batch = texts[i:i+batch_size] 
            save_embeddings_to_index(index_name=index_name, text=text_batch)
        sleep(1)

    ans = retrieve_chunks(user_input, index_obj)

    return ans

In [7]:
import pandas as pd
filename = "../evaluation_data/question_answer.csv"
df = pd.read_csv(filename, encoding='gbk')
print(df.head(0))

Empty DataFrame
Columns: [question, answer, paper, reference paragraph 1, reference paragraph 2, reference paragraph 3, similar_question]
Index: []

# Evaluate text-embedding-3-small

In [8]:
from dotenv import load_dotenv
import os 
load_dotenv()
os.environ["EMBEDDING_MODEL"] = "text-embedding-3-small"
os.environ["USE_OPENAI_EMBEDDINGS"] = 'True'

model_name = os.getenv("EMBEDDING_MODEL", "text-embedding-3-small")
print("Using embedding model:", model_name)

model_name = os.getenv("USE_OPENAI_EMBEDDINGS", 'True')
print("whether use openai embedding model:", model_name)
# sometimes you need to restart the kernel in order for this env settings to work

Using embedding model: text-embedding-3-small
whether use openai embedding model: True

In [9]:
import sys
sys.setrecursionlimit(10000)

In [10]:
import pandas as pd
import numpy as np
import builtins 
from Embedder import embed

# 加载预训练的 SentenceTransformer 模型
model = SentenceTransformer('all-MiniLM-L6-v2')

# 假设 df 已经加载，包含以下列：
# 'question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 例如：df = pd.read_csv("your_dataset.csv")

all_scores = []         # 用于存储每个 question 的 3 个 cosine similarity 分数
comparison_results = [] # 用于存储所有比较结果，稍后转换成 DataFrame

# 遍历 DataFrame 中的每一行（假设有10个问题，即 10 行，共 3*10 比较）
for idx, row in df.iterrows():
    print("=" * 60)
    print(f"Question {idx+1}:")
    print(row['question'])
    print("=" * 60)
    
    # 用户查询即当前行的 question
    user_query = row['question']
    
    # 参考文本列表，顺序与检索结果顺序对应
    ref_paragraphs = [
        row['reference paragraph 1'],
        row['reference paragraph 2'],
        row['reference paragraph 3']
    ]
    
    # 调用检索函数获取结果，返回的 ans 是一个列表，每个元素为 { "text": ..., "source": ... }
    try:
        ans = retrieve_ans(user_query, index_obj)
    except KeyError as e:
        print(f"KeyError encountered for question {idx+1}: {e}. Skipping this question.\n")
        continue

    if ans == 0 or len(ans) < 3:
        print(f"WARNING: No sufficient results for question {idx+1}: {user_query}\n")
        continue
    
    scores = []
    # 针对前三个结果进行比较：第一条检索结果对应第一个参考段落，依此类推
    for i in range(3):
        result_text = ans[i]['text']
        ref_text = ref_paragraphs[i]
        
        print(f"\n--- Comparison {i+1} ---")
        print("Retrieved Result:")
        print(result_text)
        print("\nReference Paragraph:")
        print(ref_text)
        
        # 分别生成两段文本的 embedding
        emb_result = model.encode(result_text, convert_to_tensor=True)
        emb_ref = model.encode(ref_text, convert_to_tensor=True)
        
        # 计算 cosine similarity（util.cos_sim 返回的是 tensor）
        score = util.cos_sim(emb_result, emb_ref)
        similarity = score.item()
        scores.append(similarity)
        
        print(f"\nCosine Similarity for Comparison {i+1}: {similarity:.4f}")
        
        # 记录当前比较结果到 comparison_results 列表中
        comparison_results.append({
            "question": user_query,
            "comparison_index": i+1,
            "retrieved_result": result_text,
            "reference_paragraph": ref_text,
            "cosine_similarity": similarity
        })
    
    print("\nSimilarity scores for Question {}: {}".format(idx+1, scores))
    all_scores.append(scores)

# 将所有分数转换为 numpy 数组，shape 为 (num_questions, 3)
score_matrix = np.array(all_scores)
print("\n" + "=" * 60)
print("Cosine Similarity Matrix:")
print(score_matrix)

# 计算所有相似度的均值
mean_score = score_matrix.mean()
print("\nMean Cosine Similarity: {:.4f}".format(mean_score))

# 将所有比较结果转换为 DataFrame 并打印输出
comparison_df = pd.DataFrame(comparison_results)
print("\nComparison Results DataFrame:")
print(comparison_df)

============================================================
Question 1:
Describe the K-means clustering algorithm.
============================================================
{'filters': {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Describe the K-means clustering algorithm.'}

Running Search with filters: {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 89 chunks from 'An implementation of the relational k-means algorithm'

Total Chunks Extracted: 89

Upserted 89 embeddings into index '8xkvyxtznx', namespace 'default'.
⚠️ No relevant documents found in Pinecone, trying again...
WARNING: No sufficient results for question 1: Describe the K-means clustering algorithm.

============================================================
Question 2:
Explain the Typiclust algorithm
============================================================
{'filters': {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Explain the Typiclust algorithm'}

Running Search with filters: {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 394 chunks from 'Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets'

Total Chunks Extracted: 394

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 194 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Reference Paragraph:
TypiClust is composed of three steps: (1) Representation learning: learn a semantically meaningful feature space using self-supervised learning. (2) Clustering: partition the data to ensure diversity. (3) Query: select the most typical examples (i.e., dense points) from the largest uncovered clusters

Cosine Similarity for Comparison 1: 0.6234

--- Comparison 2 ---
Retrieved Result:
by clustering the dataset and sampling the densest point
from each cluster (see Fig. 2).
In Section 4, we compare TypiClust to various AL strategies
in the low-budget regime. TypiClust consistently improves
generalization by a large margin, across different datasets

Reference Paragraph:
To capture the principle of max density, we define the Typicality of an example by the inverse of the average Euclidean distance to its K nearest neighbors. That is, typical points are those located in high-density areas of the feature space, and thus likely to be representative of the data distribution

Cosine Similarity for Comparison 2: 0.4165

--- Comparison 3 ---
Retrieved Result:
w.r.tLi−1), while selecting the most typical example in each
cluster favors the selection of representative examples.
As the steps above do not depend on any speciﬁc representa-
tion or clustering method, different variants of the TypiClust

Reference Paragraph:
Algorithm 1: Given an unlabeled pool and a budget B, first learn representations, then cluster the embedding space into B clusters. For each cluster, select the example with the highest typicality. This yields B diverse and representative samples for labeling?

Cosine Similarity for Comparison 3: 0.5071

Similarity scores for Question 2: [0.6233622431755066, 0.41654881834983826, 0.5071254968643188]
============================================================
Question 3:
What is the Support Vector Machine (SVM) and how does it work?
============================================================
{'filters': {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is the Support Vector Machine (SVM) and how does it work?'}

Running Search with filters: {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 132 chunks from 'Linear Classification of data with Support Vector Machines and Generalized Support Vector Machines'

Total Chunks Extracted: 132

Upserted 132 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Reference Paragraph:
The support-vector network implements the following idea: it maps the input vectors into some high dimensional feature space Z through some non-linear mapping chosen a priori. In this space a linear decision surface is constructed with special properties that ensure high generalization ability of the network.

Cosine Similarity for Comparison 1: 0.5048

--- Comparison 2 ---
Retrieved Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Reference Paragraph:
An optimal hyperplane is here defined as the linear decision function with maximal margin between the vectors of the two classes. It was observed that to construct such optimal hyperplanes one only has to take into account a small amount of the training data, the so called support vectors, which determine this margin.

Cosine Similarity for Comparison 2: 0.4866

--- Comparison 3 ---
Retrieved Result:
We call this problem as the Generalized Support Vector Machine (GSV M).
The GSVM is equivalent to
ﬁnd wi ∈ W : ⟨G′ (wi) , v − wi⟩ ≥ 0 for all v ∈ Rn with η > 0,
or more speciﬁcally
ﬁnd wi ∈ W : ⟨ηG′ (wi) , v − wi⟩ ≥ 0 for all v ∈ Rn. (2.5)

Reference Paragraph:
Using different dot-products K(u, v) one can construct different learning machines with arbitrary types of decision surfaces. The decision surface of these machines has a form ∑ ai K(xi, x), where xi is the image of a support vector and ai is its weight. The only difference is that instead of computing dot-products directly, kernels are used.

Cosine Similarity for Comparison 3: 0.4040

Similarity scores for Question 3: [0.5048344731330872, 0.4866325259208679, 0.40402403473854065]
============================================================
Question 4:
Describe the backpropagation algorithm used in neural networks.
============================================================
{'filters': {'query': 'backpropagation algorithm neural networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Describe the backpropagation algorithm used in neural networks.'}

Running Search with filters: {'query': 'backpropagation algorithm neural networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 192 chunks from 'ZORB: A Derivative-Free Backpropagation Algorithm for Neural Networks'

Total Chunks Extracted: 192

Upserted 192 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Reference Paragraph:
Introduces backpropagation as a method for error propagation.

Cosine Similarity for Comparison 1: 0.6312

--- Comparison 2 ---
Retrieved Result:
the same as the traditional BP algorithm. While backpropagating through activation functions, the
inverse of the activation function is applied, i.e., the feedback matrices must be deactivated. However,

Reference Paragraph:
The backward pass which propagates derivatives from the top layer back to the bottom one is more complicated. We start by computing ?E/?y for the output units, apply the chain rule to get ?E/?x, then compute how error changes with respect to weights: ?E/?w = ?E/?x × y. This process repeats layer by layer to update weights across the network.

Cosine Similarity for Comparison 2: 0.4391

--- Comparison 3 ---
Retrieved Result:
ZORB: A Derivative-Free Backpropagation
Algorithm for Neural Networks
Varun Ranganathan
Department of Computing Science
University of Alberta
Edmonton, AB T6G 2E8
vrangana@ualberta.ca
Alex Lewandowski
Department of Computing Science
University of Alberta
Edmonton, AB T6G 2E8
lewandowski@ualberta.ca

Reference Paragraph:
The simplest version of gradient descent is to change each weight by an amount proportional to the accumulated ?E/?w:

Cosine Similarity for Comparison 3: 0.3741

Similarity scores for Question 4: [0.631150484085083, 0.4390789568424225, 0.3741132616996765]
============================================================
Question 5:
What are Convolutional Neural Networks (CNN) and their main applications?
============================================================
{'filters': {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What are Convolutional Neural Networks (CNN) and their main applications?'}

Running Search with filters: {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'ILP-M Conv: Optimize Convolution Algorithm for Single-Image Convolution Neural Network Inference on Mobile GPUs'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
References
[1] Xu Han. Implement convolution in cnn. http://xuhan.me/2016/09/09/conv/, 2016.
[2] Fabian Tschopp, Julien NP Martel, Srinivas C Turaga, Matthew Cook, and Jan Funke. Efﬁcient convolutional

Reference Paragraph:
Convolutional neural networks (CNNs) constitute one such class of models. Their capacity can be controlled by varying their depth and breadth, and they also make strong and mostly correct assumptions about the nature of images (namely, stationarity of statistics and locality of pixel dependencies).

Cosine Similarity for Comparison 1: 0.5657

--- Comparison 2 ---
Retrieved Result:
CNNs mainly use small convolution ﬁlters.
3.1 Unrolling-based Convolution Algorithms
Unrolling-based convolution algorithm is the most popular GPU convolution algorithm for CNNs training. The key

Reference Paragraph:
We trained a large, deep convolutional neural network to classify the 1.2 million high-resolution images in the ImageNet LSVRC-2010 contest into the 1000 different classes.

Cosine Similarity for Comparison 2: 0.3626

--- Comparison 3 ---
Retrieved Result:
• Activation after the output layer: sigmoid
C.4.2 Convolution Neural Networks
Experiments described in section 3 of the main paper involve 3 CNNs. The architecture for each neural network
is as follows:
1. Conv1:
• Kernel size: 3 x 3
• Kernels in each convolution layer: 32

Reference Paragraph:
To learn about thousands of objects from millions of images, we need a model with a large learning capacity. [...] CNNs have much fewer connections and parameters and so they are easier to train, while their theoretically-best performance is likely to be only slightly worse.

Cosine Similarity for Comparison 3: 0.3345

Similarity scores for Question 5: [0.5657214522361755, 0.3625694215297699, 0.3345028758049011]
============================================================
Question 6:
Explain the concept of Reinforcement Learning.
============================================================
{'filters': {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Explain the concept of Reinforcement Learning.'}

Running Search with filters: {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'Some Insights into Lifelong Reinforcement Learning Systems'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Reference Paragraph:
Reinforcement learning problems involve learning what to do—how to map situations to actions—so as to maximize a numerical reward signal. The learner is not told which actions to take but must discover which yield the most reward by trying them. Actions may affect not only the immediate reward but also the next situation and all subsequent rewards

Cosine Similarity for Comparison 1: 0.5753

--- Comparison 2 ---
Retrieved Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Reference Paragraph:
The reinforcement learning problem is meant to be a straightforward framing of the problem of learning from interaction to achieve a goal. The agent interacts with the environment by taking actions and receiving rewards and new states, aiming to maximize cumulative reward over time

Cosine Similarity for Comparison 2: 0.7084

--- Comparison 3 ---
Retrieved Result:
Some Insights into Lifelong Reinforcement Learning Systems
Changjian Li1
Abstract
A lifelong reinforcement learning system is a
learning system that has the ability to learn
through trail-and-error interaction with the en-
vironment over its lifetime. In this paper, I give

Reference Paragraph:
A reward signal defines the goal in a reinforcement learning problem. At each time step, the environment sends to the agent a single number, a reward. The agent’s objective is to maximize the total reward it receives. The only way to influence the reward is by acting in the environment?

Cosine Similarity for Comparison 3: 0.4222

Similarity scores for Question 6: [0.5753160119056702, 0.7083839178085327, 0.4222358465194702]
============================================================
Question 7:
What is the difference between Type I and Type II errors in hypothesis testing?
============================================================
{'filters': {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is the difference between Type I and Type II errors in hypothesis testing?'}

Running Search with filters: {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 219 chunks from 'Agnostic tests can control the type I and type II errors simultaneously'

Total Chunks Extracted: 219

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 19 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE.ATyPE)))ERROROCCURSWHENEVERTHETESTREMAINSAGNOSTIC.AN
AGNOSTICTESTCANBEDESIGNEDTOCONTROLTHEERRORSOFTyPE)AND)).
DEﬁNITION ANAGNOSTICTEST, φ,HAS(α, β)-LEVELIFTHETEST’SPROBABILITIESOFCOMMITTINGERRORSOFTyPE)AND))ARE
CONTROLLEDBy,RESPECTIVELy,αANDβ.4HATIS,

Reference Paragraph:
These errors will be of two kinds: (I) we reject H? when it is true, (II) we accept H? when some alternative H? is true. The problem before us is to consider how these errors may be best controlled.

Cosine Similarity for Comparison 1: 0.5258

--- Comparison 2 ---
Retrieved Result:
Sample 2
Reject H 0
Sample 1
Confidence Interval
R 1
R 2
Confidence Interval
R 1
R 2
FIG52E 4 )LLUSTRATIONOFTHEAGNOSTICTESTBASEDON R1 ANDR2 (SECTION4.2)WHENH0 :θ=θ0.
AGNOSTICT-TEST CONSIDERSECTION2.2.&OREACHµ∗ ∈Ò,LETH0,µ∗ :µ = µ∗.4HE5-05AGNOSTICTESTISBASEDONTHE
REGIONESTIMATORS
R1(x)=
[

Reference Paragraph:
There is an essential difference in character between errors of type I and type II. If a true hypothesis is rejected, a mistake has been made whose consequence will generally be the same [...] all errors of type I may be described as equivalent. On the other hand, if H? is accepted when some alternative H? is true, the consequences depend on how much H? differs from H?.

Cosine Similarity for Comparison 2: 0.3299

--- Comparison 3 ---
Retrieved Result:
HyPOTHESIS.4HEREMAINDEROFTHISSECTIONExPLORESALTERNATIVEMETHODSOFCONTROLLINGTHETyPE))ERRORPROBABILITIES.
/NEALTERNATIVEWAyTOCONTROLTHETyPE))ERRORPROBABILITIESISTOREqUIRESOLELyTHAT SUPθ∈H′
1
Ðθ(φ=0)≤ β,WHERE
H′
1 ISASUBSETOF H1 WHICHISRELEVANTFORTHEPRACTITIONER./NEPROCEDURETOCHOOSE H′

Reference Paragraph:
We are influenced by the consequences which follow from a wrong decision; some errors will matter more than others. All errors of type I may be regarded as equivalent, while those of type II will be of differing quality according to the extent to which the alternative hypothesis which is true varies from that which is tested.

Cosine Similarity for Comparison 3: 0.4034

Similarity scores for Question 7: [0.525840163230896, 0.32990655303001404, 0.40337520837783813]
============================================================
Question 8:
How does the Gradient Descent optimization algorithm work?
============================================================

In [11]:
comparison_df

,question,comparison_index,retrieved_result,reference_paragraph,cosine_similarity
0,Explain the Typiclust algorithm,1,given in Alg. 1 (see more details in App. F.1)...,TypiClust is composed of three steps: (1) Repr...,0.623362
1,Explain the Typiclust algorithm,2,by clustering the dataset and sampling the den...,"To capture the principle of max density, we de...",0.416549
2,Explain the Typiclust algorithm,3,"w.r.tLi−1), while selecting the most typical e...",Algorithm 1: Given an unlabeled pool and a bud...,0.507125
3,What is the Support Vector Machine (SVM) and h...,1,2010 Mathematics Subject Classiﬁcation:62H30.\...,The support-vector network implements the foll...,0.504834
4,What is the Support Vector Machine (SVM) and h...,2,support vector machine. We also provide suﬃcie...,An optimal hyperplane is here defined as the l...,0.486633
5,What is the Support Vector Machine (SVM) and h...,3,We call this problem as the Generalized Suppor...,"Using different dot-products K(u, v) one can c...",0.404024
6,Describe the backpropagation algorithm used in...,1,traditional backpropagation with Gradient Desc...,Introduces backpropagation as a method for err...,0.631150
7,Describe the backpropagation algorithm used in...,2,the same as the traditional BP algorithm. Whil...,The backward pass which propagates derivatives...,0.439079
8,Describe the backpropagation algorithm used in...,3,ZORB: A Derivative-Free Backpropagation\nAlgor...,The simplest version of gradient descent is to...,0.374113
9,What are Convolutional Neural Networks (CNN) a...,1,References\n[1] Xu Han. Implement convolution ...,Convolutional neural networks (CNNs) constitut...,0.565721
10,What are Convolutional Neural Networks (CNN) a...,2,CNNs mainly use small convolution ﬁlters.\n3.1...,"We trained a large, deep convolutional neural ...",0.362569
11,What are Convolutional Neural Networks (CNN) a...,3,• Activation after the output layer: sigmoid\n...,To learn about thousands of objects from milli...,0.334503
12,Explain the concept of Reinforcement Learning.,1,reward space of the learning system. In other ...,Reinforcement learning problems involve learni...,0.575316
13,Explain the concept of Reinforcement Learning.,2,type of learning system. Some insights into li...,The reinforcement learning problem is meant to...,0.708384
14,Explain the concept of Reinforcement Learning.,3,Some Insights into Lifelong Reinforcement Lear...,A reward signal defines the goal in a reinforc...,0.422236
15,What is the difference between Type I and Type...,1,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,These errors will be of two kinds: (I) we reje...,0.525840
16,What is the difference between Type I and Type...,2,Sample 2\nReject H 0\nSample 1\nConfidence Int...,There is an essential difference in character ...,0.329907
17,What is the difference between Type I and Type...,3,HyPOTHESIS.4HEREMAINDEROFTHISSECTIONExPLORESAL...,We are influenced by the consequences which fo...,0.403375
18,How does the Gradient Descent optimization alg...,1,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,The simplest minimization procedure in such a ...,0.511702
19,How does the Gradient Descent optimization alg...,2,traditional backpropagation with Gradient Desc...,Gradient-Based Learning draws on the fact that...,0.576658
20,How does the Gradient Descent optimization alg...,3,Since SGD approximates the gradient using a si...,A popular minimization procedure is the stocha...,0.581772
21,What is Overfitting in machine learning and ho...,1,"overﬁtting, like zero training loss, and use n...",Overfitting is the use of models or procedures...,0.555013
22,What is Overfitting in machine learning and ho...,2,students to become proﬁcient machine learning ...,Overfitting is undesirable for a number of rea...,0.527125
23,What is Overfitting in machine learning and ho...,3,Teaching the concept of overﬁtting is not easy...,Some sort of out-of-sample prediction is essen...,0.452271
24,what is concept of Transfer Learning in deep l...,1,An eﬀective solution to this challenge is to e...,Definition 1 (Transfer Learning) Given a sourc...,0.508730
25,what is concept of Transfer Learning in deep l...,2,knowledge from previous learning experiences w...,"In 2005, the Broad Agency Announcement (BAA) 0...",0.547248
26,what is concept of Transfer Learning in deep l...,3,improving the transferability of deep models. ...,Transfer learning is motivated by the fact tha...,0.555300

In [12]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - text-embedding-3-small",          # 在ClearML中显示的标题
    series="Retrieval Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=comparison_df             # 直接传入 DataFrame
)

In [13]:
import pandas as pd
import numpy as np
from sentence_transformers import util
 

# 假设 df 已经加载，并且包含以下列：
# 'question', 'similar_question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 此外，之前生成的 comparison_df 包含原始 question 对应的 retrieval 结果，列包括：
# "question", "comparison_index", "retrieved_result", "reference_paragraph", "cosine_similarity"

# 用于存储新比较结果的列表
new_comparison_results = []

# 遍历 df 的前 10 行（或需要的数量）
for idx, row in df.head(10).iterrows():
    orig_question = row['question']
    sim_question = row['similar_question']
    
    print("=" * 60)
    print(f"Processing row {idx+1}:")
    print("Original Question:")
    print(orig_question)
    print("Similar Question:")
    print(sim_question)
    print("=" * 60)
    
    # 获取原始问题的 retrieval 结果
    # 从之前的 comparison_df 筛选出原始问题对应的 retrieval 结果（保证顺序为 1-3）
    orig_results_df = comparison_df[comparison_df['question'] == orig_question]
    if orig_results_df.empty or len(orig_results_df) < 3:
        print(f"WARNING: No sufficient retrieval results for original question {idx+1}. Skipping row.")
        continue
    
    orig_results = orig_results_df.sort_values("comparison_index")["retrieved_result"].tolist()
    
    # 获取相似问题的 retrieval 结果（调用检索函数）
    ans_sim = retrieve_ans(sim_question, index_obj)
    if ans_sim == 0 or len(ans_sim) < 3:
        print(f"WARNING: No sufficient retrieval results for similar question {idx+1}. Skipping row.")
        continue
    sim_results = [item['text'] for item in ans_sim[:3]]
    
    # 计算原始问题与相似问题本身的 cosine similarity
    emb_orig_question = model.encode(orig_question, convert_to_tensor=True)
    emb_sim_question = model.encode(sim_question, convert_to_tensor=True)
    query_cos_sim = util.cos_sim(emb_orig_question, emb_sim_question).item()
    
    # 对于对应位置的 retrieval 结果进行比较：只比较对应的 1 对 1, 2 对 2, 3 对 3
    for i in range(3):
        orig_text = orig_results[i]
        sim_text = sim_results[i]
        
        emb_orig = model.encode(orig_text, convert_to_tensor=True)
        emb_sim = model.encode(sim_text, convert_to_tensor=True)
        retrieval_cos_sim = util.cos_sim(emb_orig, emb_sim).item()
        
        new_comparison_results.append({
            "original_question": orig_question,
            "similar_question": sim_question,
            "comparison_index": i+1,
            "orig_retrieved_result": orig_text,
            "sim_retrieved_result": sim_text,
            "retrieval_cosine_similarity": retrieval_cos_sim,
            "query_cosine_similarity": query_cos_sim
        })
        
        print(f"\nComparison {i+1}:")
        print("Original Retrieval Result:")
        print(orig_text)
        print("\nSimilar Retrieval Result:")
        print(sim_text)
        print(f"\nRetrieval Cosine Similarity: {retrieval_cos_sim:.4f}")
    
    print(f"\nQuery Cosine Similarity (Original vs. Similar Question): {query_cos_sim:.4f}")

# 将所有新比较结果转换为 DataFrame
similarity_comparison_df = pd.DataFrame(new_comparison_results)
print("\nNew Comparison Results DataFrame:")
print(similarity_comparison_df)

# 如需计算所有 retrieval_cosine_similarity 的平均值
mean_retrieval_cos_sim = similarity_comparison_df["retrieval_cosine_similarity"].mean()
mean_query_cos_sim = similarity_comparison_df["query_cosine_similarity"].mean()

print("\nMean Retrieval Cosine Similarity: {:.4f}".format(mean_retrieval_cos_sim))
print("Mean Query Cosine Similarity: {:.4f}".format(mean_query_cos_sim))

============================================================
Processing row 1:
Original Question:
Describe the K-means clustering algorithm.
Similar Question:
Search for the question: Can you explain how the K-means clustering algorithm works?
============================================================
WARNING: No sufficient retrieval results for original question 1. Skipping row.
============================================================
Processing row 2:
Original Question:
Explain the Typiclust algorithm
Similar Question:
Search for the question: What is the fundamental idea behind Typiclust algorithm?
============================================================
{'filters': {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is the fundamental idea behind Typiclust algorithm?'}

Running Search with filters: {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 394 chunks from 'Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets'

Total Chunks Extracted: 394

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 194 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Similar Retrieval Result:
at https://github.com/avihu111/TypiClust.
1. Introduction
Recent years have witnessed the emergence of deep learning
as the dominant force in advancing machine learning and
its applications. But this development is data-hungry – to a
large extent, deep learning owes its success to the growing

Retrieval Cosine Similarity: 0.4949

Comparison 2:
Original Retrieval Result:
by clustering the dataset and sampling the densest point
from each cluster (see Fig. 2).
In Section 4, we compare TypiClust to various AL strategies
in the low-budget regime. TypiClust consistently improves
generalization by a large margin, across different datasets

Similar Retrieval Result:
at https://github.com/avihu111/TypiClust.
1. Introduction
Recent years have witnessed the emergence of deep learning
as the dominant force in advancing machine learning and
its applications. But this development is data-hungry – to a
large extent, deep learning owes its success to the growing

Retrieval Cosine Similarity: 0.4703

Comparison 3:
Original Retrieval Result:
w.r.tLi−1), while selecting the most typical example in each
cluster favors the selection of representative examples.
As the steps above do not depend on any speciﬁc representa-
tion or clustering method, different variants of the TypiClust

Similar Retrieval Result:
by clustering the dataset and sampling the densest point
from each cluster (see Fig. 2).
In Section 4, we compare TypiClust to various AL strategies
in the low-budget regime. TypiClust consistently improves
generalization by a large margin, across different datasets

Retrieval Cosine Similarity: 0.5686

Query Cosine Similarity (Original vs. Similar Question): 0.9289
============================================================
Processing row 3:
Original Question:
What is the Support Vector Machine (SVM) and how does it work?
Similar Question:
Search for the question: How does a Support Vector Machine (SVM) operate?
============================================================
{'filters': {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'How does a Support Vector Machine (SVM) operate?'}

Running Search with filters: {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 132 chunks from 'Linear Classification of data with Support Vector Machines and Generalized Support Vector Machines'

Total Chunks Extracted: 132

Upserted 132 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Similar Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Retrieval Cosine Similarity: 0.6475

Comparison 2:
Original Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Similar Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Retrieval Cosine Similarity: 1.0000

Comparison 3:
Original Retrieval Result:
We call this problem as the Generalized Support Vector Machine (GSV M).
The GSVM is equivalent to
ﬁnd wi ∈ W : ⟨G′ (wi) , v − wi⟩ ≥ 0 for all v ∈ Rn with η > 0,
or more speciﬁcally
ﬁnd wi ∈ W : ⟨ηG′ (wi) , v − wi⟩ ≥ 0 for all v ∈ Rn. (2.5)

Similar Retrieval Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Retrieval Cosine Similarity: 0.5702

Query Cosine Similarity (Original vs. Similar Question): 0.8931
============================================================
Processing row 4:
Original Question:
Describe the backpropagation algorithm used in neural networks.
Similar Question:
Search for the question: How does the backpropagation algorithm function in neural network training?
============================================================
{'filters': {'query': 'backpropagation algorithm neural network training', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'How does the backpropagation algorithm function in neural network training?'}

Running Search with filters: {'query': 'backpropagation algorithm neural network training', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 192 chunks from 'ZORB: A Derivative-Free Backpropagation Algorithm for Neural Networks'

Total Chunks Extracted: 192

Upserted 192 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Similar Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
the same as the traditional BP algorithm. While backpropagating through activation functions, the
inverse of the activation function is applied, i.e., the feedback matrices must be deactivated. However,

Similar Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Retrieval Cosine Similarity: 0.5272

Comparison 3:
Original Retrieval Result:
ZORB: A Derivative-Free Backpropagation
Algorithm for Neural Networks
Varun Ranganathan
Department of Computing Science
University of Alberta
Edmonton, AB T6G 2E8
vrangana@ualberta.ca
Alex Lewandowski
Department of Computing Science
University of Alberta
Edmonton, AB T6G 2E8
lewandowski@ualberta.ca

Similar Retrieval Result:
ZORB: A Derivative-Free Backpropagation
Algorithm for Neural Networks
Varun Ranganathan
Department of Computing Science
University of Alberta
Edmonton, AB T6G 2E8
vrangana@ualberta.ca
Alex Lewandowski
Department of Computing Science
University of Alberta
Edmonton, AB T6G 2E8
lewandowski@ualberta.ca

Retrieval Cosine Similarity: 1.0000

Query Cosine Similarity (Original vs. Similar Question): 0.8541
============================================================
Processing row 5:
Original Question:
What are Convolutional Neural Networks (CNN) and their main applications?
Similar Question:
Search for the question: Can you describe what Convolutional Neural Networks (CNN) are and their primary uses?
============================================================
{'filters': {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Can you describe what Convolutional Neural Networks (CNN) are and their primary uses?'}

Running Search with filters: {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'ILP-M Conv: Optimize Convolution Algorithm for Single-Image Convolution Neural Network Inference on Mobile GPUs'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
References
[1] Xu Han. Implement convolution in cnn. http://xuhan.me/2016/09/09/conv/, 2016.
[2] Fabian Tschopp, Julien NP Martel, Srinivas C Turaga, Matthew Cook, and Jan Funke. Efﬁcient convolutional

Similar Retrieval Result:
References
[1] Xu Han. Implement convolution in cnn. http://xuhan.me/2016/09/09/conv/, 2016.
[2] Fabian Tschopp, Julien NP Martel, Srinivas C Turaga, Matthew Cook, and Jan Funke. Efﬁcient convolutional

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
CNNs mainly use small convolution ﬁlters.
3.1 Unrolling-based Convolution Algorithms
Unrolling-based convolution algorithm is the most popular GPU convolution algorithm for CNNs training. The key

Similar Retrieval Result:
References
[1] Xu Han. Implement convolution in cnn. http://xuhan.me/2016/09/09/conv/, 2016.
[2] Fabian Tschopp, Julien NP Martel, Srinivas C Turaga, Matthew Cook, and Jan Funke. Efﬁcient convolutional

Retrieval Cosine Similarity: 0.5919

Comparison 3:
Original Retrieval Result:
• Activation after the output layer: sigmoid
C.4.2 Convolution Neural Networks
Experiments described in section 3 of the main paper involve 3 CNNs. The architecture for each neural network
is as follows:
1. Conv1:
• Kernel size: 3 x 3
• Kernels in each convolution layer: 32

Similar Retrieval Result:
CNNs mainly use small convolution ﬁlters.
3.1 Unrolling-based Convolution Algorithms
Unrolling-based convolution algorithm is the most popular GPU convolution algorithm for CNNs training. The key

Retrieval Cosine Similarity: 0.4968

Query Cosine Similarity (Original vs. Similar Question): 0.8394
============================================================
Processing row 6:
Original Question:
Explain the concept of Reinforcement Learning.
Similar Question:
Search for the question: What is Reinforcement Learning and how does it enable decision-making?
============================================================
{'filters': {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is Reinforcement Learning and how does it enable decision-making?'}

Running Search with filters: {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'Some Insights into Lifelong Reinforcement Learning Systems'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Similar Retrieval Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Retrieval Cosine Similarity: 0.6869

Comparison 2:
Original Retrieval Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Similar Retrieval Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Retrieval Cosine Similarity: 1.0000

Comparison 3:
Original Retrieval Result:
Some Insights into Lifelong Reinforcement Learning Systems
Changjian Li1
Abstract
A lifelong reinforcement learning system is a
learning system that has the ability to learn
through trail-and-error interaction with the en-
vironment over its lifetime. In this paper, I give

Similar Retrieval Result:
reinforcement learning system was given, with an empha-
size on how learning bias can be embedded into the learning
system through the synergy of the reward language and the
learning algorithm.
Acknowledgements
The author would like to thank Gaurav Sharma (Borealis

Retrieval Cosine Similarity: 0.5305

Query Cosine Similarity (Original vs. Similar Question): 0.8050
============================================================
Processing row 7:
Original Question:
What is the difference between Type I and Type II errors in hypothesis testing?
Similar Question:
Search for the question: How do Type I and Type II errors differ in hypothesis testing?
============================================================
{'filters': {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'How do Type I and Type II errors differ in hypothesis testing?'}

Running Search with filters: {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 219 chunks from 'Agnostic tests can control the type I and type II errors simultaneously'

Total Chunks Extracted: 219

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 19 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE.ATyPE)))ERROROCCURSWHENEVERTHETESTREMAINSAGNOSTIC.AN
AGNOSTICTESTCANBEDESIGNEDTOCONTROLTHEERRORSOFTyPE)AND)).
DEﬁNITION ANAGNOSTICTEST, φ,HAS(α, β)-LEVELIFTHETEST’SPROBABILITIESOFCOMMITTINGERRORSOFTyPE)AND))ARE
CONTROLLEDBy,RESPECTIVELy,αANDβ.4HATIS,

Similar Retrieval Result:
Sample 2
Reject H 0
Sample 1
Confidence Interval
R 1
R 2
Confidence Interval
R 1
R 2
FIG52E 4 )LLUSTRATIONOFTHEAGNOSTICTESTBASEDON R1 ANDR2 (SECTION4.2)WHENH0 :θ=θ0.
AGNOSTICT-TEST CONSIDERSECTION2.2.&OREACHµ∗ ∈Ò,LETH0,µ∗ :µ = µ∗.4HE5-05AGNOSTICTESTISBASEDONTHE
REGIONESTIMATORS
R1(x)=
[

Retrieval Cosine Similarity: 0.4277

Comparison 2:
Original Retrieval Result:
Sample 2
Reject H 0
Sample 1
Confidence Interval
R 1
R 2
Confidence Interval
R 1
R 2
FIG52E 4 )LLUSTRATIONOFTHEAGNOSTICTESTBASEDON R1 ANDR2 (SECTION4.2)WHENH0 :θ=θ0.
AGNOSTICT-TEST CONSIDERSECTION2.2.&OREACHµ∗ ∈Ò,LETH0,µ∗ :µ = µ∗.4HE5-05AGNOSTICTESTISBASEDONTHE
REGIONESTIMATORS
R1(x)=
[

Similar Retrieval Result:
Sample 2
Reject H 0
Sample 1
Confidence Interval
R 1
R 2
Confidence Interval
R 1
R 2
FIG52E 4 )LLUSTRATIONOFTHEAGNOSTICTESTBASEDON R1 ANDR2 (SECTION4.2)WHENH0 :θ=θ0.
AGNOSTICT-TEST CONSIDERSECTION2.2.&OREACHµ∗ ∈Ò,LETH0,µ∗ :µ = µ∗.4HE5-05AGNOSTICTESTISBASEDONTHE
REGIONESTIMATORS
R1(x)=
[

Retrieval Cosine Similarity: 1.0000

Comparison 3:
Original Retrieval Result:
HyPOTHESIS.4HEREMAINDEROFTHISSECTIONExPLORESALTERNATIVEMETHODSOFCONTROLLINGTHETyPE))ERRORPROBABILITIES.
/NEALTERNATIVEWAyTOCONTROLTHETyPE))ERRORPROBABILITIESISTOREqUIRESOLELyTHAT SUPθ∈H′
1
Ðθ(φ=0)≤ β,WHERE
H′
1 ISASUBSETOF H1 WHICHISRELEVANTFORTHEPRACTITIONER./NEPROCEDURETOCHOOSE H′

Similar Retrieval Result:
HyPOTHESIS.4HEREMAINDEROFTHISSECTIONExPLORESALTERNATIVEMETHODSOFCONTROLLINGTHETyPE))ERRORPROBABILITIES.
/NEALTERNATIVEWAyTOCONTROLTHETyPE))ERRORPROBABILITIESISTOREqUIRESOLELyTHAT SUPθ∈H′
1
Ðθ(φ=0)≤ β,WHERE
H′
1 ISASUBSETOF H1 WHICHISRELEVANTFORTHEPRACTITIONER./NEPROCEDURETOCHOOSE H′

Retrieval Cosine Similarity: 1.0000

Query Cosine Similarity (Original vs. Similar Question): 0.9236
============================================================
Processing row 8:
Original Question:
How does the Gradient Descent optimization algorithm work?
Similar Question:
Search for the question: Can you detail the process of Gradient Descent optimization?
============================================================

In [14]:
similarity_comparison_df

,original_question,similar_question,comparison_index,orig_retrieved_result,sim_retrieved_result,retrieval_cosine_similarity,query_cosine_similarity
0,Explain the Typiclust algorithm,Search for the question: What is the fundament...,1,given in Alg. 1 (see more details in App. F.1)...,at https://github.com/avihu111/TypiClust.\n1. ...,0.494900,0.928873
1,Explain the Typiclust algorithm,Search for the question: What is the fundament...,2,by clustering the dataset and sampling the den...,at https://github.com/avihu111/TypiClust.\n1. ...,0.470333,0.928873
2,Explain the Typiclust algorithm,Search for the question: What is the fundament...,3,"w.r.tLi−1), while selecting the most typical e...",by clustering the dataset and sampling the den...,0.568641,0.928873
3,What is the Support Vector Machine (SVM) and h...,Search for the question: How does a Support Ve...,1,2010 Mathematics Subject Classiﬁcation:62H30.\...,support vector machine. We also provide suﬃcie...,0.647456,0.893119
4,What is the Support Vector Machine (SVM) and h...,Search for the question: How does a Support Ve...,2,support vector machine. We also provide suﬃcie...,support vector machine. We also provide suﬃcie...,1.000000,0.893119
5,What is the Support Vector Machine (SVM) and h...,Search for the question: How does a Support Ve...,3,We call this problem as the Generalized Suppor...,2010 Mathematics Subject Classiﬁcation:62H30.\...,0.570207,0.893119
6,Describe the backpropagation algorithm used in...,Search for the question: How does the backprop...,1,traditional backpropagation with Gradient Desc...,traditional backpropagation with Gradient Desc...,1.000000,0.854085
7,Describe the backpropagation algorithm used in...,Search for the question: How does the backprop...,2,the same as the traditional BP algorithm. Whil...,traditional backpropagation with Gradient Desc...,0.527170,0.854085
8,Describe the backpropagation algorithm used in...,Search for the question: How does the backprop...,3,ZORB: A Derivative-Free Backpropagation\nAlgor...,ZORB: A Derivative-Free Backpropagation\nAlgor...,1.000000,0.854085
9,What are Convolutional Neural Networks (CNN) a...,Search for the question: Can you describe what...,1,References\n[1] Xu Han. Implement convolution ...,References\n[1] Xu Han. Implement convolution ...,1.000000,0.839415
10,What are Convolutional Neural Networks (CNN) a...,Search for the question: Can you describe what...,2,CNNs mainly use small convolution ﬁlters.\n3.1...,References\n[1] Xu Han. Implement convolution ...,0.591895,0.839415
11,What are Convolutional Neural Networks (CNN) a...,Search for the question: Can you describe what...,3,• Activation after the output layer: sigmoid\n...,CNNs mainly use small convolution ﬁlters.\n3.1...,0.496822,0.839415
12,Explain the concept of Reinforcement Learning.,Search for the question: What is Reinforcement...,1,reward space of the learning system. In other ...,type of learning system. Some insights into li...,0.686934,0.805001
13,Explain the concept of Reinforcement Learning.,Search for the question: What is Reinforcement...,2,type of learning system. Some insights into li...,type of learning system. Some insights into li...,1.000000,0.805001
14,Explain the concept of Reinforcement Learning.,Search for the question: What is Reinforcement...,3,Some Insights into Lifelong Reinforcement Lear...,"reinforcement learning system was given, with ...",0.530525,0.805001
15,What is the difference between Type I and Type...,Search for the question: How do Type I and Typ...,1,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,Sample 2\nReject H 0\nSample 1\nConfidence Int...,0.427660,0.923597
16,What is the difference between Type I and Type...,Search for the question: How do Type I and Typ...,2,Sample 2\nReject H 0\nSample 1\nConfidence Int...,Sample 2\nReject H 0\nSample 1\nConfidence Int...,1.000000,0.923597
17,What is the difference between Type I and Type...,Search for the question: How do Type I and Typ...,3,HyPOTHESIS.4HEREMAINDEROFTHISSECTIONExPLORESAL...,HyPOTHESIS.4HEREMAINDEROFTHISSECTIONExPLORESAL...,1.000000,0.923597
18,How does the Gradient Descent optimization alg...,Search for the question: Can you detail the pr...,1,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,1.000000,0.757021
19,How does the Gradient Descent optimization alg...,Search for the question: Can you detail the pr...,2,traditional backpropagation with Gradient Desc...,In Advances in Neural Information Processing S...,0.620690,0.757021
20,How does the Gradient Descent optimization alg...,Search for the question: Can you detail the pr...,3,Since SGD approximates the gradient using a si...,overview of mini-batch gradient descent. Cited...,0.657968,0.757021
21,What is Overfitting in machine learning and ho...,Search for the question: How can overfitting b...,1,"overﬁtting, like zero training loss, and use n...","overﬁtting, like zero training loss, and use n...",1.000000,0.867256
22,What is Overfitting in machine learning and ho...,Search for the question: How can overfitting b...,2,students to become proﬁcient machine learning ...,could lead to potential risk of overfitting (H...,0.624283,0.867256
23,What is Overfitting in machine learning and ho...,Search for the question: How can overfitting b...,3,Teaching the concept of overﬁtting is not easy...,Teaching the concept of overﬁtting is not easy...,1.000000,0.867256
24,what is concept of Transfer Learning in deep l...,Search for the question: Can you explain the c...,1,An eﬀective solution to this challenge is to e...,An eﬀective solution to this challenge is to e...,1.000000,0.882798
25,what is concept of Transfer Learning in deep l...,Search for the question: Can you explain the c...,2,knowledge from previous learning experiences w...,The survey is organized around how to acquire ...,0.699202,0.882798
26,what is concept of Transfer Learning in deep l...,Search for the question: Can you explain the c...,3,improving the transferability of deep models. ...,in pre-training and adaptation and we will giv...,0.655992,0.882798

In [15]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - text-embedding-3-small",          # 在ClearML中显示的标题
    series="Embedding Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=similarity_comparison_df             # 直接传入 DataFrame
)

# Evaluate text-embedding-3-large

In [ ]:
index_name = create_index()
index_obj = pc.Index(index_name)

In [16]:
from dotenv import load_dotenv
import os 
load_dotenv()
os.environ["EMBEDDING_MODEL"] = 'text-embedding-3-large'
os.environ["USE_OPENAI_EMBEDDINGS"] = 'True'

model_name = os.getenv("EMBEDDING_MODEL", 'text-embedding-3-large')
print("Using embedding model:", model_name) 

model_name = os.getenv("USE_OPENAI_EMBEDDINGS", 'True')
print("whether use openai embedding model:", model_name)
# sometimes you need to restart the kernel in order for this env settings to work

Using embedding model: text-embedding-3-large
whether use openai embedding model: True

In [17]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer, util

# 加载预训练的 SentenceTransformer 模型
model = SentenceTransformer('all-MiniLM-L6-v2')

# 假设 df 已经加载，包含以下列：
# 'question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 例如：df = pd.read_csv("your_dataset.csv")

all_scores = []         # 用于存储每个 question 的 3 个 cosine similarity 分数
comparison_results = [] # 用于存储所有比较结果，稍后转换成 DataFrame

# 遍历 DataFrame 中的每一行（假设有10个问题，即 10 行，共 3*10 比较）
for idx, row in df.iterrows():
    print("=" * 60)
    print(f"Question {idx+1}:")
    print(row['question'])
    print("=" * 60)
    
    # 用户查询即当前行的 question
    user_query = row['question']
    
    # 参考文本列表，顺序与检索结果顺序对应
    ref_paragraphs = [
        row['reference paragraph 1'],
        row['reference paragraph 2'],
        row['reference paragraph 3']
    ]
    
    # 调用检索函数获取结果，返回的 ans 是一个列表，每个元素为 { "text": ..., "source": ... }
    try:
        ans = retrieve_ans(user_query, index_obj)
    except KeyError as e:
        print(f"KeyError encountered for question {idx+1}: {e}. Skipping this question.\n")
        continue

    if ans == 0 or len(ans) < 3:
        print(f"WARNING: No sufficient results for question {idx+1}: {user_query}\n")
        continue
    
    scores = []
    # 针对前三个结果进行比较：第一条检索结果对应第一个参考段落，依此类推
    for i in range(3):
        result_text = ans[i]['text']
        ref_text = ref_paragraphs[i]
        
        print(f"\n--- Comparison {i+1} ---")
        print("Retrieved Result:")
        print(result_text)
        print("\nReference Paragraph:")
        print(ref_text)
        
        # 分别生成两段文本的 embedding
        emb_result = model.encode(result_text, convert_to_tensor=True)
        emb_ref = model.encode(ref_text, convert_to_tensor=True)
        
        # 计算 cosine similarity（util.cos_sim 返回的是 tensor）
        score = util.cos_sim(emb_result, emb_ref)
        similarity = score.item()
        scores.append(similarity)
        
        print(f"\nCosine Similarity for Comparison {i+1}: {similarity:.4f}")
        
        # 记录当前比较结果到 comparison_results 列表中
        comparison_results.append({
            "question": user_query,
            "comparison_index": i+1,
            "retrieved_result": result_text,
            "reference_paragraph": ref_text,
            "cosine_similarity": similarity
        })
    
    print("\nSimilarity scores for Question {}: {}".format(idx+1, scores))
    all_scores.append(scores)

# 将所有分数转换为 numpy 数组，shape 为 (num_questions, 3)
score_matrix = np.array(all_scores)
print("\n" + "=" * 60)
print("Cosine Similarity Matrix:")
print(score_matrix)

# 计算所有相似度的均值
mean_score = score_matrix.mean()
print("\nMean Cosine Similarity: {:.4f}".format(mean_score))

# 将所有比较结果转换为 DataFrame 并打印输出
comparison_df = pd.DataFrame(comparison_results)
print("\nComparison Results DataFrame:")
print(comparison_df)

============================================================
Question 1:
Describe the K-means clustering algorithm.
============================================================
{'filters': {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Describe the K-means clustering algorithm.'}

Running Search with filters: {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 89 chunks from 'An implementation of the relational k-means algorithm'

Total Chunks Extracted: 89

Upserted 89 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Reference Paragraph:
The process, which is called 'k-means,' appears to give partitions which are reasonably efficient in the sense of within-class variance… Also, the k-means procedure is easily programmed and is computationally economical, so that it is feasible to process very large samples on a digital computer?

Cosine Similarity for Comparison 1: 0.6026

--- Comparison 2 ---
Retrieved Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Reference Paragraph:
Stated informally, the k-means procedure consists of simply starting with k groups each of which consists of a single random point, and thereafter adding each new point to the group whose mean the new point is nearest. After a point is added to a group, the mean of that group is adjusted in order to take account of the new point?

Cosine Similarity for Comparison 2: 0.6620

--- Comparison 3 ---
Retrieved Result:
2 Relational k-means
First, we provide a brief outline of the algorithm. LetA ∈ Rn×n be the squared distance
matrix. That is, Aij = f(pi, pj)2. The algorithm starts with some initial clustering and
improves it by repeatedly performing an iteration step. The algorithm stops if the last

Reference Paragraph:
Perhaps the most obvious application of the k-means process is to the problem of "similarity grouping" or "clustering." The point of view taken in this application is not to find some unique, definitive grouping, but rather to simply aid the investigator in obtaining qualitative and quantitative understanding of large amounts of N-dimensional data?

Cosine Similarity for Comparison 3: 0.6008

Similarity scores for Question 1: [0.6025615930557251, 0.6620315909385681, 0.600822925567627]
============================================================
Question 2:
Explain the Typiclust algorithm
============================================================
{'filters': {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Explain the Typiclust algorithm'}

Running Search with filters: {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 394 chunks from 'Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets'

Total Chunks Extracted: 394

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 194 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Reference Paragraph:
TypiClust is composed of three steps: (1) Representation learning: learn a semantically meaningful feature space using self-supervised learning. (2) Clustering: partition the data to ensure diversity. (3) Query: select the most typical examples (i.e., dense points) from the largest uncovered clusters

Cosine Similarity for Comparison 1: 0.6234

--- Comparison 2 ---
Retrieved Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Reference Paragraph:
To capture the principle of max density, we define the Typicality of an example by the inverse of the average Euclidean distance to its K nearest neighbors. That is, typical points are those located in high-density areas of the feature space, and thus likely to be representative of the data distribution

Cosine Similarity for Comparison 2: 0.1381

--- Comparison 3 ---
Retrieved Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Reference Paragraph:
Algorithm 1: Given an unlabeled pool and a budget B, first learn representations, then cluster the embedding space into B clusters. For each cluster, select the example with the highest typicality. This yields B diverse and representative samples for labeling?

Cosine Similarity for Comparison 3: 0.3325

Similarity scores for Question 2: [0.6233622431755066, 0.13806737959384918, 0.3325369954109192]
============================================================
Question 3:
What is the Support Vector Machine (SVM) and how does it work?
============================================================
{'filters': {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is the Support Vector Machine (SVM) and how does it work?'}

Running Search with filters: {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 132 chunks from 'Linear Classification of data with Support Vector Machines and Generalized Support Vector Machines'

Total Chunks Extracted: 132

Upserted 132 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Reference Paragraph:
The support-vector network implements the following idea: it maps the input vectors into some high dimensional feature space Z through some non-linear mapping chosen a priori. In this space a linear decision surface is constructed with special properties that ensure high generalization ability of the network.

Cosine Similarity for Comparison 1: 0.5048

--- Comparison 2 ---
Retrieved Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Reference Paragraph:
An optimal hyperplane is here defined as the linear decision function with maximal margin between the vectors of the two classes. It was observed that to construct such optimal hyperplanes one only has to take into account a small amount of the training data, the so called support vectors, which determine this margin.

Cosine Similarity for Comparison 2: 0.4264

--- Comparison 3 ---
Retrieved Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Reference Paragraph:
Using different dot-products K(u, v) one can construct different learning machines with arbitrary types of decision surfaces. The decision surface of these machines has a form ∑ ai K(xi, x), where xi is the image of a support vector and ai is its weight. The only difference is that instead of computing dot-products directly, kernels are used.

Cosine Similarity for Comparison 3: 0.5319

Similarity scores for Question 3: [0.5048344731330872, 0.42637449502944946, 0.5319231152534485]
============================================================
Question 4:
Describe the backpropagation algorithm used in neural networks.
============================================================
{'filters': {'query': 'backpropagation algorithm neural networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Describe the backpropagation algorithm used in neural networks.'}

Running Search with filters: {'query': 'backpropagation algorithm neural networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 192 chunks from 'ZORB: A Derivative-Free Backpropagation Algorithm for Neural Networks'

Total Chunks Extracted: 192

Upserted 192 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Reference Paragraph:
Introduces backpropagation as a method for error propagation.

Cosine Similarity for Comparison 1: 0.6312

--- Comparison 2 ---
Retrieved Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Reference Paragraph:
The backward pass which propagates derivatives from the top layer back to the bottom one is more complicated. We start by computing ?E/?y for the output units, apply the chain rule to get ?E/?x, then compute how error changes with respect to weights: ?E/?w = ?E/?x × y. This process repeats layer by layer to update weights across the network.

Cosine Similarity for Comparison 2: 0.4599

--- Comparison 3 ---
Retrieved Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Reference Paragraph:
The simplest version of gradient descent is to change each weight by an amount proportional to the accumulated ?E/?w:

Cosine Similarity for Comparison 3: 0.4915

Similarity scores for Question 4: [0.631150484085083, 0.4598606824874878, 0.49150407314300537]
============================================================
Question 5:
What are Convolutional Neural Networks (CNN) and their main applications?
============================================================
{'filters': {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What are Convolutional Neural Networks (CNN) and their main applications?'}

Running Search with filters: {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'ILP-M Conv: Optimize Convolution Algorithm for Single-Image Convolution Neural Network Inference on Mobile GPUs'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
CNNs learn features to recognise shapes with a high degree
of invariance to translation, scaling, skewing, and other types
of distortion [11].
CNNs achieve this by including speciﬁc types of layers with
different respective purposes:
• Feature extraction: Each neuron takes inputs only from a

Reference Paragraph:
Convolutional neural networks (CNNs) constitute one such class of models. Their capacity can be controlled by varying their depth and breadth, and they also make strong and mostly correct assumptions about the nature of images (namely, stationarity of statistics and locality of pixel dependencies).

Cosine Similarity for Comparison 1: 0.6440

--- Comparison 2 ---
Retrieved Result:
Fig. 1: Example CNN architecture with alternating convolution
and subsampling layers [11].
Convolutional neural networks (CNNs), are a speciﬁc class
of ANNs created speciﬁcally for image processing tasks.
CNNs learn features to recognise shapes with a high degree

Reference Paragraph:
We trained a large, deep convolutional neural network to classify the 1.2 million high-resolution images in the ImageNet LSVRC-2010 contest into the 1000 different classes.

Cosine Similarity for Comparison 2: 0.4749

--- Comparison 3 ---
Retrieved Result:
References
[1] Xu Han. Implement convolution in cnn. http://xuhan.me/2016/09/09/conv/, 2016.
[2] Fabian Tschopp, Julien NP Martel, Srinivas C Turaga, Matthew Cook, and Jan Funke. Efﬁcient convolutional

Reference Paragraph:
To learn about thousands of objects from millions of images, we need a model with a large learning capacity. [...] CNNs have much fewer connections and parameters and so they are easier to train, while their theoretically-best performance is likely to be only slightly worse.

Cosine Similarity for Comparison 3: 0.4502

Similarity scores for Question 5: [0.6440198421478271, 0.47485631704330444, 0.4502198100090027]
============================================================
Question 6:
Explain the concept of Reinforcement Learning.
============================================================
{'filters': {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Explain the concept of Reinforcement Learning.'}

Running Search with filters: {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'Some Insights into Lifelong Reinforcement Learning Systems'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Reference Paragraph:
Reinforcement learning problems involve learning what to do—how to map situations to actions—so as to maximize a numerical reward signal. The learner is not told which actions to take but must discover which yield the most reward by trying them. Actions may affect not only the immediate reward but also the next situation and all subsequent rewards

Cosine Similarity for Comparison 1: 0.5753

--- Comparison 2 ---
Retrieved Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Reference Paragraph:
The reinforcement learning problem is meant to be a straightforward framing of the problem of learning from interaction to achieve a goal. The agent interacts with the environment by taking actions and receiving rewards and new states, aiming to maximize cumulative reward over time

Cosine Similarity for Comparison 2: 0.6526

--- Comparison 3 ---
Retrieved Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Reference Paragraph:
A reward signal defines the goal in a reinforcement learning problem. At each time step, the environment sends to the agent a single number, a reward. The agent’s objective is to maximize the total reward it receives. The only way to influence the reward is by acting in the environment?

Cosine Similarity for Comparison 3: 0.5693

Similarity scores for Question 6: [0.5753160119056702, 0.6525695323944092, 0.5692849159240723]
============================================================
Question 7:
What is the difference between Type I and Type II errors in hypothesis testing?
============================================================
{'filters': {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is the difference between Type I and Type II errors in hypothesis testing?'}

Running Search with filters: {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 219 chunks from 'Agnostic tests can control the type I and type II errors simultaneously'

Total Chunks Extracted: 219

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 19 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE.ATyPE)))ERROROCCURSWHENEVERTHETESTREMAINSAGNOSTIC.AN

In [18]:
comparison_df

,question,comparison_index,retrieved_result,reference_paragraph,cosine_similarity
0,Describe the K-means clustering algorithm.,1,The relational k-means algorithm takes an init...,"The process, which is called 'k-means,' appear...",0.602562
1,Describe the K-means clustering algorithm.,2,The relational k-means algorithm takes an init...,"Stated informally, the k-means procedure consi...",0.662032
2,Describe the K-means clustering algorithm.,3,"2 Relational k-means\nFirst, we provide a brie...",Perhaps the most obvious application of the k-...,0.600823
3,Explain the Typiclust algorithm,1,given in Alg. 1 (see more details in App. F.1)...,TypiClust is composed of three steps: (1) Repr...,0.623362
4,Explain the Typiclust algorithm,2,given in Alg. 1 (see more details in App. F.1)...,"To capture the principle of max density, we de...",0.138067
5,Explain the Typiclust algorithm,3,given in Alg. 1 (see more details in App. F.1)...,Algorithm 1: Given an unlabeled pool and a bud...,0.332537
6,What is the Support Vector Machine (SVM) and h...,1,2010 Mathematics Subject Classiﬁcation:62H30.\...,The support-vector network implements the foll...,0.504834
7,What is the Support Vector Machine (SVM) and h...,2,2010 Mathematics Subject Classiﬁcation:62H30.\...,An optimal hyperplane is here defined as the l...,0.426374
8,What is the Support Vector Machine (SVM) and h...,3,support vector machine. We also provide suﬃcie...,"Using different dot-products K(u, v) one can c...",0.531923
9,Describe the backpropagation algorithm used in...,1,traditional backpropagation with Gradient Desc...,Introduces backpropagation as a method for err...,0.631150
10,Describe the backpropagation algorithm used in...,2,traditional backpropagation with Gradient Desc...,The backward pass which propagates derivatives...,0.459861
11,Describe the backpropagation algorithm used in...,3,traditional backpropagation with Gradient Desc...,The simplest version of gradient descent is to...,0.491504
12,What are Convolutional Neural Networks (CNN) a...,1,CNNs learn features to recognise shapes with a...,Convolutional neural networks (CNNs) constitut...,0.644020
13,What are Convolutional Neural Networks (CNN) a...,2,Fig. 1: Example CNN architecture with alternat...,"We trained a large, deep convolutional neural ...",0.474856
14,What are Convolutional Neural Networks (CNN) a...,3,References\n[1] Xu Han. Implement convolution ...,To learn about thousands of objects from milli...,0.450220
15,Explain the concept of Reinforcement Learning.,1,reward space of the learning system. In other ...,Reinforcement learning problems involve learni...,0.575316
16,Explain the concept of Reinforcement Learning.,2,reward space of the learning system. In other ...,The reinforcement learning problem is meant to...,0.652570
17,Explain the concept of Reinforcement Learning.,3,reward space of the learning system. In other ...,A reward signal defines the goal in a reinforc...,0.569285
18,What is the difference between Type I and Type...,1,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,These errors will be of two kinds: (I) we reje...,0.525840
19,What is the difference between Type I and Type...,2,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,There is an essential difference in character ...,0.440594
20,What is the difference between Type I and Type...,3,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,We are influenced by the consequences which fo...,0.432751
21,How does the Gradient Descent optimization alg...,1,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,The simplest minimization procedure in such a ...,0.511702
22,How does the Gradient Descent optimization alg...,2,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,Gradient-Based Learning draws on the fact that...,0.538868
23,How does the Gradient Descent optimization alg...,3,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,A popular minimization procedure is the stocha...,0.604487
24,What is Overfitting in machine learning and ho...,1,"overﬁtting, like zero training loss, and use n...",Overfitting is the use of models or procedures...,0.555013
25,What is Overfitting in machine learning and ho...,2,"overﬁtting, like zero training loss, and use n...",Overfitting is undesirable for a number of rea...,0.410973
26,What is Overfitting in machine learning and ho...,3,students to become proﬁcient machine learning ...,Some sort of out-of-sample prediction is essen...,0.527279
27,what is concept of Transfer Learning in deep l...,1,An eﬀective solution to this challenge is to e...,Definition 1 (Transfer Learning) Given a sourc...,0.508730
28,what is concept of Transfer Learning in deep l...,2,An eﬀective solution to this challenge is to e...,"In 2005, the Broad Agency Announcement (BAA) 0...",0.511744
29,what is concept of Transfer Learning in deep l...,3,level learned features deﬁned in terms of lowe...,Transfer learning is motivated by the fact tha...,0.533873

In [19]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - text-embedding-3-large",          # 在ClearML中显示的标题
    series="Retrieval Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=comparison_df             # 直接传入 DataFrame
)

In [20]:
import pandas as pd
import numpy as np
from sentence_transformers import util


# 假设 df 已经加载，并且包含以下列：
# 'question', 'similar_question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 此外，之前生成的 comparison_df 包含原始 question 对应的 retrieval 结果，列包括：
# "question", "comparison_index", "retrieved_result", "reference_paragraph", "cosine_similarity"

# 用于存储新比较结果的列表
new_comparison_results = []

# 遍历 df 的前 10 行（或需要的数量）
for idx, row in df.head(10).iterrows():
    orig_question = row['question']
    sim_question = row['similar_question']
    
    print("=" * 60)
    print(f"Processing row {idx+1}:")
    print("Original Question:")
    print(orig_question)
    print("Similar Question:")
    print(sim_question)
    print("=" * 60)
    
    # 获取原始问题的 retrieval 结果
    # 从之前的 comparison_df 筛选出原始问题对应的 retrieval 结果（保证顺序为 1-3）
    orig_results_df = comparison_df[comparison_df['question'] == orig_question]
    if orig_results_df.empty or len(orig_results_df) < 3:
        print(f"WARNING: No sufficient retrieval results for original question {idx+1}. Skipping row.")
        continue
    
    orig_results = orig_results_df.sort_values("comparison_index")["retrieved_result"].tolist()
    
    # 获取相似问题的 retrieval 结果（调用检索函数）
    ans_sim = retrieve_ans(sim_question, index_obj)
    if ans_sim == 0 or len(ans_sim) < 3:
        print(f"WARNING: No sufficient retrieval results for similar question {idx+1}. Skipping row.")
        continue
    sim_results = [item['text'] for item in ans_sim[:3]]
    
    # 计算原始问题与相似问题本身的 cosine similarity
    emb_orig_question = model.encode(orig_question, convert_to_tensor=True)
    emb_sim_question = model.encode(sim_question, convert_to_tensor=True)
    query_cos_sim = util.cos_sim(emb_orig_question, emb_sim_question).item()
    
    # 对于对应位置的 retrieval 结果进行比较：只比较对应的 1 对 1, 2 对 2, 3 对 3
    for i in range(3):
        orig_text = orig_results[i]
        sim_text = sim_results[i]
        
        emb_orig = model.encode(orig_text, convert_to_tensor=True)
        emb_sim = model.encode(sim_text, convert_to_tensor=True)
        retrieval_cos_sim = util.cos_sim(emb_orig, emb_sim).item()
        
        new_comparison_results.append({
            "original_question": orig_question,
            "similar_question": sim_question,
            "comparison_index": i+1,
            "orig_retrieved_result": orig_text,
            "sim_retrieved_result": sim_text,
            "retrieval_cosine_similarity": retrieval_cos_sim,
            "query_cosine_similarity": query_cos_sim
        })
        
        print(f"\nComparison {i+1}:")
        print("Original Retrieval Result:")
        print(orig_text)
        print("\nSimilar Retrieval Result:")
        print(sim_text)
        print(f"\nRetrieval Cosine Similarity: {retrieval_cos_sim:.4f}")
    
    print(f"\nQuery Cosine Similarity (Original vs. Similar Question): {query_cos_sim:.4f}")

# 将所有新比较结果转换为 DataFrame
similarity_comparison_df = pd.DataFrame(new_comparison_results)
print("\nNew Comparison Results DataFrame:")
print(similarity_comparison_df)

# 如需计算所有 retrieval_cosine_similarity 的平均值
mean_retrieval_cos_sim = similarity_comparison_df["retrieval_cosine_similarity"].mean()
mean_query_cos_sim = similarity_comparison_df["query_cosine_similarity"].mean()

print("\nMean Retrieval Cosine Similarity: {:.4f}".format(mean_retrieval_cos_sim))
print("Mean Query Cosine Similarity: {:.4f}".format(mean_query_cos_sim))

============================================================
Processing row 1:
Original Question:
Describe the K-means clustering algorithm.
Similar Question:
Search for the question: Can you explain how the K-means clustering algorithm works?
============================================================
{'filters': {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Can you explain how the K-means clustering algorithm works?'}

Running Search with filters: {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 89 chunks from 'An implementation of the relational k-means algorithm'

Total Chunks Extracted: 89

Upserted 89 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Similar Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Similar Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Retrieval Cosine Similarity: 1.0000

Comparison 3:
Original Retrieval Result:
2 Relational k-means
First, we provide a brief outline of the algorithm. LetA ∈ Rn×n be the squared distance
matrix. That is, Aij = f(pi, pj)2. The algorithm starts with some initial clustering and
improves it by repeatedly performing an iteration step. The algorithm stops if the last

Similar Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Retrieval Cosine Similarity: 0.7621

Query Cosine Similarity (Original vs. Similar Question): 0.8821
============================================================
Processing row 2:
Original Question:
Explain the Typiclust algorithm
Similar Question:
Search for the question: What is the fundamental idea behind Typiclust algorithm?
============================================================
{'filters': {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is the fundamental idea behind Typiclust algorithm?'}

Running Search with filters: {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 394 chunks from 'Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets'

Total Chunks Extracted: 394

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 194 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Similar Retrieval Result:
at https://github.com/avihu111/TypiClust.
1. Introduction
Recent years have witnessed the emergence of deep learning
as the dominant force in advancing machine learning and
its applications. But this development is data-hungry – to a
large extent, deep learning owes its success to the growing

Retrieval Cosine Similarity: 0.4949

Comparison 2:
Original Retrieval Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Similar Retrieval Result:
at https://github.com/avihu111/TypiClust.
1. Introduction
Recent years have witnessed the emergence of deep learning
as the dominant force in advancing machine learning and
its applications. But this development is data-hungry – to a
large extent, deep learning owes its success to the growing

Retrieval Cosine Similarity: 0.4949

Comparison 3:
Original Retrieval Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Similar Retrieval Result:
at https://github.com/avihu111/TypiClust.
1. Introduction
Recent years have witnessed the emergence of deep learning
as the dominant force in advancing machine learning and
its applications. But this development is data-hungry – to a
large extent, deep learning owes its success to the growing

Retrieval Cosine Similarity: 0.4949

Query Cosine Similarity (Original vs. Similar Question): 0.9289
============================================================
Processing row 3:
Original Question:
What is the Support Vector Machine (SVM) and how does it work?
Similar Question:
Search for the question: How does a Support Vector Machine (SVM) operate?
============================================================
{'filters': {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'How does a Support Vector Machine (SVM) operate?'}

Running Search with filters: {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 132 chunks from 'Linear Classification of data with Support Vector Machines and Generalized Support Vector Machines'

Total Chunks Extracted: 132

Upserted 132 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Similar Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Retrieval Cosine Similarity: 0.6475

Comparison 2:
Original Retrieval Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Similar Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Retrieval Cosine Similarity: 0.6475

Comparison 3:
Original Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Similar Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Retrieval Cosine Similarity: 1.0000

Query Cosine Similarity (Original vs. Similar Question): 0.8931
============================================================
Processing row 4:
Original Question:
Describe the backpropagation algorithm used in neural networks.
Similar Question:
Search for the question: How does the backpropagation algorithm function in neural network training?
============================================================
{'filters': {'query': 'backpropagation algorithm neural network training', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'How does the backpropagation algorithm function in neural network training?'}

Running Search with filters: {'query': 'backpropagation algorithm neural network training', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 192 chunks from 'ZORB: A Derivative-Free Backpropagation Algorithm for Neural Networks'

Total Chunks Extracted: 192

Upserted 192 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Similar Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Similar Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Retrieval Cosine Similarity: 1.0000

Comparison 3:
Original Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Similar Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Retrieval Cosine Similarity: 1.0000

Query Cosine Similarity (Original vs. Similar Question): 0.8541
============================================================
Processing row 5:
Original Question:
What are Convolutional Neural Networks (CNN) and their main applications?
Similar Question:
Search for the question: Can you describe what Convolutional Neural Networks (CNN) are and their primary uses?
============================================================
{'filters': {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Can you describe what Convolutional Neural Networks (CNN) are and their primary uses?'}

Running Search with filters: {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'ILP-M Conv: Optimize Convolution Algorithm for Single-Image Convolution Neural Network Inference on Mobile GPUs'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
CNNs learn features to recognise shapes with a high degree
of invariance to translation, scaling, skewing, and other types
of distortion [11].
CNNs achieve this by including speciﬁc types of layers with
different respective purposes:
• Feature extraction: Each neuron takes inputs only from a

Similar Retrieval Result:
CNNs learn features to recognise shapes with a high degree
of invariance to translation, scaling, skewing, and other types
of distortion [11].
CNNs achieve this by including speciﬁc types of layers with
different respective purposes:
• Feature extraction: Each neuron takes inputs only from a

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
Fig. 1: Example CNN architecture with alternating convolution
and subsampling layers [11].
Convolutional neural networks (CNNs), are a speciﬁc class
of ANNs created speciﬁcally for image processing tasks.
CNNs learn features to recognise shapes with a high degree

Similar Retrieval Result:
References
[1] Xu Han. Implement convolution in cnn. http://xuhan.me/2016/09/09/conv/, 2016.
[2] Fabian Tschopp, Julien NP Martel, Srinivas C Turaga, Matthew Cook, and Jan Funke. Efﬁcient convolutional

Retrieval Cosine Similarity: 0.6246

Comparison 3:
Original Retrieval Result:
References
[1] Xu Han. Implement convolution in cnn. http://xuhan.me/2016/09/09/conv/, 2016.
[2] Fabian Tschopp, Julien NP Martel, Srinivas C Turaga, Matthew Cook, and Jan Funke. Efﬁcient convolutional

Similar Retrieval Result:
References
[1] Xu Han. Implement convolution in cnn. http://xuhan.me/2016/09/09/conv/, 2016.
[2] Fabian Tschopp, Julien NP Martel, Srinivas C Turaga, Matthew Cook, and Jan Funke. Efﬁcient convolutional

Retrieval Cosine Similarity: 1.0000

Query Cosine Similarity (Original vs. Similar Question): 0.8394
============================================================
Processing row 6:
Original Question:
Explain the concept of Reinforcement Learning.
Similar Question:
Search for the question: What is Reinforcement Learning and how does it enable decision-making?
============================================================
{'filters': {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is Reinforcement Learning and how does it enable decision-making?'}

Running Search with filters: {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'Some Insights into Lifelong Reinforcement Learning Systems'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Similar Retrieval Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Retrieval Cosine Similarity: 0.6869

Comparison 2:
Original Retrieval Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Similar Retrieval Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Retrieval Cosine Similarity: 0.6869

Comparison 3:
Original Retrieval Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Similar Retrieval Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Retrieval Cosine Similarity: 0.6869

Query Cosine Similarity (Original vs. Similar Question): 0.8050
============================================================
Processing row 7:
Original Question:
What is the difference between Type I and Type II errors in hypothesis testing?
Similar Question:
Search for the question: How do Type I and Type II errors differ in hypothesis testing?
============================================================
{'filters': {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'How do Type I and Type II errors differ in hypothesis testing?'}


In [21]:
similarity_comparison_df

,original_question,similar_question,comparison_index,orig_retrieved_result,sim_retrieved_result,retrieval_cosine_similarity,query_cosine_similarity
0,Describe the K-means clustering algorithm.,Search for the question: Can you explain how t...,1,The relational k-means algorithm takes an init...,The relational k-means algorithm takes an init...,1.000000,0.882090
1,Describe the K-means clustering algorithm.,Search for the question: Can you explain how t...,2,The relational k-means algorithm takes an init...,The relational k-means algorithm takes an init...,1.000000,0.882090
2,Describe the K-means clustering algorithm.,Search for the question: Can you explain how t...,3,"2 Relational k-means\nFirst, we provide a brie...",The relational k-means algorithm takes an init...,0.762053,0.882090
3,Explain the Typiclust algorithm,Search for the question: What is the fundament...,1,given in Alg. 1 (see more details in App. F.1)...,at https://github.com/avihu111/TypiClust.\n1. ...,0.494900,0.928873
4,Explain the Typiclust algorithm,Search for the question: What is the fundament...,2,given in Alg. 1 (see more details in App. F.1)...,at https://github.com/avihu111/TypiClust.\n1. ...,0.494900,0.928873
5,Explain the Typiclust algorithm,Search for the question: What is the fundament...,3,given in Alg. 1 (see more details in App. F.1)...,at https://github.com/avihu111/TypiClust.\n1. ...,0.494900,0.928873
6,What is the Support Vector Machine (SVM) and h...,Search for the question: How does a Support Ve...,1,2010 Mathematics Subject Classiﬁcation:62H30.\...,support vector machine. We also provide suﬃcie...,0.647456,0.893119
7,What is the Support Vector Machine (SVM) and h...,Search for the question: How does a Support Ve...,2,2010 Mathematics Subject Classiﬁcation:62H30.\...,support vector machine. We also provide suﬃcie...,0.647456,0.893119
8,What is the Support Vector Machine (SVM) and h...,Search for the question: How does a Support Ve...,3,support vector machine. We also provide suﬃcie...,support vector machine. We also provide suﬃcie...,1.000000,0.893119
9,Describe the backpropagation algorithm used in...,Search for the question: How does the backprop...,1,traditional backpropagation with Gradient Desc...,traditional backpropagation with Gradient Desc...,1.000000,0.854085
10,Describe the backpropagation algorithm used in...,Search for the question: How does the backprop...,2,traditional backpropagation with Gradient Desc...,traditional backpropagation with Gradient Desc...,1.000000,0.854085
11,Describe the backpropagation algorithm used in...,Search for the question: How does the backprop...,3,traditional backpropagation with Gradient Desc...,traditional backpropagation with Gradient Desc...,1.000000,0.854085
12,What are Convolutional Neural Networks (CNN) a...,Search for the question: Can you describe what...,1,CNNs learn features to recognise shapes with a...,CNNs learn features to recognise shapes with a...,1.000000,0.839415
13,What are Convolutional Neural Networks (CNN) a...,Search for the question: Can you describe what...,2,Fig. 1: Example CNN architecture with alternat...,References\n[1] Xu Han. Implement convolution ...,0.624587,0.839415
14,What are Convolutional Neural Networks (CNN) a...,Search for the question: Can you describe what...,3,References\n[1] Xu Han. Implement convolution ...,References\n[1] Xu Han. Implement convolution ...,1.000000,0.839415
15,Explain the concept of Reinforcement Learning.,Search for the question: What is Reinforcement...,1,reward space of the learning system. In other ...,type of learning system. Some insights into li...,0.686934,0.805001
16,Explain the concept of Reinforcement Learning.,Search for the question: What is Reinforcement...,2,reward space of the learning system. In other ...,type of learning system. Some insights into li...,0.686934,0.805001
17,Explain the concept of Reinforcement Learning.,Search for the question: What is Reinforcement...,3,reward space of the learning system. In other ...,type of learning system. Some insights into li...,0.686934,0.805001
18,What is the difference between Type I and Type...,Search for the question: How do Type I and Typ...,1,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,Sample 2\nReject H 0\nSample 1\nConfidence Int...,0.427660,0.923597
19,What is the difference between Type I and Type...,Search for the question: How do Type I and Typ...,2,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,Sample 2\nReject H 0\nSample 1\nConfidence Int...,0.427660,0.923597
20,What is the difference between Type I and Type...,Search for the question: How do Type I and Typ...,3,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,Sample 2\nReject H 0\nSample 1\nConfidence Int...,0.427660,0.923597
21,How does the Gradient Descent optimization alg...,Search for the question: Can you detail the pr...,1,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,1.000000,0.757021
22,How does the Gradient Descent optimization alg...,Search for the question: Can you detail the pr...,2,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,1.000000,0.757021
23,How does the Gradient Descent optimization alg...,Search for the question: Can you detail the pr...,3,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,1.000000,0.757021
24,What is Overfitting in machine learning and ho...,Search for the question: How can overfitting b...,1,"overﬁtting, like zero training loss, and use n...","overﬁtting, like zero training loss, and use n...",1.000000,0.867256
25,What is Overfitting in machine learning and ho...,Search for the question: How can overfitting b...,2,"overﬁtting, like zero training loss, and use n...","overﬁtting, like zero training loss, and use n...",1.000000,0.867256
26,What is Overfitting in machine learning and ho...,Search for the question: How can overfitting b...,3,students to become proﬁcient machine learning ...,could lead to potential risk of overfitting (H...,0.624283,0.867256
27,what is concept of Transfer Learning in deep l...,Search for the question: Can you explain the c...,1,An eﬀective solution to this challenge is to e...,An eﬀective solution to this challenge is to e...,1.000000,0.882798
28,what is concept of Transfer Learning in deep l...,Search for the question: Can you explain the c...,2,An eﬀective solution to this challenge is to e...,An eﬀective solution to this challenge is to e...,1.000000,0.882798
29,what is concept of Transfer Learning in deep l...,Search for the question: Can you explain the c...,3,level learned features deﬁned in terms of lowe...,The survey is organized around how to acquire ...,0.661453,0.882798

In [22]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - text-embedding-3-large",          # 在ClearML中显示的标题
    series="Embedding Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=similarity_comparison_df             # 直接传入 DataFrame
)

# Evaluate all-MiniLM-L6-v2

In [ ]:
index_name = create_index()
index_obj = pc.Index(index_name)

In [23]:
from dotenv import load_dotenv
import os 
load_dotenv() 
os.environ["USE_OPENAI_EMBEDDINGS"] = 'False'

model_name = os.getenv("USE_OPENAI_EMBEDDINGS", 'False')
print("whether use openai embedding model:", model_name)
# sometimes you need to restart the kernel in order for this env settings to work

whether use openai embedding model: False

In [24]:
import pandas as pd
import numpy as np
from sentence_transformers import util
 

# 假设 df 已经加载，包含以下列：
# 'question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 例如：df = pd.read_csv("your_dataset.csv")

all_scores = []         # 用于存储每个 question 的 3 个 cosine similarity 分数
comparison_results = [] # 用于存储所有比较结果，稍后转换成 DataFrame

# 遍历 DataFrame 中的每一行（假设有10个问题，即 10 行，共 3*10 比较）
for idx, row in df.iterrows():
    print("=" * 60)
    print(f"Question {idx+1}:")
    print(row['question'])
    print("=" * 60)
    
    # 用户查询即当前行的 question
    user_query = row['question']
    
    # 参考文本列表，顺序与检索结果顺序对应
    ref_paragraphs = [
        row['reference paragraph 1'],
        row['reference paragraph 2'],
        row['reference paragraph 3']
    ]
    
    # 调用检索函数获取结果，返回的 ans 是一个列表，每个元素为 { "text": ..., "source": ... }
    try:
        ans = retrieve_ans(user_query, index_obj)
    except KeyError as e:
        print(f"KeyError encountered for question {idx+1}: {e}. Skipping this question.\n")
        continue

    if ans == 0 or len(ans) < 3:
        print(f"WARNING: No sufficient results for question {idx+1}: {user_query}\n")
        continue
    
    scores = []
    # 针对前三个结果进行比较：第一条检索结果对应第一个参考段落，依此类推
    for i in range(3):
        result_text = ans[i]['text']
        ref_text = ref_paragraphs[i]
        
        print(f"\n--- Comparison {i+1} ---")
        print("Retrieved Result:")
        print(result_text)
        print("\nReference Paragraph:")
        print(ref_text)
        
        # 分别生成两段文本的 embedding
        emb_result = model.encode(result_text, convert_to_tensor=True)
        emb_ref = model.encode(ref_text, convert_to_tensor=True)
        
        # 计算 cosine similarity（util.cos_sim 返回的是 tensor）
        score = util.cos_sim(emb_result, emb_ref)
        similarity = score.item()
        scores.append(similarity)
        
        print(f"\nCosine Similarity for Comparison {i+1}: {similarity:.4f}")
        
        # 记录当前比较结果到 comparison_results 列表中
        comparison_results.append({
            "question": user_query,
            "comparison_index": i+1,
            "retrieved_result": result_text,
            "reference_paragraph": ref_text,
            "cosine_similarity": similarity
        })
    
    print("\nSimilarity scores for Question {}: {}".format(idx+1, scores))
    all_scores.append(scores)

# 将所有分数转换为 numpy 数组，shape 为 (num_questions, 3)
score_matrix = np.array(all_scores)
print("\n" + "=" * 60)
print("Cosine Similarity Matrix:")
print(score_matrix)

# 计算所有相似度的均值
mean_score = score_matrix.mean()
print("\nMean Cosine Similarity: {:.4f}".format(mean_score))

# 将所有比较结果转换为 DataFrame 并打印输出
comparison_df = pd.DataFrame(comparison_results)
print("\nComparison Results DataFrame:")
print(comparison_df)

============================================================
Question 1:
Describe the K-means clustering algorithm.
============================================================
{'filters': {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Describe the K-means clustering algorithm.'}

Running Search with filters: {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 89 chunks from 'An implementation of the relational k-means algorithm'

Total Chunks Extracted: 89

Upserted 89 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Reference Paragraph:
The process, which is called 'k-means,' appears to give partitions which are reasonably efficient in the sense of within-class variance… Also, the k-means procedure is easily programmed and is computationally economical, so that it is feasible to process very large samples on a digital computer?

Cosine Similarity for Comparison 1: 0.6026

--- Comparison 2 ---
Retrieved Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Reference Paragraph:
Stated informally, the k-means procedure consists of simply starting with k groups each of which consists of a single random point, and thereafter adding each new point to the group whose mean the new point is nearest. After a point is added to a group, the mean of that group is adjusted in order to take account of the new point?

Cosine Similarity for Comparison 2: 0.6620

--- Comparison 3 ---
Retrieved Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Reference Paragraph:
Perhaps the most obvious application of the k-means process is to the problem of "similarity grouping" or "clustering." The point of view taken in this application is not to find some unique, definitive grouping, but rather to simply aid the investigator in obtaining qualitative and quantitative understanding of large amounts of N-dimensional data?

Cosine Similarity for Comparison 3: 0.6928

Similarity scores for Question 1: [0.6025615930557251, 0.6620315909385681, 0.6928319931030273]
============================================================
Question 2:
Explain the Typiclust algorithm
============================================================
{'filters': {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Explain the Typiclust algorithm'}

Running Search with filters: {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 394 chunks from 'Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets'

Total Chunks Extracted: 394

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 194 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Reference Paragraph:
TypiClust is composed of three steps: (1) Representation learning: learn a semantically meaningful feature space using self-supervised learning. (2) Clustering: partition the data to ensure diversity. (3) Query: select the most typical examples (i.e., dense points) from the largest uncovered clusters

Cosine Similarity for Comparison 1: 0.6234

--- Comparison 2 ---
Retrieved Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Reference Paragraph:
To capture the principle of max density, we define the Typicality of an example by the inverse of the average Euclidean distance to its K nearest neighbors. That is, typical points are those located in high-density areas of the feature space, and thus likely to be representative of the data distribution

Cosine Similarity for Comparison 2: 0.1381

--- Comparison 3 ---
Retrieved Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Reference Paragraph:
Algorithm 1: Given an unlabeled pool and a budget B, first learn representations, then cluster the embedding space into B clusters. For each cluster, select the example with the highest typicality. This yields B diverse and representative samples for labeling?

Cosine Similarity for Comparison 3: 0.3325

Similarity scores for Question 2: [0.6233622431755066, 0.13806737959384918, 0.3325369954109192]
============================================================
Question 3:
What is the Support Vector Machine (SVM) and how does it work?
============================================================
{'filters': {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is the Support Vector Machine (SVM) and how does it work?'}

Running Search with filters: {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 132 chunks from 'Linear Classification of data with Support Vector Machines and Generalized Support Vector Machines'

Total Chunks Extracted: 132

Upserted 132 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Reference Paragraph:
The support-vector network implements the following idea: it maps the input vectors into some high dimensional feature space Z through some non-linear mapping chosen a priori. In this space a linear decision surface is constructed with special properties that ensure high generalization ability of the network.

Cosine Similarity for Comparison 1: 0.5048

--- Comparison 2 ---
Retrieved Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Reference Paragraph:
An optimal hyperplane is here defined as the linear decision function with maximal margin between the vectors of the two classes. It was observed that to construct such optimal hyperplanes one only has to take into account a small amount of the training data, the so called support vectors, which determine this margin.

Cosine Similarity for Comparison 2: 0.4264

--- Comparison 3 ---
Retrieved Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Reference Paragraph:
Using different dot-products K(u, v) one can construct different learning machines with arbitrary types of decision surfaces. The decision surface of these machines has a form ∑ ai K(xi, x), where xi is the image of a support vector and ai is its weight. The only difference is that instead of computing dot-products directly, kernels are used.

Cosine Similarity for Comparison 3: 0.4254

Similarity scores for Question 3: [0.5048344731330872, 0.42637449502944946, 0.42535173892974854]
============================================================
Question 4:
Describe the backpropagation algorithm used in neural networks.
============================================================
{'filters': {'query': 'backpropagation algorithm neural networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Describe the backpropagation algorithm used in neural networks.'}

Running Search with filters: {'query': 'backpropagation algorithm neural networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 192 chunks from 'ZORB: A Derivative-Free Backpropagation Algorithm for Neural Networks'

Total Chunks Extracted: 192

Upserted 192 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Reference Paragraph:
Introduces backpropagation as a method for error propagation.

Cosine Similarity for Comparison 1: 0.6312

--- Comparison 2 ---
Retrieved Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Reference Paragraph:
The backward pass which propagates derivatives from the top layer back to the bottom one is more complicated. We start by computing ?E/?y for the output units, apply the chain rule to get ?E/?x, then compute how error changes with respect to weights: ?E/?w = ?E/?x × y. This process repeats layer by layer to update weights across the network.

Cosine Similarity for Comparison 2: 0.4599

--- Comparison 3 ---
Retrieved Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Reference Paragraph:
The simplest version of gradient descent is to change each weight by an amount proportional to the accumulated ?E/?w:

Cosine Similarity for Comparison 3: 0.4915

Similarity scores for Question 4: [0.631150484085083, 0.4598606824874878, 0.49150407314300537]
============================================================
Question 5:
What are Convolutional Neural Networks (CNN) and their main applications?
============================================================
{'filters': {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What are Convolutional Neural Networks (CNN) and their main applications?'}

Running Search with filters: {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'ILP-M Conv: Optimize Convolution Algorithm for Single-Image Convolution Neural Network Inference on Mobile GPUs'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
CNNs learn features to recognise shapes with a high degree
of invariance to translation, scaling, skewing, and other types
of distortion [11].
CNNs achieve this by including speciﬁc types of layers with
different respective purposes:
• Feature extraction: Each neuron takes inputs only from a

Reference Paragraph:
Convolutional neural networks (CNNs) constitute one such class of models. Their capacity can be controlled by varying their depth and breadth, and they also make strong and mostly correct assumptions about the nature of images (namely, stationarity of statistics and locality of pixel dependencies).

Cosine Similarity for Comparison 1: 0.6440

--- Comparison 2 ---
Retrieved Result:
CNNs learn features to recognise shapes with a high degree
of invariance to translation, scaling, skewing, and other types
of distortion [11].
CNNs achieve this by including speciﬁc types of layers with
different respective purposes:
• Feature extraction: Each neuron takes inputs only from a

Reference Paragraph:
We trained a large, deep convolutional neural network to classify the 1.2 million high-resolution images in the ImageNet LSVRC-2010 contest into the 1000 different classes.

Cosine Similarity for Comparison 2: 0.4475

--- Comparison 3 ---
Retrieved Result:
Fig. 1: Example CNN architecture with alternating convolution
and subsampling layers [11].
Convolutional neural networks (CNNs), are a speciﬁc class
of ANNs created speciﬁcally for image processing tasks.
CNNs learn features to recognise shapes with a high degree

Reference Paragraph:
To learn about thousands of objects from millions of images, we need a model with a large learning capacity. [...] CNNs have much fewer connections and parameters and so they are easier to train, while their theoretically-best performance is likely to be only slightly worse.

Cosine Similarity for Comparison 3: 0.5076

Similarity scores for Question 5: [0.6440198421478271, 0.4474785327911377, 0.5076175928115845]
============================================================
Question 6:
Explain the concept of Reinforcement Learning.
============================================================
{'filters': {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Explain the concept of Reinforcement Learning.'}

Running Search with filters: {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'Some Insights into Lifelong Reinforcement Learning Systems'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Reference Paragraph:
Reinforcement learning problems involve learning what to do—how to map situations to actions—so as to maximize a numerical reward signal. The learner is not told which actions to take but must discover which yield the most reward by trying them. Actions may affect not only the immediate reward but also the next situation and all subsequent rewards

Cosine Similarity for Comparison 1: 0.5753

--- Comparison 2 ---
Retrieved Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Reference Paragraph:
The reinforcement learning problem is meant to be a straightforward framing of the problem of learning from interaction to achieve a goal. The agent interacts with the environment by taking actions and receiving rewards and new states, aiming to maximize cumulative reward over time

Cosine Similarity for Comparison 2: 0.6526

--- Comparison 3 ---
Retrieved Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Reference Paragraph:
A reward signal defines the goal in a reinforcement learning problem. At each time step, the environment sends to the agent a single number, a reward. The agent’s objective is to maximize the total reward it receives. The only way to influence the reward is by acting in the environment?

Cosine Similarity for Comparison 3: 0.5693

Similarity scores for Question 6: [0.5753160119056702, 0.6525695323944092, 0.5692849159240723]
============================================================
Question 7:
What is the difference between Type I and Type II errors in hypothesis testing?
============================================================
{'filters': {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is the difference between Type I and Type II errors in hypothesis testing?'}

Running Search with filters: {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 219 chunks from 'Agnostic tests can control the type I and type II errors simultaneously'

Total Chunks Extracted: 219

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 19 embeddings into index '8xkvyxtznx', namespace 'default'.

--- Comparison 1 ---
Retrieved Result:
ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE.ATyPE)))ERROROCCURSWHENEVERTHETESTREMAINSAGNOSTIC.AN

In [25]:
comparison_df

,question,comparison_index,retrieved_result,reference_paragraph,cosine_similarity
0,Describe the K-means clustering algorithm.,1,The relational k-means algorithm takes an init...,"The process, which is called 'k-means,' appear...",0.602562
1,Describe the K-means clustering algorithm.,2,The relational k-means algorithm takes an init...,"Stated informally, the k-means procedure consi...",0.662032
2,Describe the K-means clustering algorithm.,3,The relational k-means algorithm takes an init...,Perhaps the most obvious application of the k-...,0.692832
3,Explain the Typiclust algorithm,1,given in Alg. 1 (see more details in App. F.1)...,TypiClust is composed of three steps: (1) Repr...,0.623362
4,Explain the Typiclust algorithm,2,given in Alg. 1 (see more details in App. F.1)...,"To capture the principle of max density, we de...",0.138067
5,Explain the Typiclust algorithm,3,given in Alg. 1 (see more details in App. F.1)...,Algorithm 1: Given an unlabeled pool and a bud...,0.332537
6,What is the Support Vector Machine (SVM) and h...,1,2010 Mathematics Subject Classiﬁcation:62H30.\...,The support-vector network implements the foll...,0.504834
7,What is the Support Vector Machine (SVM) and h...,2,2010 Mathematics Subject Classiﬁcation:62H30.\...,An optimal hyperplane is here defined as the l...,0.426374
8,What is the Support Vector Machine (SVM) and h...,3,2010 Mathematics Subject Classiﬁcation:62H30.\...,"Using different dot-products K(u, v) one can c...",0.425352
9,Describe the backpropagation algorithm used in...,1,traditional backpropagation with Gradient Desc...,Introduces backpropagation as a method for err...,0.631150
10,Describe the backpropagation algorithm used in...,2,traditional backpropagation with Gradient Desc...,The backward pass which propagates derivatives...,0.459861
11,Describe the backpropagation algorithm used in...,3,traditional backpropagation with Gradient Desc...,The simplest version of gradient descent is to...,0.491504
12,What are Convolutional Neural Networks (CNN) a...,1,CNNs learn features to recognise shapes with a...,Convolutional neural networks (CNNs) constitut...,0.644020
13,What are Convolutional Neural Networks (CNN) a...,2,CNNs learn features to recognise shapes with a...,"We trained a large, deep convolutional neural ...",0.447479
14,What are Convolutional Neural Networks (CNN) a...,3,Fig. 1: Example CNN architecture with alternat...,To learn about thousands of objects from milli...,0.507618
15,Explain the concept of Reinforcement Learning.,1,reward space of the learning system. In other ...,Reinforcement learning problems involve learni...,0.575316
16,Explain the concept of Reinforcement Learning.,2,reward space of the learning system. In other ...,The reinforcement learning problem is meant to...,0.652570
17,Explain the concept of Reinforcement Learning.,3,reward space of the learning system. In other ...,A reward signal defines the goal in a reinforc...,0.569285
18,What is the difference between Type I and Type...,1,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,These errors will be of two kinds: (I) we reje...,0.525840
19,What is the difference between Type I and Type...,2,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,There is an essential difference in character ...,0.440594
20,What is the difference between Type I and Type...,3,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,We are influenced by the consequences which fo...,0.432751
21,How does the Gradient Descent optimization alg...,1,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,The simplest minimization procedure in such a ...,0.511702
22,How does the Gradient Descent optimization alg...,2,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,Gradient-Based Learning draws on the fact that...,0.538868
23,How does the Gradient Descent optimization alg...,3,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,A popular minimization procedure is the stocha...,0.604487
24,What is Overfitting in machine learning and ho...,1,"overﬁtting, like zero training loss, and use n...",Overfitting is the use of models or procedures...,0.555013
25,What is Overfitting in machine learning and ho...,2,"overﬁtting, like zero training loss, and use n...",Overfitting is undesirable for a number of rea...,0.410973
26,What is Overfitting in machine learning and ho...,3,"overﬁtting, like zero training loss, and use n...",Some sort of out-of-sample prediction is essen...,0.381127
27,what is concept of Transfer Learning in deep l...,1,An eﬀective solution to this challenge is to e...,Definition 1 (Transfer Learning) Given a sourc...,0.508730
28,what is concept of Transfer Learning in deep l...,2,An eﬀective solution to this challenge is to e...,"In 2005, the Broad Agency Announcement (BAA) 0...",0.511744
29,what is concept of Transfer Learning in deep l...,3,An eﬀective solution to this challenge is to e...,Transfer learning is motivated by the fact tha...,0.656957

In [26]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - all-MiniLM-L6-v2",          # 在ClearML中显示的标题
    series="Retrieval Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=comparison_df             # 直接传入 DataFrame
)

In [27]:
import pandas as pd
import numpy as np
from sentence_transformers import util
 

# 假设 df 已经加载，并且包含以下列：
# 'question', 'similar_question', 'reference paragraph 1', 'reference paragraph 2', 'reference paragraph 3'
# 此外，之前生成的 comparison_df 包含原始 question 对应的 retrieval 结果，列包括：
# "question", "comparison_index", "retrieved_result", "reference_paragraph", "cosine_similarity"

# 用于存储新比较结果的列表
new_comparison_results = []

# 遍历 df 的前 10 行（或需要的数量）
for idx, row in df.head(10).iterrows():
    orig_question = row['question']
    sim_question = row['similar_question']
    
    print("=" * 60)
    print(f"Processing row {idx+1}:")
    print("Original Question:")
    print(orig_question)
    print("Similar Question:")
    print(sim_question)
    print("=" * 60)
    
    # 获取原始问题的 retrieval 结果
    # 从之前的 comparison_df 筛选出原始问题对应的 retrieval 结果（保证顺序为 1-3）
    orig_results_df = comparison_df[comparison_df['question'] == orig_question]
    if orig_results_df.empty or len(orig_results_df) < 3:
        print(f"WARNING: No sufficient retrieval results for original question {idx+1}. Skipping row.")
        continue
    
    orig_results = orig_results_df.sort_values("comparison_index")["retrieved_result"].tolist()
    
    # 获取相似问题的 retrieval 结果（调用检索函数）
    ans_sim = retrieve_ans(sim_question, index_obj)
    if ans_sim == 0 or len(ans_sim) < 3:
        print(f"WARNING: No sufficient retrieval results for similar question {idx+1}. Skipping row.")
        continue
    sim_results = [item['text'] for item in ans_sim[:3]]
    
    # 计算原始问题与相似问题本身的 cosine similarity
    emb_orig_question = model.encode(orig_question, convert_to_tensor=True)
    emb_sim_question = model.encode(sim_question, convert_to_tensor=True)
    query_cos_sim = util.cos_sim(emb_orig_question, emb_sim_question).item()
    
    # 对于对应位置的 retrieval 结果进行比较：只比较对应的 1 对 1, 2 对 2, 3 对 3
    for i in range(3):
        orig_text = orig_results[i]
        sim_text = sim_results[i]
        
        emb_orig = model.encode(orig_text, convert_to_tensor=True)
        emb_sim = model.encode(sim_text, convert_to_tensor=True)
        retrieval_cos_sim = util.cos_sim(emb_orig, emb_sim).item()
        
        new_comparison_results.append({
            "original_question": orig_question,
            "similar_question": sim_question,
            "comparison_index": i+1,
            "orig_retrieved_result": orig_text,
            "sim_retrieved_result": sim_text,
            "retrieval_cosine_similarity": retrieval_cos_sim,
            "query_cosine_similarity": query_cos_sim
        })
        
        print(f"\nComparison {i+1}:")
        print("Original Retrieval Result:")
        print(orig_text)
        print("\nSimilar Retrieval Result:")
        print(sim_text)
        print(f"\nRetrieval Cosine Similarity: {retrieval_cos_sim:.4f}")
    
    print(f"\nQuery Cosine Similarity (Original vs. Similar Question): {query_cos_sim:.4f}")

# 将所有新比较结果转换为 DataFrame
similarity_comparison_df = pd.DataFrame(new_comparison_results)
print("\nNew Comparison Results DataFrame:")
print(similarity_comparison_df)

# 如需计算所有 retrieval_cosine_similarity 的平均值
mean_retrieval_cos_sim = similarity_comparison_df["retrieval_cosine_similarity"].mean()
mean_query_cos_sim = similarity_comparison_df["query_cosine_similarity"].mean()

print("\nMean Retrieval Cosine Similarity: {:.4f}".format(mean_retrieval_cos_sim))
print("Mean Query Cosine Similarity: {:.4f}".format(mean_query_cos_sim))

============================================================
Processing row 1:
Original Question:
Describe the K-means clustering algorithm.
Similar Question:
Search for the question: Can you explain how the K-means clustering algorithm works?
============================================================
{'filters': {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Can you explain how the K-means clustering algorithm works?'}

Running Search with filters: {'query': 'K-means clustering algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 89 chunks from 'An implementation of the relational k-means algorithm'

Total Chunks Extracted: 89

Upserted 89 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Similar Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Similar Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Retrieval Cosine Similarity: 1.0000

Comparison 3:
Original Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Similar Retrieval Result:
The relational k-means algorithm takes an initial clusteri ng (e.g. a random one), and
improves it through repeated applications of an iteration s tep which reclusters the data
points. The iteration step simply reassigns each data point to the cluster which minimized

Retrieval Cosine Similarity: 1.0000

Query Cosine Similarity (Original vs. Similar Question): 0.8821
============================================================
Processing row 2:
Original Question:
Explain the Typiclust algorithm
Similar Question:
Search for the question: What is the fundamental idea behind Typiclust algorithm?
============================================================
{'filters': {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is the fundamental idea behind Typiclust algorithm?'}

Running Search with filters: {'query': 'Typiclust algorithm', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 394 chunks from 'Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets'

Total Chunks Extracted: 394

Upserted 200 embeddings into index '8xkvyxtznx', namespace 'default'.
Upserted 194 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Similar Retrieval Result:
at https://github.com/avihu111/TypiClust.
1. Introduction
Recent years have witnessed the emergence of deep learning
as the dominant force in advancing machine learning and
its applications. But this development is data-hungry – to a
large extent, deep learning owes its success to the growing

Retrieval Cosine Similarity: 0.4949

Comparison 2:
Original Retrieval Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Similar Retrieval Result:
at https://github.com/avihu111/TypiClust.
1. Introduction
Recent years have witnessed the emergence of deep learning
as the dominant force in advancing machine learning and
its applications. But this development is data-hungry – to a
large extent, deep learning owes its success to the growing

Retrieval Cosine Similarity: 0.4949

Comparison 3:
Original Retrieval Result:
given in Alg. 1 (see more details in App. F.1). Note that,
unlike traditional active learning strategies, TypiClust relies
on self-supervised representation learning, and therefore
can be used for initial pool selection.
Algorithm 1 TypiClust initial pooling algorithm

Similar Retrieval Result:
at https://github.com/avihu111/TypiClust.
1. Introduction
Recent years have witnessed the emergence of deep learning
as the dominant force in advancing machine learning and
its applications. But this development is data-hungry – to a
large extent, deep learning owes its success to the growing

Retrieval Cosine Similarity: 0.4949

Query Cosine Similarity (Original vs. Similar Question): 0.9289
============================================================
Processing row 3:
Original Question:
What is the Support Vector Machine (SVM) and how does it work?
Similar Question:
Search for the question: How does a Support Vector Machine (SVM) operate?
============================================================
{'filters': {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'How does a Support Vector Machine (SVM) operate?'}

Running Search with filters: {'query': 'Support Vector Machine', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 132 chunks from 'Linear Classification of data with Support Vector Machines and Generalized Support Vector Machines'

Total Chunks Extracted: 132

Upserted 132 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Similar Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Retrieval Cosine Similarity: 0.6475

Comparison 2:
Original Retrieval Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Similar Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Retrieval Cosine Similarity: 0.6475

Comparison 3:
Original Retrieval Result:
2010 Mathematics Subject Classiﬁcation:62H30.
———————————————
1 Support Vector Machine
Over the last decade, support vector machines (SVMs) [2, 3, 13,14, 18] has
been revealed as very powerful and important tools for pattern c lassiﬁcation

Similar Retrieval Result:
support vector machine. We also provide suﬃcient conditions under which
the solution of generalized support vector machine exist. Various e xamples
are also present to show the validity of these results.
\end{conclusion}
References
[1] Adankon, M.M., and Cheriet, M.: Model selection for the LS-SVM.

Retrieval Cosine Similarity: 0.6475

Query Cosine Similarity (Original vs. Similar Question): 0.8931
============================================================
Processing row 4:
Original Question:
Describe the backpropagation algorithm used in neural networks.
Similar Question:
Search for the question: How does the backpropagation algorithm function in neural network training?
============================================================
{'filters': {'query': 'backpropagation algorithm neural network training', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'How does the backpropagation algorithm function in neural network training?'}

Running Search with filters: {'query': 'backpropagation algorithm neural network training', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 192 chunks from 'ZORB: A Derivative-Free Backpropagation Algorithm for Neural Networks'

Total Chunks Extracted: 192

Upserted 192 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Similar Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Similar Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Retrieval Cosine Similarity: 1.0000

Comparison 3:
Original Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Similar Retrieval Result:
traditional backpropagation with Gradient Descent.
1 Introduction
The workhorse of the deep learning paradigm is the Back-Propagation (BP) algorithm [33], which
combines Gradient Descent (GD) with the chain-rule and caching [32]. Despite the ongoing success

Retrieval Cosine Similarity: 1.0000

Query Cosine Similarity (Original vs. Similar Question): 0.8541
============================================================
Processing row 5:
Original Question:
What are Convolutional Neural Networks (CNN) and their main applications?
Similar Question:
Search for the question: Can you describe what Convolutional Neural Networks (CNN) are and their primary uses?
============================================================
{'filters': {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'Can you describe what Convolutional Neural Networks (CNN) are and their primary uses?'}

Running Search with filters: {'query': 'Convolutional Neural Networks', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'ILP-M Conv: Optimize Convolution Algorithm for Single-Image Convolution Neural Network Inference on Mobile GPUs'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
CNNs learn features to recognise shapes with a high degree
of invariance to translation, scaling, skewing, and other types
of distortion [11].
CNNs achieve this by including speciﬁc types of layers with
different respective purposes:
• Feature extraction: Each neuron takes inputs only from a

Similar Retrieval Result:
CNNs learn features to recognise shapes with a high degree
of invariance to translation, scaling, skewing, and other types
of distortion [11].
CNNs achieve this by including speciﬁc types of layers with
different respective purposes:
• Feature extraction: Each neuron takes inputs only from a

Retrieval Cosine Similarity: 1.0000

Comparison 2:
Original Retrieval Result:
CNNs learn features to recognise shapes with a high degree
of invariance to translation, scaling, skewing, and other types
of distortion [11].
CNNs achieve this by including speciﬁc types of layers with
different respective purposes:
• Feature extraction: Each neuron takes inputs only from a

Similar Retrieval Result:
CNNs learn features to recognise shapes with a high degree
of invariance to translation, scaling, skewing, and other types
of distortion [11].
CNNs achieve this by including speciﬁc types of layers with
different respective purposes:
• Feature extraction: Each neuron takes inputs only from a

Retrieval Cosine Similarity: 1.0000

Comparison 3:
Original Retrieval Result:
Fig. 1: Example CNN architecture with alternating convolution
and subsampling layers [11].
Convolutional neural networks (CNNs), are a speciﬁc class
of ANNs created speciﬁcally for image processing tasks.
CNNs learn features to recognise shapes with a high degree

Similar Retrieval Result:
References
[1] Xu Han. Implement convolution in cnn. http://xuhan.me/2016/09/09/conv/, 2016.
[2] Fabian Tschopp, Julien NP Martel, Srinivas C Turaga, Matthew Cook, and Jan Funke. Efﬁcient convolutional

Retrieval Cosine Similarity: 0.6246

Query Cosine Similarity (Original vs. Similar Question): 0.8394
============================================================
Processing row 6:
Original Question:
Explain the concept of Reinforcement Learning.
Similar Question:
Search for the question: What is Reinforcement Learning and how does it enable decision-making?
============================================================
{'filters': {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'What is Reinforcement Learning and how does it enable decision-making?'}

Running Search with filters: {'query': 'Reinforcement Learning', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}
[integration] Found 1 verified paper(s).
Extracted 176 chunks from 'Some Insights into Lifelong Reinforcement Learning Systems'

Total Chunks Extracted: 176

Upserted 176 embeddings into index '8xkvyxtznx', namespace 'default'.

Comparison 1:
Original Retrieval Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Similar Retrieval Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Retrieval Cosine Similarity: 0.6869

Comparison 2:
Original Retrieval Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Similar Retrieval Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Retrieval Cosine Similarity: 0.6869

Comparison 3:
Original Retrieval Result:
reward space of the learning system. In other words,
Figure 2: Architecture of lifelong reinforcement learning
system. In contrast to traditional reinforcement learning
(Figure 1), the learning algorithm resides inside the agent.
The internal environment of the agent can be thought of as a

Similar Retrieval Result:
type of learning system. Some insights into life-
long reinforcement learning are provided, along
with a simplistic prototype lifelong reinforcement
learning system.
1. Introduction
An agent is an abstraction of a decision-maker. At each time

Retrieval Cosine Similarity: 0.6869

Query Cosine Similarity (Original vs. Similar Question): 0.8050
============================================================
Processing row 7:
Original Question:
What is the difference between Type I and Type II errors in hypothesis testing?
Similar Question:
Search for the question: How do Type I and Type II errors differ in hypothesis testing?
============================================================
{'filters': {'query': 'Type I and Type II errors in hypothesis testing', 'author': None, 'title': None, 'category': None, 'abstract': None, 'journal_ref': None, 'doi': None, 'exclude_words': None, 'start_date': None, 'end_date': None, 'max_results': '1', 'sort_by': 'relevance'}, 'question': 'How do Type I and Type II errors differ in hypothesis testing?'}


In [28]:
similarity_comparison_df

,original_question,similar_question,comparison_index,orig_retrieved_result,sim_retrieved_result,retrieval_cosine_similarity,query_cosine_similarity
0,Describe the K-means clustering algorithm.,Search for the question: Can you explain how t...,1,The relational k-means algorithm takes an init...,The relational k-means algorithm takes an init...,1.000000,0.882090
1,Describe the K-means clustering algorithm.,Search for the question: Can you explain how t...,2,The relational k-means algorithm takes an init...,The relational k-means algorithm takes an init...,1.000000,0.882090
2,Describe the K-means clustering algorithm.,Search for the question: Can you explain how t...,3,The relational k-means algorithm takes an init...,The relational k-means algorithm takes an init...,1.000000,0.882090
3,Explain the Typiclust algorithm,Search for the question: What is the fundament...,1,given in Alg. 1 (see more details in App. F.1)...,at https://github.com/avihu111/TypiClust.\n1. ...,0.494900,0.928873
4,Explain the Typiclust algorithm,Search for the question: What is the fundament...,2,given in Alg. 1 (see more details in App. F.1)...,at https://github.com/avihu111/TypiClust.\n1. ...,0.494900,0.928873
5,Explain the Typiclust algorithm,Search for the question: What is the fundament...,3,given in Alg. 1 (see more details in App. F.1)...,at https://github.com/avihu111/TypiClust.\n1. ...,0.494900,0.928873
6,What is the Support Vector Machine (SVM) and h...,Search for the question: How does a Support Ve...,1,2010 Mathematics Subject Classiﬁcation:62H30.\...,support vector machine. We also provide suﬃcie...,0.647456,0.893119
7,What is the Support Vector Machine (SVM) and h...,Search for the question: How does a Support Ve...,2,2010 Mathematics Subject Classiﬁcation:62H30.\...,support vector machine. We also provide suﬃcie...,0.647456,0.893119
8,What is the Support Vector Machine (SVM) and h...,Search for the question: How does a Support Ve...,3,2010 Mathematics Subject Classiﬁcation:62H30.\...,support vector machine. We also provide suﬃcie...,0.647456,0.893119
9,Describe the backpropagation algorithm used in...,Search for the question: How does the backprop...,1,traditional backpropagation with Gradient Desc...,traditional backpropagation with Gradient Desc...,1.000000,0.854085
10,Describe the backpropagation algorithm used in...,Search for the question: How does the backprop...,2,traditional backpropagation with Gradient Desc...,traditional backpropagation with Gradient Desc...,1.000000,0.854085
11,Describe the backpropagation algorithm used in...,Search for the question: How does the backprop...,3,traditional backpropagation with Gradient Desc...,traditional backpropagation with Gradient Desc...,1.000000,0.854085
12,What are Convolutional Neural Networks (CNN) a...,Search for the question: Can you describe what...,1,CNNs learn features to recognise shapes with a...,CNNs learn features to recognise shapes with a...,1.000000,0.839415
13,What are Convolutional Neural Networks (CNN) a...,Search for the question: Can you describe what...,2,CNNs learn features to recognise shapes with a...,CNNs learn features to recognise shapes with a...,1.000000,0.839415
14,What are Convolutional Neural Networks (CNN) a...,Search for the question: Can you describe what...,3,Fig. 1: Example CNN architecture with alternat...,References\n[1] Xu Han. Implement convolution ...,0.624587,0.839415
15,Explain the concept of Reinforcement Learning.,Search for the question: What is Reinforcement...,1,reward space of the learning system. In other ...,type of learning system. Some insights into li...,0.686934,0.805001
16,Explain the concept of Reinforcement Learning.,Search for the question: What is Reinforcement...,2,reward space of the learning system. In other ...,type of learning system. Some insights into li...,0.686934,0.805001
17,Explain the concept of Reinforcement Learning.,Search for the question: What is Reinforcement...,3,reward space of the learning system. In other ...,type of learning system. Some insights into li...,0.686934,0.805001
18,What is the difference between Type I and Type...,Search for the question: How do Type I and Typ...,1,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,Sample 2\nReject H 0\nSample 1\nConfidence Int...,0.427660,0.923597
19,What is the difference between Type I and Type...,Search for the question: How do Type I and Typ...,2,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,Sample 2\nReject H 0\nSample 1\nConfidence Int...,0.427660,0.923597
20,What is the difference between Type I and Type...,Search for the question: How do Type I and Typ...,3,ERROROCCURSWHENTHETESTACCEPTS H0 ANDH0 ISFALSE...,Sample 2\nReject H 0\nSample 1\nConfidence Int...,0.427660,0.923597
21,How does the Gradient Descent optimization alg...,Search for the question: Can you detail the pr...,1,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,1.000000,0.757021
22,How does the Gradient Descent optimization alg...,Search for the question: Can you detail the pr...,2,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,1.000000,0.757021
23,How does the Gradient Descent optimization alg...,Search for the question: Can you detail the pr...,3,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,7 Appendix\nA Preliminaries\nA.1 Gradient Desc...,1.000000,0.757021
24,What is Overfitting in machine learning and ho...,Search for the question: How can overfitting b...,1,"overﬁtting, like zero training loss, and use n...","overﬁtting, like zero training loss, and use n...",1.000000,0.867256
25,What is Overfitting in machine learning and ho...,Search for the question: How can overfitting b...,2,"overﬁtting, like zero training loss, and use n...","overﬁtting, like zero training loss, and use n...",1.000000,0.867256
26,What is Overfitting in machine learning and ho...,Search for the question: How can overfitting b...,3,"overﬁtting, like zero training loss, and use n...","overﬁtting, like zero training loss, and use n...",1.000000,0.867256
27,what is concept of Transfer Learning in deep l...,Search for the question: Can you explain the c...,1,An eﬀective solution to this challenge is to e...,An eﬀective solution to this challenge is to e...,1.000000,0.882798
28,what is concept of Transfer Learning in deep l...,Search for the question: Can you explain the c...,2,An eﬀective solution to this challenge is to e...,An eﬀective solution to this challenge is to e...,1.000000,0.882798
29,what is concept of Transfer Learning in deep l...,Search for the question: Can you explain the c...,3,An eﬀective solution to this challenge is to e...,An eﬀective solution to this challenge is to e...,1.000000,0.882798

In [29]:
logger = task.get_logger()

# comparison_df 是上面代码中生成的 DataFrame
logger.report_table(
    title="Comparison Results - all-MiniLM-L6-v2",          # 在ClearML中显示的标题
    series="Embedding Evaluation",        # 相当于分组/系列名称
    iteration=0,                         # 当前迭代（如果你没有迭代概念，可以固定为0）
    table_plot=similarity_comparison_df             # 直接传入 DataFrame
)

In [ ]:
# # TODO 
# evaluate humanlly, and use the metric, how does it use other embedding models??

In [ ]:
path = "../evaluation_data/retrieval_comparison.csv"
comparison_df.to_csv(path)

: